# Generated by Django 5.2.10 on 2026-05-07 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BasesGenerales', '0003_formatos_hudn_area_formatos_hudn_consecutivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FRQUI_095_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_oid', models.IntegerField(blank=True, help_text='Identificador único del paciente en el sistema clínico', null=True, verbose_name='OID del Paciente (Nexus)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('identificacion_paciente', models.CharField(max_length=50, verbose_name='Identificación Paciente')),
                ('indicador_quimico', models.BooleanField(default=False, verbose_name='Lectura de Indicador Químico')),
                ('indicador_biologico', models.BooleanField(default=False, verbose_name='Lectura de Indicador Biológico')),
                ('agujas_inicial', models.IntegerField(default=0, verbose_name='Agujas (Inicial)')),
                ('agujas_final', models.IntegerField(default=0, verbose_name='Agujas (Final)')),
                ('torundas_inicial', models.IntegerField(default=0, verbose_name='Torundas (Inicial)')),
                ('torundas_final', models.IntegerField(default=0, verbose_name='Torundas (Final)')),
                ('gasas_inicial', models.IntegerField(default=0, verbose_name='Gasas (Inicial)')),
                ('gasas_final', models.IntegerField(default=0, verbose_name='Gasas (Final)')),
                ('compresas_inicial', models.IntegerField(default=0, verbose_name='Compresas (Inicial)')),
                ('compresas_final', models.IntegerField(default=0, verbose_name='Compresas (Final)')),
                ('hoja_bisturi_inicial', models.IntegerField(default=0, verbose_name='Hoja Bisturí (Inicial)')),
                ('hoja_bisturi_final', models.IntegerField(default=0, verbose_name='Hoja Bisturí (Final)')),
                ('mechas_inicial', models.IntegerField(default=0, verbose_name='Mechas (Inicial)')),
                ('mechas_final', models.IntegerField(default=0, verbose_name='Mechas (Final)')),
                ('vendas_gasa_inicial', models.IntegerField(default=0, verbose_name='Vendas de Gasa (Inicial)')),
                ('vendas_gasa_final', models.IntegerField(default=0, verbose_name='Vendas de Gasa (Final)')),
                ('tetras_inicial', models.IntegerField(default=0, verbose_name='Tetras (Inicial)')),
                ('tetras_final', models.IntegerField(default=0, verbose_name='Tetras (Final)')),
                ('cotonoides_inicial', models.IntegerField(default=0, verbose_name='Cotonoides (Inicial)')),
                ('cotonoides_final', models.IntegerField(default=0, verbose_name='Cotonoides (Final)')),
                ('pinzas_inicial', models.IntegerField(default=0, verbose_name='Pinzas (Inicial)')),
                ('pinzas_final', models.IntegerField(default=0, verbose_name='Pinzas (Final)')),
                ('num_personas_cirugia', models.IntegerField(verbose_name='N° de personas en cirugía incluyendo el paciente')),
                ('puerta_cerrada', models.BooleanField(default=True, verbose_name='Se opera con puerta cerrada')),
                ('lavado_zona_operatoria_por', models.CharField(max_length=200, verbose_name='Lavado Zona Operatoria Realizado por')),
                ('descripcion_muestra', models.TextField(blank=True, null=True, verbose_name='Descripción de la muestra')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('formato_maestro', models.ForeignKey(help_text='Vínculo con el catálogo institucional de formatos', on_delete=django.db.models.deletion.PROTECT, to='BasesGenerales.formatos_hudn', verbose_name='Formato Maestro')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
            ],
            options={
                'verbose_name': 'Registro FRQUI-095',
                'verbose_name_plural': 'Registros FRQUI-095',
                'db_table': 'FRQUI_095_Data',
            },
        ),
    ]
