# Generated by Django 5.2.10 on 2026-05-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frqui_095_model',
            name='atencion_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Atención / HC'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='paciente_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Paciente'),
        ),
    ]
