# Generated by Django 5.2.10 on 2026-05-07 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos_apps', '0002_frqui_095_model_atencion_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frqui_095_model',
            name='anestesiologo_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula Anestesiólogo'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='anestesiologo_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Anestesiólogo'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='auxiliar_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula Auxiliar Circulante'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='auxiliar_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Auxiliar Circulante'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='ayudante_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula Ayudante'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='ayudante_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Ayudante'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='cirujano_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula Cirujano'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='cirujano_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Cirujano'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='eps',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='EPS'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='fecha_operacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Operación'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='procedimiento',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Procedimiento'),
        ),
    ]
