# Generated by Django 5.2.10 on 2026-05-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos_apps', '0003_frqui_095_model_anestesiologo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frqui_095_model',
            name='clasificacion_herida',
            field=models.CharField(blank=True, choices=[('LIMPIA', 'Limpia'), ('CONTAMINADA', 'Contaminada'), ('LIMPIA_CONTAMINADA', 'Limpia Contaminada'), ('SUCIA', 'Sucia')], max_length=20, null=True, verbose_name='Clasificación Herida Quirúrgica'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='electrobisturi',
            field=models.BooleanField(default=False, verbose_name='Electrobisturí (SI/NO)'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='indicador_quimico_externo',
            field=models.BooleanField(default=False, verbose_name='Indicador Químico Externo'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='indicador_quimico_interno',
            field=models.BooleanField(default=False, verbose_name='Indicador Químico Interno'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='sitio_ubicacion_placa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sitio de ubicación de placa'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='indicador_biologico',
            field=models.BooleanField(default=False, verbose_name='Indicador Biológico'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='indicador_quimico',
            field=models.BooleanField(default=False, verbose_name='Indicador Químico (General)'),
        ),
    ]
