# Generated by Django 5.2.10 on 2026-05-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos_apps', '0004_frqui_095_model_clasificacion_herida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frqui_095_model',
            name='agujas_na',
            field=models.BooleanField(default=False, verbose_name='Agujas (N/A)'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='agujas_observacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación Agujas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='agujas_responsable_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Responsable Agujas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='agujas_responsable_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Responsable Agujas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='compresas_na',
            field=models.BooleanField(default=False, verbose_name='Compresas (N/A)'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='compresas_observacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación Compresas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='compresas_responsable_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Responsable Compresas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='compresas_responsable_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Responsable Compresas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='cotonoides_na',
            field=models.BooleanField(default=False, verbose_name='Cotonoides (N/A)'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='cotonoides_observacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación Cotonoides'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='cotonoides_responsable_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Responsable Cotonoides'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='cotonoides_responsable_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Responsable Cotonoides'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='gasas_na',
            field=models.BooleanField(default=False, verbose_name='Gasas (N/A)'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='gasas_observacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación Gasas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='gasas_responsable_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Responsable Gasas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='gasas_responsable_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Responsable Gasas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='hoja_bisturi_na',
            field=models.BooleanField(default=False, verbose_name='Hoja Bisturí (N/A)'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='hoja_bisturi_observacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación Hoja Bisturí'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='hoja_bisturi_responsable_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Responsable Hoja Bisturí'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='hoja_bisturi_responsable_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Responsable Hoja Bisturí'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='mechas_na',
            field=models.BooleanField(default=False, verbose_name='Mechas (N/A)'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='mechas_observacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación Mechas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='mechas_responsable_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Responsable Mechas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='mechas_responsable_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Responsable Mechas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='pinzas_na',
            field=models.BooleanField(default=False, verbose_name='Pinzas (N/A)'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='pinzas_observacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación Pinzas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='pinzas_responsable_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Responsable Pinzas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='pinzas_responsable_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Responsable Pinzas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='tetras_na',
            field=models.BooleanField(default=False, verbose_name='Tetras (N/A)'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='tetras_observacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación Tetras'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='tetras_responsable_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Responsable Tetras'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='tetras_responsable_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Responsable Tetras'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='torundas_na',
            field=models.BooleanField(default=False, verbose_name='Torundas (N/A)'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='torundas_observacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación Torundas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='torundas_responsable_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Responsable Torundas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='torundas_responsable_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Responsable Torundas'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='vendas_gasa_na',
            field=models.BooleanField(default=False, verbose_name='Vendas de Gasa (N/A)'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='vendas_gasa_observacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación Vendas de Gasa'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='vendas_gasa_responsable_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Responsable Vendas de Gasa'),
        ),
        migrations.AddField(
            model_name='frqui_095_model',
            name='vendas_gasa_responsable_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Responsable Vendas de Gasa'),
        ),
    ]
