# Generated by Django 5.2.10 on 2026-05-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos_apps', '0005_frqui_095_model_agujas_na_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frqui_095_model',
            name='agujas_final',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Agujas (Final)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='agujas_inicial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Agujas (Inicial)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='compresas_final',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Compresas (Final)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='compresas_inicial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Compresas (Inicial)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='cotonoides_final',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cotonoides (Final)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='cotonoides_inicial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cotonoides (Inicial)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='gasas_final',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Gasas (Final)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='gasas_inicial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Gasas (Inicial)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='hoja_bisturi_final',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Hoja Bisturí (Final)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='hoja_bisturi_inicial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Hoja Bisturí (Inicial)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='mechas_final',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Mechas (Final)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='mechas_inicial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Mechas (Inicial)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='pinzas_final',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pinzas (Final)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='pinzas_inicial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pinzas (Inicial)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='tetras_final',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tetras (Final)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='tetras_inicial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tetras (Inicial)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='torundas_final',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Torundas (Final)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='torundas_inicial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Torundas (Inicial)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='vendas_gasa_final',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Vendas de Gasa (Final)'),
        ),
        migrations.AlterField(
            model_name='frqui_095_model',
            name='vendas_gasa_inicial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Vendas de Gasa (Inicial)'),
        ),
    ]
