# Generated by Django 5.2.10 on 2026-05-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos_apps', '0007_frqui_001_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frqui_001_model',
            old_name='auxiliar_entrega',
            new_name='auxiliar_entrega_nombre',
        ),
        migrations.RenameField(
            model_name='frqui_001_model',
            old_name='auxiliar_recibe',
            new_name='auxiliar_recibe_nombre',
        ),
        migrations.RenameField(
            model_name='frqui_001_model',
            old_name='enfermeria_entrega',
            new_name='enfermeria_entrega_nombre',
        ),
        migrations.RenameField(
            model_name='frqui_001_model',
            old_name='enfermeria_recibe',
            new_name='enfermeria_recibe_nombre',
        ),
        migrations.RenameField(
            model_name='frqui_001_model',
            old_name='firma_enfermera',
            new_name='firma_enfermera_nombre',
        ),
        migrations.AddField(
            model_name='frqui_001_model',
            name='auxiliar_entrega_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula Auxiliar Entrega'),
        ),
        migrations.AddField(
            model_name='frqui_001_model',
            name='auxiliar_recibe_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula Auxiliar Recibe'),
        ),
        migrations.AddField(
            model_name='frqui_001_model',
            name='enfermeria_entrega_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula Enfermería Entrega'),
        ),
        migrations.AddField(
            model_name='frqui_001_model',
            name='enfermeria_recibe_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula Enfermería Recibe'),
        ),
        migrations.AddField(
            model_name='frqui_001_model',
            name='firma_enfermera_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula Enfermera'),
        ),
    ]
