import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'HospitalManagement.settings')
django.setup()

from defenjur_py.legal.models import CatalogoAccionado

ENTIDADES = [
    ('CCF024', 'CAJA DE COMPENSACION FAMILIAR DE CARTAGENA Y BOLIVAR COMFAMILIAR - CM'),
    ('CCF033', 'CAJA DE COMPENSACION FAMILIAR DEL CHOCO - CM'),
    ('CCF035', 'CAJA DE COMPENSACION FAMILIAR DE LA GUAJIRA "COMFAGUAJIRA" - CM'),
    ('CCF050', 'CAJA DE COMPENSACION FAMILIAR DEL META "COMFAMETA" - CM'),
    ('CCF053', 'CAJA DE COMPENSACION FAMILIAR DE NARIÑO - CM'),
    ('CCF055', 'CAJA DE COMPENSACION FAMILIAR DE SUCRE - CM'),
    ('EPS001', 'ALIANZASALUD EPS S.A.'),
    ('EPS002', 'SALUD TOTAL ENTIDAD PROMOTORA DE SALUD DEL REGIMEN CONTRIBUTIVO Y DEL REGIMEN SUBSIDIADO S.A.'),
    ('EPS005', 'ENTIDAD PROMOTORA DE SALUD SANITAS S.A.S.'),
    ('EPS008', 'CAJA DE COMPENSACION FAMILIAR COMPENSAR'),
    ('EPS010', 'EPS SURAMERICANA S.A.'),
    ('EPS012', 'CAJA DE COMPENSACION FAMILIAR DEL VALLE DEL CAUCA "COMFENALCO VALLE DE LA GENTE" - CM'),
    ('EPS016', 'COOMEVA ENTIDAD PROMOTORA DE SALUD S.A. "COOMEVA EPS S.A."'),
    ('EPS017', 'EPS FAMISANAR S.A.S.'),
    ('EPS018', 'ENTIDAD PROMOTORA DE SALUD SERVICIO OCCIDENTAL DE SALUD S.A. S.O.S.'),
    ('EPS037', 'NUEVA EPS S.A.'),
    ('EPS040', 'ALIANZA MEDELLIN ANTIOQUIA EPS S.A.S. "SAVIA SALUD EPS" - CM'),
    ('EPS044', 'ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SALUD ENTIDAD PROMOTORA DE SALUD - MUTUAL SER EPS'),
    ('EPS045', 'CAPITAL SALUD ENTIDAD PROMOTORA DE SALUD DEL REGIMEN SUBSIDIADO SAS "CAPITAL SALUD EPS-S S.A.S." - CM'),
    ('EPS046', 'FUNDACION SALUD MIA - CM'),
    ('EPS048', 'ASMET SALUD EPS S.A.S.'),
    ('ESS024', 'ASOCIACION MUTUAL BARRIOS UNIDOS DE QUIBDO AMBUQ EPS - S - ESS'),
    ('ESS062', 'ASOCIACION INDIGENA DEL CAUCA AIC EPS-I - CM'),
    ('ESS091', 'EMPRESA PROMOTORA DE SALUD INDIGENA ANAS WAYUU EPSI - CM'),
    ('ESS118', 'ENTIDAD PROMOTORA DE SALUD MALLAMAS EPSI - CM'),
    ('EMP002', 'MEDPLUS MEDICINA PREPAGADA S.A.'),
    ('EMP015', 'COMPAÑIA DE MEDICINA PREPAGADA COLSANITAS S.A.'),
    ('EMP017', 'MEDISANITAS S.A COMPAÑIA DE MEDICINA PREPAGADA'),
    ('EMP019', 'COLMEDICA MEDICINA PREPAGADA'),
    ('RES001', 'UNIVERSIDAD DE ANTIOQUIA'),
    ('RES006', 'UNIVERSIDAD DEL CAUCA'),
    ('RES007', 'UNIVERSIDAD DEL VALLE'),
    ('RES008', 'UNIVERSIDAD NACIONAL DE COLOMBIA'),
    ('FMS001', 'FUERZAS MILITARES'),
    ('POL001', 'POLICIA NACIONAL'),
    ('ECO001', 'ECOPETROL'),
    ('MAG001', 'MAGISTERIO'),
]

for nit, nombre in ENTIDADES:
    CatalogoAccionado.objects.get_or_create(nombre=nombre, defaults={'nit': nit})

print("Entidades cargadas exitosamente.")
