import os
import django

# Configuración de Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'HospitalManagement.settings')
django.setup()

from BasesGenerales.models import Geo01Pais

def populate_countries():
    paises = [
        ('AFG', 'Afganistán', 'Afganistán'),
        ('ALA', 'Åland', 'Åland, Islas'),
        ('ALB', 'Albania', 'Albania'),
        ('DEU', 'Alemania', 'Alemania'),
        ('AND', 'Andorra', 'Andorra'),
        ('AGO', 'Angola', 'Angola'),
        ('AIA', 'Anguila', 'Anguila'),
        ('ATA', 'Antártida', 'Antártida'),
        ('ATG', 'Antigua y Barbuda', 'Antigua y Barbuda'),
        ('SAU', 'Arabia Saudita', 'Arabia Saudita'),
        ('DZA', 'Argelia', 'Argelia'),
        ('ARG', 'Argentina', 'Argentina'),
        ('ARM', 'Armenia', 'Armenia'),
        ('ABW', 'Aruba', 'Aruba'),
        ('AUS', 'Australia', 'Australia'),
        ('AUT', 'Austria', 'Austria'),
        ('AZE', 'Azerbaiyán', 'Azerbaiyán'),
        ('BHS', 'Bahamas', 'Bahamas (las)'),
        ('BGD', 'Bangladés', 'Bangladés'),
        ('BRB', 'Barbados', 'Barbados'),
        ('BHR', 'Baréin', 'Baréin'),
        ('BEL', 'Bélgica', 'Bélgica'),
        ('BLZ', 'Belice', 'Belice'),
        ('BEN', 'Benín', 'Benín'),
        ('BMU', 'Bermudas', 'Bermudas'),
        ('BLR', 'Bielorrusia', 'Belarús'),
        ('BOL', 'Bolivia', 'Bolivia (Estado Plurinacional de)'),
        ('BES', 'Bonaire, San Eustaquio y Saba', 'Bonaire, San Eustaquio y Saba'),
        ('BIH', 'Bosnia y Herzegovina', 'Bosnia y Herzegovina'),
        ('BWA', 'Botsuana', 'Botsuana'),
        ('BRA', 'Brasil', 'Brasil'),
        ('BRN', 'Brunéi', 'Brunéi Darussalam'),
        ('BGR', 'Bulgaria', 'Bulgaria'),
        ('BFA', 'Burkina Faso', 'Burkina Faso'),
        ('BDI', 'Burundi', 'Burundi'),
        ('BTN', 'Bután', 'Bhután'),
        ('CPV', 'Cabo Verde', 'Cabo Verde'),
        ('KHM', 'Camboya', 'Camboya'),
        ('CMR', 'Camerún', 'Camerún'),
        ('CAN', 'Canadá', 'Canadá'),
        ('QAT', 'Catar', 'Catar'),
        ('TCD', 'Chad', 'Chad'),
        ('CHL', 'Chile', 'Chile'),
        ('CHN', 'China', 'China'),
        ('CYP', 'Chipre', 'Chipre'),
        ('COL', 'Colombia', 'Colombia'),
        ('COM', 'Comoras', 'Comoras (las)'),
        ('PRK', 'Corea del Norte', 'Corea (la República Popular Democrática de)'),
        ('KOR', 'Corea del Sur', 'Corea (la República de)'),
        ('CIV', 'Costa de Marfil', "Côte d'Ivoire"),
        ('CRI', 'Costa Rica', 'Costa Rica'),
        ('HRV', 'Croacia', 'Croacia'),
        ('CUB', 'Cuba', 'Cuba'),
        ('CUW', 'Curazao', 'Curaçao'),
        ('DNK', 'Dinamarca', 'Dinamarca'),
        ('DMA', 'Dominica', 'Dominica'),
        ('ECU', 'Ecuador', 'Ecuador'),
        ('EGY', 'Egipto', 'Egipto'),
        ('SLV', 'El Salvador', 'El Salvador'),
        ('ARE', 'EAU', 'Emiratos Árabes Unidos (los)'),
        ('ERI', 'Eritrea', 'Eritrea'),
        ('SVK', 'Eslovaquia', 'Eslovaquia'),
        ('SVN', 'Eslovenia', 'Eslovenia'),
        ('ESP', 'España', 'España'),
        ('USA', 'Estados Unidos', 'Estados Unidos de América (los)'),
        ('EST', 'Estonia', 'Estonia'),
        ('ETH', 'Etiopía', 'Etiopía'),
        ('PHL', 'Filipinas', 'Filipinas (las)'),
        ('FIN', 'Finlandia', 'Finlandia'),
        ('FJI', 'Fiyi', 'Fiyi'),
        ('FRA', 'Francia', 'Francia'),
        ('GAB', 'Gabón', 'Gabón'),
        ('GMB', 'Gambia', 'Gambia (la)'),
        ('GEO', 'Georgia', 'Georgia'),
        ('GHA', 'Ghana', 'Ghana'),
        ('GIB', 'Gibraltar', 'Gibraltar'),
        ('GRD', 'Granada', 'Granada'),
        ('GRC', 'Grecia', 'Grecia'),
        ('GRL', 'Groenlandia', 'Groenlandia'),
        ('GLP', 'Guadalupe', 'Guadeloupe'),
        ('GUM', 'Guam', 'Guam'),
        ('GTM', 'Guatemala', 'Guatemala'),
        ('GUF', 'Guayana Francesa', 'Guayana Francesa'),
        ('GGY', 'Guernsey', 'Guernsey'),
        ('GIN', 'Guinea', 'Guinea'),
        ('GNB', 'Guinea-Bisáu', 'Guinea Bissau'),
        ('GNQ', 'Guinea Ecuatorial', 'Guinea Ecuatorial'),
        ('GUY', 'Guyana', 'Guyana'),
        ('HTI', 'Haití', 'Haití'),
        ('HND', 'Honduras', 'Honduras'),
        ('HKG', 'Hong Kong', 'Hong Kong'),
        ('HUN', 'Hungría', 'Hungría'),
        ('IND', 'India', 'India'),
        ('IDN', 'Indonesia', 'Indonesia'),
        ('IRQ', 'Irak', 'Irak'),
        ('IRN', 'Irán', 'Irán (República Islámica de)'),
        ('IRL', 'Irlanda', 'Irlanda'),
        ('BVT', 'Isla Bouvet', 'Bouvet, Isla'),
        ('IMN', 'Isla de Man', 'Isla de Man'),
        ('CXR', 'Isla de Navidad', 'Navidad, Isla de'),
        ('ISL', 'Islandia', 'Islandia'),
        ('CYM', 'Islas Caimán', 'Caimán, (las) Islas'),
        ('CCK', 'Islas Cocos', 'Cocos / Keeling, (las) Islas'),
        ('COK', 'Islas Cook', 'Cook, (las) Islas'),
        ('FRO', 'Islas Feroe', 'Feroe, (las) Islas'),
        ('SGS', 'Islas Georgias del Sur y Sandwich del Sur', 'Georgia del Sur (la) y las Islas Sandwich del Sur'),
        ('HMD', 'Islas Heard y McDonald', 'Heard (Isla) e Islas McDonald'),
        ('FLK', 'Islas Malvinas', 'Malvinas [Falkland], (las) Islas'),
        ('MNP', 'Islas Marianas del Norte', 'Marianas del Norte, (las) Islas'),
        ('MHL', 'Islas Marshall', 'Marshall, (las) Islas'),
        ('PCN', 'Islas Pitcairn', 'Pitcairn'),
        ('SLB', 'Islas Salomón', 'Salomón, Islas'),
        ('TCA', 'Islas Turcas y Caicos', 'Turcas y Caicos, (las) Islas'),
        ('UMI', 'Islas Ultramarinas Menores de los Estados Unidos', 'Islas Ultramarinas Menores de los Estados Unidos (las)'),
        ('VGB', 'Islas Vírgenes Británicas', 'Vírgenes británicas, Islas'),
        ('VIR', 'Islas Vírgenes de los Estados Unidos', 'Vírgenes de los Estados Unidos, Islas'),
        ('ISR', 'Israel', 'Israel'),
        ('ITA', 'Italia', 'Italia'),
        ('JAM', 'Jamaica', 'Jamaica'),
        ('JPN', 'Japón', 'Japón'),
        ('JEY', 'Jersey', 'Jersey'),
        ('JOR', 'Jordania', 'Jordania'),
        ('KAZ', 'Kazajistán', 'Kazajistán'),
        ('KEN', 'Kenia', 'Kenia'),
        ('KGZ', 'Kirguistán', 'Kirguistán'),
        ('KIR', 'Kiribati', 'Kiribati'),
        ('KWT', 'Kuwait', 'Kuwait'),
        ('LAO', 'Laos', 'Lao, (la) República Democrática Popular'),
        ('LSO', 'Lesoto', 'Lesoto'),
        ('LVA', 'Letonia', 'Letonia'),
        ('LBN', 'Líbano', 'Líbano'),
        ('LBR', 'Liberia', 'Liberia'),
        ('LBY', 'Libia', 'Libia'),
        ('LIE', 'Liechtenstein', 'Liechtenstein'),
        ('LTU', 'Lituania', 'Lituania'),
        ('LUX', 'Luxemburgo', 'Luxemburgo'),
        ('MAC', 'Macao', 'Macao'),
        ('MKD', 'Macedonia del Norte', 'Macedonia del Norte'),
        ('MDG', 'Madagascar', 'Madagascar'),
        ('MYS', 'Malasia', 'Malasia'),
        ('MWI', 'Malaui', 'Malawi'),
        ('MDV', 'Maldivas', 'Maldivas'),
        ('MLI', 'Mali', 'Malí'),
        ('MLT', 'Malta', 'Malta'),
        ('MAR', 'Marruecos', 'Marruecos'),
        ('MTQ', 'Martinica', 'Martinique'),
        ('MUS', 'Mauricio', 'Mauricio'),
        ('MRT', 'Mauritania', 'Mauritania'),
        ('MYT', 'Mayotte', 'Mayotte'),
        ('MEX', 'México', 'México'),
        ('FSM', 'Micronesia', 'Micronesia (Estados Federados de)'),
        ('MDA', 'Moldavia', 'Moldavia (la República de)'),
        ('MCO', 'Mónaco', 'Mónaco'),
        ('MNG', 'Mongolia', 'Mongolia'),
        ('MNE', 'Montenegro', 'Montenegro'),
        ('MSR', 'Montserrat', 'Montserrat'),
        ('MOZ', 'Mozambique', 'Mozambique'),
        ('MMR', 'Birmania', 'Myanmar'),
        ('NAM', 'Namibia', 'Namibia'),
        ('NRU', 'Nauru', 'Nauru'),
        ('NPL', 'Nepal', 'Nepal'),
        ('NIC', 'Nicaragua', 'Nicaragua'),
        ('NER', 'Níger', 'Níger (el)'),
        ('NGA', 'Nigeria', 'Nigeria'),
        ('NIU', 'Niue', 'Niue'),
        ('NFK', 'Isla Norfolk', 'Norfolk, Isla'),
        ('NOR', 'Noruega', 'Noruega'),
        ('NCL', 'Nueva Caledonia', 'Nueva Caledonia'),
        ('NZL', 'Nueva Zelanda', 'Nueva Zelandia'),
        ('OMN', 'Omán', 'Omán'),
        ('NLD', 'Países Bajos', 'Países Bajos (los)'),
        ('PAK', 'Pakistán', 'Pakistán'),
        ('PLW', 'Palaos', 'Palaos'),
        ('PSE', 'Palestina', 'Palestina, Estado de'),
        ('PAN', 'Panamá', 'Panamá'),
        ('PNG', 'Papúa Nueva Guinea', 'Papúa Nueva Guinea'),
        ('PRY', 'Paraguay', 'Paraguay'),
        ('PER', 'Perú', 'Perú'),
        ('PYF', 'Polinesia Francesa', 'Polinesia Francesa'),
        ('POL', 'Polonia', 'Polonia'),
        ('PRT', 'Portugal', 'Portugal'),
        ('PRI', 'Puerto Rico', 'Puerto Rico'),
        ('ESH', 'República Árabe Saharaui Democrática', 'Sahara Occidental'),
        ('CAF', 'República Centroafricana', 'República Centroafricana (la)'),
        ('CZE', 'República Checa', 'Chequia'),
        ('COG', 'República del Congo', 'Congo (el)'),
        ('COD', 'República Democrática del Congo', 'Congo (la República Democrática del)'),
        ('DOM', 'República Dominicana', 'Dominicana, (la) República'),
        ('REU', 'Reunión', 'Reunión'),
        ('RWA', 'Ruanda', 'Ruanda'),
        ('ROU', 'Rumania', 'Rumania'),
        ('RUS', 'Rusia', 'Rusia, (la) Federación de'),
        ('WSM', 'Samoa', 'Samoa'),
        ('ASM', 'Samoa Americana', 'Samoa Americana'),
        ('BLM', 'San Bartolomé', 'Saint Barthélemy'),
        ('KNA', 'San Cristóbal y Nieves', 'San Cristóbal y Nieves'),
        ('SMR', 'San Marino', 'San Marino'),
        ('MAF', 'San Martín', 'Saint Martin (parte francesa)'),
        ('SPM', 'San Pedro y Miquelón', 'San Pedro y Miquelón'),
        ('VCT', 'San Vicente y las Granadinas', 'San Vicente y las Granadinas'),
        ('SHN', 'Santa Elena, Ascensión y Tristán de Acuña', 'Santa Helena, Ascensión y Tristán de Acuña'),
        ('LCA', 'Santa Lucía', 'Santa Lucía'),
        ('STP', 'Santo Tomé y Príncipe', 'Santo Tomé y Príncipe'),
        ('SEN', 'Senegal', 'Senegal'),
        ('SRB', 'Serbia', 'Serbia'),
        ('SYC', 'Seychelles', 'Seychelles'),
        ('SLE', 'Sierra Leona', 'Sierra leona'),
        ('SGP', 'Singapur', 'Singapur'),
        ('SXM', 'San Martín', 'Sint Maarten (parte neerlandesa)'),
        ('SYR', 'Siria', 'República Árabe Siria'),
        ('SOM', 'Somalia', 'Somalia'),
        ('LKA', 'Sri Lanka', 'Sri Lanka'),
        ('SWZ', 'Suazilandia', 'Suazilandia'),
        ('ZAF', 'Sudáfrica', 'Sudáfrica'),
        ('SDN', 'Sudán', 'Sudán (el)'),
        ('SSD', 'Sudán del Sur', 'Sudán del Sur'),
        ('SWE', 'Suecia', 'Suecia'),
        ('CHE', 'Suiza', 'Suiza'),
        ('SUR', 'Surinam', 'Suriname'),
        ('SJM', 'Svalbard y Jan Mayen', 'Svalbard y Jan Mayen'),
        ('THA', 'Tailandia', 'Tailandia'),
        ('TWN', 'Taiwán (República de China)', 'Taiwán (Provincia de China)'),
        ('TZA', 'Tanzania', 'Tanzania, República Unida de'),
        ('TJK', 'Tayikistán', 'Tayikistán'),
        ('IOT', 'Territorio Británico del Océano Índico', 'Territorio Británico del Océano Índico (el)'),
        ('ATF', 'Tierras Australes y Antárticas Francesas', 'Tierras Australes Francesas (las)'),
        ('TLS', 'Timor Oriental', 'Timor-Leste'),
        ('TGO', 'Togo', 'Togo'),
        ('TKL', 'Tokelau', 'Tokelau'),
        ('TON', 'Tonga', 'Tonga'),
        ('TTO', 'Trinidad y Tobago', 'Trinidad y Tobago'),
        ('TUN', 'Túnez', 'Túnez'),
        ('TKM', 'Turkmenistán', 'Turkmenistán'),
        ('TUR', 'Turquía', 'Turquía'),
        ('TUV', 'Tuvalu', 'Tuvalu'),
        ('UKR', 'Ucrania', 'Ucrania'),
        ('UGA', 'Uganda', 'Uganda'),
        ('URY', 'Uruguay', 'Uruguay'),
        ('UZB', 'Uzbekistán', 'Uzbekistán'),
        ('VUT', 'Vanuatu', 'Vanuatu'),
        ('VAT', 'Ciudad del Vaticano', 'Santa Sede (la)'),
        ('VEN', 'Venezuela', 'Venezuela (República Bolivariana de)'),
        ('VNM', 'Vietnam', 'Viet Nam'),
        ('WLF', 'Wallis y Futuna', 'Wallis y Futuna'),
        ('YEM', 'Yemen', 'Yemen'),
        ('DJI', 'Yibuti', 'Yibuti'),
        ('ZMB', 'Zambia', 'Zambia'),
        ('ZWE', 'Zimbabue', 'Zimbabue')
    ]

    count = 0
    # Usamos un set para evitar duplicados en la lista de tuplas
    seen_codes = set()
    
    for codigo, nombre, descripcion in paises:
        if codigo in seen_codes:
            continue
        seen_codes.add(codigo)
        
        obj, created = Geo01Pais.objects.get_or_create(
            codigo=codigo,
            defaults={'nombre': nombre, 'descripcion': descripcion}
        )
        if created:
            count += 1
            print(f"Añadido: {nombre}")
        else:
            # Si ya existe, actualizamos el nombre por si acaso
            obj.nombre = nombre
            obj.descripcion = descripcion
            obj.save()
            print(f"Actualizado: {nombre}")
    
    print(f"\nProceso finalizado. Total de países en base de datos: {Geo01Pais.objects.count()}.")

if __name__ == "__main__":
    populate_countries()
