# Generated by Django 5.2.10 on 2026-04-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Módulo')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (Identificador para permisos)')),
                ('description', models.TextField(verbose_name='Descripción Corta')),
                ('url', models.CharField(max_length=255, verbose_name='URL o Ruta (ej: /parto/)')),
                ('category', models.CharField(choices=[('asistencial', 'Asistencial'), ('administrativo', 'Administrativo'), ('varios', 'Varios'), ('consultas', 'Consultas'), ('talento_humano', 'Talento Humano')], default='asistencial', max_length=20, verbose_name='Categoría')),
                ('icon', models.TextField(blank=True, help_text="Solo la cadena d='...' del path", null=True, verbose_name='Icono (Path SVG)')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de aparición')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Módulo de DashBOard',
                'verbose_name_plural': 'Módulos de DashBOard',
                'ordering': ['order', 'name'],
            },
        ),
    ]
