# Generated by Django 5.2.10 on 2026-04-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodule',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug (Identificador para permisos)'),
        ),
    ]
