# Generated by Django 5.2.10 on 2026-04-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dashboardmodule_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardmodule',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Módulo de Inicio', 'verbose_name_plural': 'Módulos de Inicio'},
        ),
        migrations.AlterField(
            model_name='dashboardmodule',
            name='category',
            field=models.CharField(choices=[('asistencial', 'ASISTENCIAL'), ('administrativo', 'ADMINISTRATIVO'), ('juridica', 'JURIDICA'), ('talento_humano', 'TALENTO HUMANO'), ('contabilidad', 'CONTABILIDAD'), ('financiera', 'BIENES Y SERVICIOS - FINANCIERA'), ('varios', 'VARIOS'), ('consultas', 'CONSULTAS')], default='asistencial', max_length=20, verbose_name='Categoría'),
        ),
    ]
