# Generated by Django 5.2.10 on 2026-04-17 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('responsable', models.CharField(max_length=120)),
                ('orden', models.SmallIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pys_areas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EncuestaRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=150)),
                ('fecha_retiro', models.DateField()),
                ('aspectos_positivos', models.TextField(blank=True, null=True)),
                ('actividades_sugeridas', models.TextField(blank=True, null=True)),
                ('calif_compañeros', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('mala', 'Mala')], max_length=15, null=True)),
                ('calif_formacion', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('mala', 'Mala')], max_length=15, null=True)),
                ('calif_ambiente', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('mala', 'Mala')], max_length=15, null=True)),
                ('calif_reconocimiento', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('mala', 'Mala')], max_length=15, null=True)),
                ('calif_carga_trabajo', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('mala', 'Mala')], max_length=15, null=True)),
                ('calif_superior', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('mala', 'Mala')], max_length=15, null=True)),
                ('calif_beneficios', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('mala', 'Mala')], max_length=15, null=True)),
                ('calif_salario', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('mala', 'Mala')], max_length=15, null=True)),
                ('calif_valores', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('mala', 'Mala')], max_length=15, null=True)),
                ('calif_cultura', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('mala', 'Mala')], max_length=15, null=True)),
                ('calif_trabajo_equipo', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('mala', 'Mala')], max_length=15, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pys_encuestas_retiro',
            },
        ),
        migrations.CreateModel(
            name='LogAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usunombre', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=30)),
                ('accion', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=10)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pys_log_accesos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='PazSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('dependencia', models.CharField(max_length=150)),
                ('coordinador', models.CharField(max_length=150)),
                ('fecha_retiro', models.DateField()),
                ('estado', models.CharField(choices=[('EN_TRAMITE', 'En Trámite'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='EN_TRAMITE', max_length=20)),
                ('archivado', models.BooleanField(default=False)),
                ('creado_por', models.CharField(max_length=100)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pys_paz_salvos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=20)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADA', 'Procesada')], default='PENDIENTE', max_length=15)),
                ('procesado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pys_solicitudes_ps',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usunombre', models.CharField(max_length=100, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('dependencia', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('foto_url', models.CharField(blank=True, max_length=500, null=True)),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro')], default='claro', max_length=10)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('total_logins', models.PositiveIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pys_usuarios_app',
            },
        ),
        migrations.CreateModel(
            name='ListaBlanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usunombre', models.CharField(max_length=100, unique=True)),
                ('usuemail', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('avatar', models.CharField(default='US', max_length=4)),
                ('rol', models.CharField(choices=[('paz_salvo', 'Paz y Salvo'), ('permisos', 'Permisos'), ('validador', 'Validador'), ('firmador', 'Firmador'), ('admin', 'Admin')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paz_y_salvo.area')),
            ],
            options={
                'db_table': 'pys_lista_blanca',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=150)),
                ('asunto', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ERROR', 'Error')], max_length=10)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paz_y_salvo.area')),
                ('ps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paz_y_salvo.pazsalvo')),
            ],
            options={
                'db_table': 'pys_email_log',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPSArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('contenido', models.BinaryField(max_length='max')),
                ('tipo_mime', models.CharField(default='application/octet-stream', max_length=100)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='paz_y_salvo.solicitudps')),
            ],
            options={
                'db_table': 'pys_solicitudes_ps_archivos',
            },
        ),
        migrations.CreateModel(
            name='FirmanteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_label', models.CharField(max_length=100)),
                ('orden', models.SmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('lb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paz_y_salvo.listablanca')),
            ],
            options={
                'db_table': 'pys_firmantes_config',
                'ordering': ['orden'],
                'unique_together': {('lb', 'rol_label')},
            },
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paz_y_salvo.area')),
                ('ps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='paz_y_salvo.pazsalvo')),
            ],
            options={
                'db_table': 'pys_validaciones',
                'unique_together': {('ps', 'area')},
            },
        ),
    ]
