# Generated by Django 5.2.10 on 2026-04-10 19:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_oid', models.IntegerField(verbose_name='ID Empleado (OID)')),
                ('nombre_empleado', models.CharField(blank=True, max_length=255, verbose_name='Nombre Completo')),
                ('documento_empleado', models.CharField(blank=True, max_length=50, verbose_name='Documento')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Labores')),
                ('horas_recargo_nocturno', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='H. Recargo Nocturno (35%)')),
                ('horas_recargo_dominical_diurno', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='H. Dominical/Festiva Diurna (75%)')),
                ('horas_recargo_dominical_nocturno', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='H. Dominical/Festiva Nocturna (110%)')),
                ('horas_extra_diurna', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='H. Extra Diurna (25%)')),
                ('horas_extra_nocturna', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='H. Extra Nocturna (75%)')),
                ('horas_extra_dominical_diurna', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='H. Extra Dominical/Festiva Diurna (100%)')),
                ('horas_extra_dominical_nocturna', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='H. Extra Dominical/Festiva Nocturna (150%)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Carga de Hora Extra',
                'verbose_name_plural': 'Carga de Horas Extras y Recargos',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
