# Generated by Django 5.2.10 on 2026-04-15 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaRecargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Área (Recargos)',
                'verbose_name_plural': 'Áreas (Recargos)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ObservacionMensualRecargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('observacion', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Observación Mensual (Recargos)',
                'verbose_name_plural': 'Observaciones Mensuales (Recargos)',
                'unique_together': {('empleado_id', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PerfilRecargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('coordinador', 'Coordinador')], default='coordinador', max_length=15)),
                ('documento', models.CharField(blank=True, default='', max_length=20)),
                ('areas', models.ManyToManyField(blank=True, related_name='coordinadores', to='horas_extras.arearecargos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_recargos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Recargos',
                'verbose_name_plural': 'Perfiles Recargos',
            },
        ),
        migrations.CreateModel(
            name='TrabajadorRecargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(blank=True, default='', max_length=100)),
                ('tipo', models.CharField(choices=[('permanente', 'Planta Permanente'), ('temporal', 'Planta Temporal'), ('ops', 'OPS')], default='permanente', max_length=15)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='horas_extras.arearecargos')),
            ],
            options={
                'verbose_name': 'Trabajador (Recargos)',
                'verbose_name_plural': 'Trabajadores (Recargos)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TurnoRecargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_id', models.IntegerField(help_text='ID del empleado (SQL Server o local)')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('manana', 'Mañana (07:00–13:00)'), ('tarde', 'Tarde (13:00–19:00)'), ('noche', 'Noche (19:00–07:00)'), ('manana_tarde', 'Mañana-Tarde (07:00–19:00)'), ('veinticuatro', '24 Horas (07:00–07:00)'), ('por_horas', 'Por horas'), ('libre', 'Libre')], max_length=15)),
                ('observaciones', models.CharField(blank=True, default='', max_length=500)),
                ('horas_diurnas', models.IntegerField(blank=True, default=None, null=True)),
                ('horas_nocturnas', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Turno (Recargos)',
                'verbose_name_plural': 'Turnos (Recargos)',
                'ordering': ['fecha'],
                'unique_together': {('empleado_id', 'fecha')},
            },
        ),
    ]
