# Generated by Django 5.2.10 on 2026-04-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0002_arearecargos_observacionmensualrecargos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinadorRecargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(blank=True, default='', max_length=100)),
                ('areas', models.ManyToManyField(blank=True, related_name='coordinadores_recargos', to='horas_extras.arearecargos')),
            ],
            options={
                'verbose_name': 'Coordinador (Recargos)',
                'verbose_name_plural': 'Coordinadores (Recargos)',
                'ordering': ['nombre'],
            },
        ),
    ]
