# Generated by Django 5.2.10 on 2026-04-24 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0003_coordinadorrecargos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadorrecargos',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='horas_extras.arearecargos'),
        ),
    ]
