# Generated by Django 5.2.10 on 2026-05-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0007_alter_turnorecargos_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesConfigRecargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('habilitado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Configuración Mes (Recargos)',
                'verbose_name_plural': 'Configuraciones de Meses (Recargos)',
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
