# Generated by Django 5.2.10 on 2026-05-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0008_mes_config_recargos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotEmpleadoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('empleado_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(blank=True, default='', max_length=20)),
                ('cargo', models.CharField(blank=True, default='', max_length=100)),
                ('area_id', models.IntegerField(null=True)),
                ('area_nombre', models.CharField(blank=True, default='', max_length=100)),
                ('tipo', models.CharField(default='permanente', max_length=15)),
            ],
            options={
                'verbose_name': 'Snapshot Empleado-Área',
                'verbose_name_plural': 'Snapshots Empleado-Área',
                'ordering': ['year', 'month', 'nombre'],
                'unique_together': {('year', 'month', 'empleado_id')},
            },
        ),
    ]
