# Generated by Django 5.2.10 on 2026-05-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0009_snapshot_empleado_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnorecargos',
            name='turno',
            field=models.CharField(choices=[('manana', 'Mañana (07:00–13:00)'), ('tarde', 'Tarde (13:00–19:00)'), ('noche', 'Noche (19:00–07:00)'), ('manana_noche', 'Mañana-Noche (07:00–13:00 / 19:00–07:00)'), ('manana_tarde', 'Mañana-Tarde (07:00–19:00)'), ('veinticuatro', '24 Horas (07:00–07:00)'), ('por_horas', 'Por horas'), ('libre', 'Libre'), ('vacaciones', 'V - Vacaciones'), ('licencia', 'LI - Licencia'), ('permiso', 'P - Permiso'), ('incapacidad', 'INC - Incapacidad')], max_length=15),
        ),
    ]
