# Generated by Django 5.2.13 on 2026-04-10 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0005_derechopeticion_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagosentenciajudicial',
            options={'verbose_name': 'Pago de sentencia judicial', 'verbose_name_plural': 'Pagos de Sentencias Judiciales'},
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='abogado_responsable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Abogado responsable'),
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='demandado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Demandado'),
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='demandante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Demandante'),
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='despacho_tramitante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Despacho tramitante'),
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='fecha_ejecutoria_sentencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha ejecutoria sentencia'),
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='fecha_pago',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha pago'),
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha registro'),
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='imputacion_costo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Imputación costo'),
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='medio_control',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Medio de control'),
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='num_proceso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° proceso'),
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='tipo_pago',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de pago'),
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='valor_pagado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor pagado'),
        ),
    ]
