# Generated by Django 5.2.13 on 2026-04-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0007_peritaje_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procesoadministrativosancionatorio',
            options={'verbose_name': 'Proceso administrativo sancionatorio', 'verbose_name_plural': 'Procesos Administrativos Sancionatorios'},
        ),
        migrations.AlterField(
            model_name='procesoadministrativosancionatorio',
            name='causa',
            field=models.TextField(blank=True, null=True, verbose_name='Causa'),
        ),
        migrations.AlterField(
            model_name='procesoadministrativosancionatorio',
            name='entidad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='procesoadministrativosancionatorio',
            name='entidad_solicitante_requerimiento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entidad solicitante'),
        ),
        migrations.AlterField(
            model_name='procesoadministrativosancionatorio',
            name='estado',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='procesoadministrativosancionatorio',
            name='fecha_dar_tramite_desde',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha dar trámite desde'),
        ),
        migrations.AlterField(
            model_name='procesoadministrativosancionatorio',
            name='fecha_dar_tramite_hasta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha dar trámite hasta'),
        ),
        migrations.AlterField(
            model_name='procesoadministrativosancionatorio',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro'),
        ),
        migrations.AlterField(
            model_name='procesoadministrativosancionatorio',
            name='fecha_requerimiento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha requerimiento'),
        ),
        migrations.AlterField(
            model_name='procesoadministrativosancionatorio',
            name='num_proceso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° proceso'),
        ),
        migrations.AlterField(
            model_name='procesoadministrativosancionatorio',
            name='objeto_requerimiento',
            field=models.TextField(blank=True, null=True, verbose_name='Objeto del requerimiento'),
        ),
    ]
