# Generated by Django 5.2.10 on 2026-04-15 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0012_requerimiento_ente_verbose_and_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
