# Generated by Django 5.2.10 on 2026-04-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0013_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('TERMINADO', 'Terminado'), ('TRAMITE', 'En Trámite')], max_length=255, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='medio_control',
            field=models.CharField(blank=True, choices=[('REPARACION_DIRECTA', 'Reparación Directa'), ('NULIDAD_RESTABLECIMIENTO', 'Nulidad y Restablecimiento del Derecho'), ('ACCION_POPULAR', 'Acción Popular'), ('ACCION_CUMPLIMIENTO', 'Acción de Cumplimiento'), ('ACCION_TUTELA', 'Acción de Tutela'), ('OTROS', 'Otros')], max_length=255, null=True, verbose_name='Medio de control'),
        ),
        migrations.AlterField(
            model_name='procesoadministrativosancionatorio',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('TERMINADO', 'Terminado'), ('TRAMITE', 'En Trámite')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='procesoextrajudicial',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('TERMINADO', 'Terminado'), ('TRAMITE', 'En Trámite')], default='TRAMITE', max_length=120),
        ),
        migrations.AlterField(
            model_name='procesoextrajudicial',
            name='medio_control',
            field=models.CharField(choices=[('REPARACION_DIRECTA', 'Reparación Directa'), ('NULIDAD_RESTABLECIMIENTO', 'Nulidad y Restablecimiento del Derecho'), ('ACCION_POPULAR', 'Acción Popular'), ('ACCION_CUMPLIMIENTO', 'Acción de Cumplimiento'), ('ACCION_TUTELA', 'Acción de Tutela'), ('OTROS', 'Otros')], default='OTROS', max_length=255),
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='medio_control',
            field=models.CharField(blank=True, choices=[('REPARACION_DIRECTA', 'Reparación Directa'), ('NULIDAD_RESTABLECIMIENTO', 'Nulidad y Restablecimiento del Derecho'), ('ACCION_POPULAR', 'Acción Popular'), ('ACCION_CUMPLIMIENTO', 'Acción de Cumplimiento'), ('ACCION_TUTELA', 'Acción de Tutela'), ('OTROS', 'Otros')], max_length=255, null=True, verbose_name='Medio de control'),
        ),
        migrations.AlterField(
            model_name='procesojudicialpasiva',
            name='medio_control',
            field=models.CharField(blank=True, choices=[('REPARACION_DIRECTA', 'Reparación Directa'), ('NULIDAD_RESTABLECIMIENTO', 'Nulidad y Restablecimiento del Derecho'), ('ACCION_POPULAR', 'Acción Popular'), ('ACCION_CUMPLIMIENTO', 'Acción de Cumplimiento'), ('ACCION_TUTELA', 'Acción de Tutela'), ('OTROS', 'Otros')], max_length=255, null=True, verbose_name='Medio de control'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='medio_control',
            field=models.CharField(blank=True, choices=[('REPARACION_DIRECTA', 'Reparación Directa'), ('NULIDAD_RESTABLECIMIENTO', 'Nulidad y Restablecimiento del Derecho'), ('ACCION_POPULAR', 'Acción Popular'), ('ACCION_CUMPLIMIENTO', 'Acción de Cumplimiento'), ('ACCION_TUTELA', 'Acción de Tutela'), ('OTROS', 'Otros')], max_length=255, null=True, verbose_name='Medio de control'),
        ),
        migrations.AddIndex(
            model_name='acciontutela',
            index=models.Index(fields=['num_proceso'], name='defenjur_ap_num_pro_73cf18_idx'),
        ),
        migrations.AddIndex(
            model_name='acciontutela',
            index=models.Index(fields=['num_reparto'], name='defenjur_ap_num_rep_d0aa07_idx'),
        ),
        migrations.AddIndex(
            model_name='acciontutela',
            index=models.Index(fields=['abogado_responsable'], name='defenjur_ap_abogado_d7bc6c_idx'),
        ),
        migrations.AddIndex(
            model_name='derechopeticion',
            index=models.Index(fields=['num_reparto'], name='defenjur_ap_num_rep_0ff9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='derechopeticion',
            index=models.Index(fields=['abogado_responsable'], name='defenjur_ap_abogado_6df797_idx'),
        ),
        migrations.AddIndex(
            model_name='pagosentenciajudicial',
            index=models.Index(fields=['num_proceso'], name='defenjur_ap_num_pro_2a0b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='peritaje',
            index=models.Index(fields=['num_proceso'], name='defenjur_ap_num_pro_431946_idx'),
        ),
        migrations.AddIndex(
            model_name='peritaje',
            index=models.Index(fields=['abogado_responsable'], name='defenjur_ap_abogado_daffcb_idx'),
        ),
        migrations.AddIndex(
            model_name='procesoadministrativosancionatorio',
            index=models.Index(fields=['num_proceso'], name='defenjur_ap_num_pro_f62431_idx'),
        ),
        migrations.AddIndex(
            model_name='procesoextrajudicial',
            index=models.Index(fields=['apoderado'], name='defenjur_ap_apodera_56ee47_idx'),
        ),
        migrations.AddIndex(
            model_name='procesojudicialactiva',
            index=models.Index(fields=['num_proceso'], name='defenjur_ap_num_pro_c43a54_idx'),
        ),
        migrations.AddIndex(
            model_name='procesojudicialactiva',
            index=models.Index(fields=['apoderado'], name='defenjur_ap_apodera_70c8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='procesojudicialpasiva',
            index=models.Index(fields=['num_proceso'], name='defenjur_ap_num_pro_6db508_idx'),
        ),
        migrations.AddIndex(
            model_name='procesojudicialpasiva',
            index=models.Index(fields=['apoderado'], name='defenjur_ap_apodera_4ab64e_idx'),
        ),
        migrations.AddIndex(
            model_name='procesojudicialterminado',
            index=models.Index(fields=['num_proceso'], name='defenjur_ap_num_pro_3e7ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='procesojudicialterminado',
            index=models.Index(fields=['apoderado'], name='defenjur_ap_apodera_2667fa_idx'),
        ),
        migrations.AddIndex(
            model_name='requerimientoentecontrol',
            index=models.Index(fields=['num_proceso'], name='defenjur_ap_num_pro_5e90b2_idx'),
        ),
        migrations.AddIndex(
            model_name='requerimientoentecontrol',
            index=models.Index(fields=['num_reparto'], name='defenjur_ap_num_rep_9b268e_idx'),
        ),
        migrations.AddIndex(
            model_name='requerimientoentecontrol',
            index=models.Index(fields=['abogado_responsable'], name='defenjur_ap_abogado_9e1925_idx'),
        ),
        # migrations.AlterModelTable(
        #     name='acciontutela',
        #     table='defenjur_app_acciontutela',
        # ),
        # migrations.AlterModelTable(
        #     name='archivoadjunto',
        #     table='defenjur_app_archivoadjunto',
        # ),
        # migrations.AlterModelTable(
        #     name='derechopeticion',
        #     table='defenjur_app_derechopeticion',
        # ),
        # migrations.AlterModelTable(
        #     name='pagosentenciajudicial',
        #     table='defenjur_app_pagosentenciajudicial',
        # ),
        # migrations.AlterModelTable(
        #     name='peritaje',
        #     table='defenjur_app_peritaje',
        # ),
        # migrations.AlterModelTable(
        #     name='procesoadministrativosancionatorio',
        #     table='defenjur_app_procesoadministrativosancionatorio',
        # ),
        # migrations.AlterModelTable(
        #     name='procesoextrajudicial',
        #     table='defenjur_app_procesoextrajudicial',
        # ),
        # migrations.AlterModelTable(
        #     name='procesojudicialactiva',
        #     table='defenjur_app_procesojudicialactiva',
        # ),
        # migrations.AlterModelTable(
        #     name='procesojudicialpasiva',
        #     table='defenjur_app_procesojudicialpasiva',
        # ),
        # migrations.AlterModelTable(
        #     name='procesojudicialterminado',
        #     table='defenjur_app_procesojudicialterminado',
        # ),
        # migrations.AlterModelTable(
        #     name='requerimientoentecontrol',
        #     table='defenjur_app_requerimientoentecontrol',
        # ),
    ]
