# Generated by Django 5.2.10 on 2026-04-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0014_alter_pagosentenciajudicial_estado_and_more'),
    ]

    operations = [
        # Se comentan las eliminaciones para mantener el esquema físico de la base de datos intacto
        # migrations.RemoveField(model_name='acciontutela', name='area_responsable',),
        # ... (todas las remociones)
        
        migrations.AlterField(
            model_name='acciontutela',
            name='abogado_responsable',
            field=models.CharField(blank=True, db_column='abogado_responsable', max_length=255, null=True, verbose_name='ABOGADO RESPONSABLE'),
        ),
        migrations.AlterField(
            model_name='acciontutela',
            name='accionado',
            field=models.CharField(blank=True, db_column='accionado', max_length=255, null=True, verbose_name='ACCIONADA'),
        ),
        migrations.AlterField(
            model_name='acciontutela',
            name='accionante',
            field=models.CharField(blank=True, db_column='accionante', max_length=255, null=True, verbose_name='ACCIONANTE'),
        ),
        migrations.AlterField(
            model_name='acciontutela',
            name='despacho_judicial',
            field=models.CharField(blank=True, db_column='despacho_judicial', max_length=255, null=True, verbose_name='DESPACHO JUDICIAL'),
        ),
        migrations.AlterField(
            model_name='acciontutela',
            name='fecha_llegada',
            field=models.CharField(blank=True, db_column='fecha_llegada', max_length=255, null=True, verbose_name='FECHA DE LLEGADA'),
        ),
        migrations.AlterField(
            model_name='acciontutela',
            name='num_proceso',
            field=models.CharField(blank=True, db_column='num_proceso', max_length=255, null=True, verbose_name='NÚMERO DE PROCESO'),
        ),
        migrations.AlterField(
            model_name='acciontutela',
            name='num_reparto',
            field=models.CharField(blank=True, db_column='num_reparto', max_length=255, null=True, verbose_name='N° REPARTO'),
        ),
        # migrations.AlterModelTable(name='acciontutela', table='defenjur_app_acciontutela',),
        # ... (otros renames)
    ]
