# Generated by Django 5.2.10 on 2026-04-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0015_remove_acciontutela_area_responsable_and_more'),
    ]

    operations = [
        # Comentado para evitar colisión con esquema físico existente
        # migrations.RemoveField(model_name='acciontutela', name='area_responsable',),
        # ...
        
        migrations.AlterField(
            model_name='acciontutela',
            name='accionado',
            field=models.CharField(blank=True, db_column='accionado', max_length=255, null=True, verbose_name='ACCIONADO'),
        ),
        
        # migrations.AlterModelTable(name='acciontutela', table='defenjur_app_acciontutela',),
        # ...
    ]
