# Generated by Django 5.2.10 on 2026-04-28 14:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('legal', '0018_acciontutela_auditoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acciontutela',
            name='area_responsable',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='asunto_tutela',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='causa',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='desacato',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fallo_desacato',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fallo_primera_instancia',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fallo_segunda_instancia',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_correo',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_fallo_primera_instancia',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_fallo_segunda_instancia',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_impugnacion',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_reparto',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_respuesta_tramite',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_tramite_desacato',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='identificacion_accionante',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='impugnacion',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='objeto_tutela',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='peticionario',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='rad_interno',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='rad_interno_arch_central',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='respuesta_incidente_desacato',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='termino_dar_tramite',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='tipo_identificacion_accionante',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='tipo_tramite',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='tramite_impartido',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='usuario_carga',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='vinculados',
        ),
        migrations.AlterModelTable(
            name='acciontutela',
            table='defenjur_app_acciontutela',
        ),
        migrations.AlterModelTable(
            name='archivoadjunto',
            table='defenjur_app_archivoadjunto',
        ),
        migrations.AlterModelTable(
            name='derechopeticion',
            table='defenjur_app_derechopeticion',
        ),
        migrations.AlterModelTable(
            name='pagosentenciajudicial',
            table='defenjur_app_pagosentenciajudicial',
        ),
        migrations.AlterModelTable(
            name='peritaje',
            table='defenjur_app_peritaje',
        ),
        migrations.AlterModelTable(
            name='procesoadministrativosancionatorio',
            table='defenjur_app_procesoadministrativosancionatorio',
        ),
        migrations.AlterModelTable(
            name='procesoextrajudicial',
            table='defenjur_app_procesoextrajudicial',
        ),
        migrations.AlterModelTable(
            name='procesojudicialactiva',
            table='defenjur_app_procesojudicialactiva',
        ),
        migrations.AlterModelTable(
            name='procesojudicialpasiva',
            table='defenjur_app_procesojudicialpasiva',
        ),
        migrations.AlterModelTable(
            name='procesojudicialterminado',
            table='defenjur_app_procesojudicialterminado',
        ),
        migrations.AlterModelTable(
            name='requerimientoentecontrol',
            table='defenjur_app_requerimientoentecontrol',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nick', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('rol', models.CharField(max_length=120)),
                ('estado', models.IntegerField(default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='legal_usuario_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='legal_usuario_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
