# Generated by Django 5.2.10 on 2026-04-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0018_acciontutela_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciontutela',
            name='derechos_vulnerados',
            field=models.TextField(blank=True, null=True, verbose_name='DERECHOS VULNERADOS'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='estado_tutela',
            field=models.CharField(blank=True, choices=[('NUEVA', 'Nueva / Por Asignar'), ('EN_TERMINO', 'En Término'), ('CONTESTADA', 'Contestada'), ('FALLO_1RA', 'Fallo 1ra Instancia'), ('IMPUGNADA', 'Impugnada'), ('FALLO_2DA', 'Fallo 2da Instancia'), ('EN_CUMPLIMIENTO', 'En Cumplimiento'), ('CERRADA', 'Cerrada / Terminada')], default='NUEVA', max_length=50, null=True, verbose_name='ESTADO DE LA TUTELA'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='fecha_limite_cumplimiento',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA LÍMITE CUMPLIMIENTO'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='fecha_notificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA Y HORA DE NOTIFICACIÓN'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA DE RESPUESTA (RADICACIÓN)'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA DE VENCIMIENTO'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='incidente_desacato',
            field=models.BooleanField(default=False, verbose_name='INCIDENTE DE DESACATO'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='medio_envio_respuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MEDIO DE ENVÍO'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='pretensiones',
            field=models.TextField(blank=True, null=True, verbose_name='PRETENSIONES'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='radicado_respuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RADICADO DE RESPUESTA'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='requiere_cumplimiento',
            field=models.BooleanField(default=False, verbose_name='REQUIERE CUMPLIMIENTO'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='sentido_fallo',
            field=models.CharField(blank=True, choices=[('CONCEDE', 'Concede'), ('NIEGA', 'Niega'), ('IMPROCEDENTE', 'Declara Improcedente'), ('HECHO_SUPERADO', 'Hecho Superado'), ('OTRO', 'Otro')], max_length=50, null=True, verbose_name='SENTIDO DEL FALLO'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='termino_dias',
            field=models.IntegerField(blank=True, null=True, verbose_name='TÉRMINO (DÍAS)'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='termino_horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='TÉRMINO (HORAS)'),
        ),
    ]
