# Generated by Django 5.2.10 on 2026-04-28 15:02

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0019_add_tutela_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='derechopeticion',
            name='estado_peticion',
            field=models.CharField(blank=True, choices=[('NUEVA', 'Nueva / Por Asignar'), ('EN_TRAMITE', 'En Trámite'), ('CONTESTADA', 'Contestada'), ('VENCIDA', 'Vencida'), ('CERRADA', 'Cerrada / Terminada')], default='NUEVA', max_length=50, null=True, verbose_name='ESTADO DE LA PETICIÓN'),
        ),
        migrations.AddField(
            model_name='derechopeticion',
            name='fecha_notificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA Y HORA DE NOTIFICACIÓN'),
        ),
        migrations.AddField(
            model_name='derechopeticion',
            name='fecha_respuesta_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA DE RESPUESTA (RADICACIÓN)'),
        ),
        migrations.AddField(
            model_name='derechopeticion',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA DE VENCIMIENTO'),
        ),
        migrations.AddField(
            model_name='derechopeticion',
            name='medio_envio_respuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MEDIO DE ENVÍO'),
        ),
        migrations.AddField(
            model_name='derechopeticion',
            name='radicado_respuesta_salida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RADICADO DE RESPUESTA'),
        ),
        migrations.AddField(
            model_name='derechopeticion',
            name='termino_dias',
            field=models.IntegerField(blank=True, null=True, verbose_name='TÉRMINO (DÍAS)'),
        ),
        migrations.AddField(
            model_name='derechopeticion',
            name='termino_horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='TÉRMINO (HORAS)'),
        ),
    ]
