# Generated by Django 5.2.10 on 2026-04-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0019_remove_acciontutela_area_responsable_and_more'),
        ('legal', '0020_add_peticion_fields'),
    ]

    operations = [
    ]
