# Generated by Django 5.2.10 on 2026-04-29 15:55

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0020_add_peticion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAccionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de Entidad/Persona')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Accionado',
                'verbose_name_plural': 'Catálogo de Accionados',
                'db_table': 'defenjur_app_catalogoaccionado',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoDerechoVulnerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Derecho')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Derecho Vulnerado',
                'verbose_name_plural': 'Catálogo de Derechos Vulnerados',
                'db_table': 'defenjur_app_catalogoderechovulnerado',
                'ordering': ['nombre'],
            },
        ),
    ]
