# Generated by Django 5.2.10 on 2026-04-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0021_catalogos'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoaccionado',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIT / Código'),
        ),
    ]
