# Generated by Django 5.2.10 on 2026-04-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0022_catalogoaccionado_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciontutela',
            name='desacato_fecha_notificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA Y HORA DE NOTIFICACIÓN'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='desacato_fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA DE RESPUESTA (RADICACIÓN)'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='desacato_fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA DE VENCIMIENTO'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='desacato_medio_envio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MEDIO DE ENVÍO'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='desacato_radicado_respuesta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RADICADO DE RESPUESTA'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='desacato_termino_dias',
            field=models.IntegerField(blank=True, null=True, verbose_name='TÉRMINO (DÍAS)'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='desacato_termino_horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='TÉRMINO (HORAS)'),
        ),
    ]
