# Generated by Django 5.2.10 on 2026-04-29 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0024_remove_acciontutela_area_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acciontutela',
            name='desacato_fecha_notificacion',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='desacato_fecha_respuesta',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='desacato_fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='desacato_medio_envio',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='desacato_radicado_respuesta',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='desacato_termino_dias',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='desacato_termino_horas',
        ),
        migrations.CreateModel(
            name='IncidenteDesacato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True, verbose_name='FECHA Y HORA DE NOTIFICACIÓN')),
                ('termino_dias', models.IntegerField(blank=True, null=True, verbose_name='TÉRMINO (DÍAS)')),
                ('termino_horas', models.IntegerField(blank=True, null=True, verbose_name='TÉRMINO (HORAS)')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True, verbose_name='FECHA DE VENCIMIENTO')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='FECHA DE RESPUESTA (RADICACIÓN)')),
                ('radicado_respuesta', models.CharField(blank=True, max_length=100, null=True, verbose_name='RADICADO DE RESPUESTA')),
                ('medio_envio', models.CharField(blank=True, max_length=100, null=True, verbose_name='MEDIO DE ENVÍO')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='OBSERVACIONES DEL INCIDENTE')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tutela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='legal.acciontutela')),
            ],
            options={
                'verbose_name': 'Incidente de Desacato',
                'verbose_name_plural': 'Incidentes de Desacato',
                'db_table': 'defenjur_app_incidentedesacato',
            },
        ),
    ]
