# Generated by Django 5.2.10 on 2026-04-29 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0025_remove_acciontutela_desacato_fecha_notificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PronunciamientoHecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hecho_referencia', models.CharField(help_text='Ej: FRENTE AL PRIMER HECHO, DEL SEGUNDO AL NOVENO...', max_length=255, verbose_name='REFERENCIA AL HECHO')),
                ('tipo_respuesta', models.CharField(choices=[('ADMITA', 'Admita'), ('NIEGA', 'Niega'), ('NO_CONSTA', 'No le Consta'), ('PARCIAL', 'Parcialmente Cierto')], default='ADMITA', max_length=20, verbose_name='RESPUESTA')),
                ('pronunciamiento', models.TextField(verbose_name='PRONUNCIAMIENTO / EXPLICACIÓN')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tutela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciamientos_hechos', to='legal.acciontutela')),
            ],
            options={
                'verbose_name': 'Pronunciamiento sobre Hecho',
                'verbose_name_plural': 'Pronunciamientos sobre Hechos',
                'db_table': 'defenjur_app_pronunciamientohecho',
            },
        ),
    ]
