# Generated by Django 5.2.10 on 2026-04-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0026_pronunciamientohecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciontutela',
            name='cedula_accionante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CÉDULA ACCIONANTE'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='email_accionante',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='EMAIL ACCIONANTE'),
        ),
    ]
