# Generated by Django 5.2.10 on 2026-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0027_acciontutela_cedula_accionante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciontutela',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Registro'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='usuario_carga',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario Carga'),
        ),
    ]
