# Generated by Django 5.2.10 on 2026-05-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0021_merge_20260430_0847'),
        ('legal', '0028_acciontutela_fecha_registro_and_more'),
    ]

    operations = [
    ]
