# Generated by Django 5.2.10 on 2026-05-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0029_merge_20260504_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciontutela',
            name='vinculados',
            field=models.TextField(blank=True, null=True, verbose_name='VINCULADOS'),
        ),
    ]
