# Generated by Django 5.2.10 on 2026-05-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0029_merge_20260505_1601'),
        ('legal', '0030_acciontutela_fecha_registro_and_more'),
    ]

    operations = [
    ]
