# Generated by Django 5.2.10 on 2026-05-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0031_merge_20260506_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acciontutela',
            name='area_responsable',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='asunto_tutela',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='causa',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='desacato',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fallo_desacato',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fallo_primera_instancia',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fallo_segunda_instancia',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_correo',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_fallo_primera_instancia',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_fallo_segunda_instancia',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_impugnacion',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_reparto',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_respuesta_tramite',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='fecha_tramite_desacato',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='identificacion_accionante',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='impugnacion',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='objeto_tutela',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='peticionario',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='rad_interno',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='rad_interno_arch_central',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='respuesta_incidente_desacato',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='termino_dar_tramite',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='tipo_identificacion_accionante',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='tipo_tramite',
        ),
        migrations.RemoveField(
            model_name='acciontutela',
            name='tramite_impartido',
        ),
    ]
