# Generated by Django 5.2.10 on 2026-05-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0031_merge_20260506'),
        ('legal', '0032_remove_acciontutela_area_responsable_and_more'),
    ]

    operations = [
    ]
