# Generated by Django 5.2.10 on 2026-05-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0033_merge_20260508_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogoaccionado',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='catalogoderechovulnerado',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='despachojudicial',
            options={'ordering': ['ciudad', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='pagosentenciajudicial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='peritaje',
            options={},
        ),
        migrations.AlterModelOptions(
            name='procesoadministrativosancionatorio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='procesojudicialterminado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pronunciamientohecho',
            options={},
        ),
        migrations.AlterModelOptions(
            name='requerimientoentecontrol',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='pagosentenciajudicial',
            name='defenjur_ap_num_pro_2a0b8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='peritaje',
            name='defenjur_ap_num_pro_431946_idx',
        ),
        migrations.RemoveIndex(
            model_name='peritaje',
            name='defenjur_ap_abogado_daffcb_idx',
        ),
        migrations.RemoveIndex(
            model_name='procesoadministrativosancionatorio',
            name='defenjur_ap_num_pro_f62431_idx',
        ),
        migrations.RemoveIndex(
            model_name='procesojudicialterminado',
            name='defenjur_ap_num_pro_3e7ddb_idx',
        ),
        migrations.RemoveIndex(
            model_name='procesojudicialterminado',
            name='defenjur_ap_apodera_2667fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='requerimientoentecontrol',
            name='defenjur_ap_num_pro_5e90b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='requerimientoentecontrol',
            name='defenjur_ap_num_rep_9b268e_idx',
        ),
        migrations.RemoveIndex(
            model_name='requerimientoentecontrol',
            name='defenjur_ap_abogado_9e1925_idx',
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='peticion_modelo',
            field=models.CharField(blank=True, help_text='Slug del modelo de petición aplicado (ej: inexistencia_falta).', max_length=100, null=True, verbose_name='MODELO DE PETICIÓN'),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='peticion_texto_aplicado',
            field=models.TextField(blank=True, help_text='Captura histórica del texto legal en el momento de la respuesta.', null=True, verbose_name='CONTENIDO DE PETICIÓN APLICADO'),
        ),
        migrations.AlterField(
            model_name='pronunciamientohecho',
            name='hecho_referencia',
            field=models.CharField(max_length=255, verbose_name='REFERENCIA AL HECHO'),
        ),
    ]
