# Generated by Django 5.2.10 on 2026-05-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0034_alter_catalogoaccionado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciontutela',
            name='medio_envio_respuesta',
            field=models.CharField(blank=True, choices=[('CORREO_CERTIFICADO', 'Correo Certificado'), ('CORREO_ELECTRONICO', 'Correo Electrónico'), ('ENTREGA_PERSONAL', 'Entrega Personal / Notificación Física'), ('PORTAL_WEB', 'Portal Web Judicial'), ('OTROS', 'Otros')], max_length=255, null=True, verbose_name='MEDIO DE ENVÍO'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='medio_envio_respuesta',
            field=models.CharField(blank=True, choices=[('CORREO_CERTIFICADO', 'Correo Certificado'), ('CORREO_ELECTRONICO', 'Correo Electrónico'), ('ENTREGA_PERSONAL', 'Entrega Personal / Notificación Física'), ('PORTAL_WEB', 'Portal Web Judicial'), ('OTROS', 'Otros')], max_length=255, null=True, verbose_name='MEDIO DE ENVÍO'),
        ),
        migrations.AlterField(
            model_name='incidentedesacato',
            name='medio_envio',
            field=models.CharField(blank=True, choices=[('CORREO_CERTIFICADO', 'Correo Certificado'), ('CORREO_ELECTRONICO', 'Correo Electrónico'), ('ENTREGA_PERSONAL', 'Entrega Personal / Notificación Física'), ('PORTAL_WEB', 'Portal Web Judicial'), ('OTROS', 'Otros')], max_length=100, null=True, verbose_name='MEDIO DE ENVÍO'),
        ),
    ]
