# Generated by Django 5.2.10 on 2026-02-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas_externas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdp_numero', models.CharField(max_length=50, unique=True, verbose_name='Número CDP')),
                ('fecha', models.DateField(verbose_name='Fecha CDP')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor')),
                ('objeto', models.TextField(verbose_name='Objeto')),
                ('rubro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro')),
                ('nombre_rubro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Rubro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tercero', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultas_externas.gentercer', verbose_name='Tercero')),
            ],
            options={
                'verbose_name': 'CDP (Certificado Disponibilidad Presupuestal)',
                'verbose_name_plural': 'CDPs',
            },
        ),
        migrations.CreateModel(
            name='RP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_numero', models.CharField(max_length=50, unique=True, verbose_name='Número RP')),
                ('fecha', models.DateField(verbose_name='Fecha RP')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor')),
                ('objeto', models.TextField(verbose_name='Objeto')),
                ('otros_datos', models.TextField(blank=True, null=True, verbose_name='Otros Datos de Importancia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cdp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rps', to='presupuesto.cdp', verbose_name='CDP Asociado')),
                ('tercero', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultas_externas.gentercer', verbose_name='Tercero')),
            ],
            options={
                'verbose_name': 'RP (Registro Presupuestal)',
                'verbose_name_plural': 'RPs',
            },
        ),
    ]
