# Generated by Django 5.2.10 on 2026-04-13 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obstetriciaunificador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adningreso',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('AINCONSEC', models.IntegerField(db_column='AINCONSEC')),
                ('AINFECING', models.DateTimeField(blank=True, db_column='AINFECING', null=True)),
                ('AINESTADO', models.IntegerField(blank=True, db_column='AINESTADO', null=True)),
            ],
            options={
                'verbose_name': 'Ingreso (Adningreso)',
                'db_table': 'ADNINGRESO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gendetcon',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('GDECODIGO', models.CharField(db_column='GDECODIGO', max_length=50)),
                ('GDENOMBRE', models.CharField(db_column='GDENOMBRE', max_length=200)),
            ],
            options={
                'db_table': 'GENDETCON',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gendiagno',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('DIACODIGO', models.CharField(db_column='DIACODIGO', max_length=20)),
                ('DIANOMBRE', models.CharField(db_column='DIANOMBRE', max_length=500)),
            ],
            options={
                'verbose_name': 'Diagnóstico (Gendiagno)',
                'db_table': 'GENDIAGNO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genpacien',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('PACNUMDOC', models.CharField(db_column='PACNUMDOC', max_length=20)),
                ('PACTIPDOC', models.IntegerField(db_column='PACTIPDOC')),
                ('PACPRINOM', models.CharField(db_column='PACPRINOM', max_length=100)),
                ('PACSEGNOM', models.CharField(db_column='PACSEGNOM', max_length=100, null=True)),
                ('PACPRIAPE', models.CharField(db_column='PACPRIAPE', max_length=100)),
                ('PACSEGAPE', models.CharField(db_column='PACSEGAPE', max_length=100, null=True)),
                ('GPAFECNAC', models.DateTimeField(db_column='GPAFECNAC')),
                ('GPASEXPAC', models.IntegerField(db_column='GPASEXPAC')),
            ],
            options={
                'verbose_name': 'Paciente Externo (Genpacien)',
                'db_table': 'Genpacien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hcmwingin',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'HCMWINGIN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hcndiapac',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('HCPDIAPRIN', models.IntegerField(blank=True, db_column='HCPDIAPRIN', null=True)),
            ],
            options={
                'db_table': 'HCNDIAPAC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hcnfolio',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('HCNUMFOL', models.IntegerField(db_column='HCNUMFOL')),
                ('HCFECFOL', models.DateTimeField(blank=True, db_column='HCFECFOL', null=True)),
            ],
            options={
                'verbose_name': 'Folio Clínico',
                'db_table': 'HCNFOLIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hpndefcam',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('HCACODIGO', models.CharField(db_column='HCACODIGO', max_length=50)),
                ('HCANOMBRE', models.CharField(db_column='HCANOMBRE', max_length=200)),
            ],
            options={
                'verbose_name': 'Cama (Hpndefcam)',
                'db_table': 'HPNDEFCAM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hpnestanc',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('HESFECING', models.DateTimeField(blank=True, db_column='HESFECING', null=True)),
                ('HESFECSAL', models.DateTimeField(blank=True, db_column='HESFECSAL', null=True)),
            ],
            options={
                'db_table': 'HPNESTANC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hpngrupos',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('HGRCODIGO', models.CharField(db_column='HGRCODIGO', max_length=50)),
                ('HGRNOMBRE', models.CharField(db_column='HGRNOMBRE', max_length=200)),
            ],
            options={
                'db_table': 'HPNGRUPOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hpnsubgru',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('HSUCODIGO', models.CharField(db_column='HSUCODIGO', max_length=50)),
                ('HSUNOMBRE', models.CharField(db_column='HSUNOMBRE', max_length=200)),
            ],
            options={
                'db_table': 'HPNSUBGRU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FirmaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.CharField(max_length=50)),
                ('formulario_id', models.CharField(blank=True, max_length=50, null=True)),
                ('template_huella', models.TextField()),
                ('imagen_huella', models.ImageField(blank=True, null=True, upload_to='huellas_biometria/')),
                ('imagen_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('usuario', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('aseguradora', models.CharField(blank=True, help_text='Nombre de la aseguradora', max_length=200)),
                ('cama', models.CharField(blank=True, help_text='Número o código de cama', max_length=50)),
                ('num_historia_clinica', models.CharField(blank=True, default='', help_text='Número de historia clínica', max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del paciente', null=True)),
                ('fecha_ingreso', models.DateField(blank=True, help_text='Fecha de ingreso al hospital', null=True)),
                ('responsable', models.CharField(blank=True, help_text='Nombre del responsable del paciente', max_length=200)),
                ('diagnostico', models.TextField(blank=True, default='', help_text='Diagnóstico clínico inicial')),
                ('tipo_sangre', models.CharField(blank=True, help_text='Tipo de sangre (O+, A-, etc.)', max_length=5)),
                ('nombre_acompanante', models.CharField(blank=True, help_text='Nombre del acompañante', max_length=200)),
                ('edad_gestacional', models.PositiveSmallIntegerField(blank=True, help_text='Edad gestacional en semanas', null=True)),
                ('gestas', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Número de gestas', null=True)),
                ('n_controles_prenatales', models.PositiveSmallIntegerField(blank=True, help_text='Número de controles prenatales', null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=20)),
                ('orden', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ParametroMEOWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=20)),
                ('orden', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Parámetro MEOWS',
                'verbose_name_plural': 'Parámetros MEOWS',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', help_text='Versión del formulario (ej: 1.0, 2.0)', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['nombre'],
                'unique_together': {('codigo', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('meows_total', models.PositiveIntegerField(blank=True, null=True)),
                ('meows_riesgo', models.CharField(blank=True, choices=[('BLANCO', 'Blanco'), ('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('ROJO', 'Rojo')], max_length=10, null=True)),
                ('meows_mensaje', models.TextField(blank=True, null=True)),
                ('atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones_meows', to='obstetriciaunificador.atencionparto')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='meows.formulario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='meows.paciente')),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='MedicionValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=20)),
                ('puntaje', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('medicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='meows.medicion')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meows.parametro')),
            ],
            options={
                'verbose_name': 'Valor de Medición',
                'verbose_name_plural': 'Valores de Medición',
                'ordering': ['parametro__orden'],
                'unique_together': {('medicion', 'parametro')},
            },
        ),
        migrations.CreateModel(
            name='RangoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_min', models.DecimalField(decimal_places=2, help_text='Valor mínimo del rango (inclusive)', max_digits=10)),
                ('valor_max', models.DecimalField(decimal_places=2, help_text='Valor máximo del rango (inclusive)', max_digits=10)),
                ('score', models.PositiveSmallIntegerField(help_text='Puntaje asignado a este rango (0-3)')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de evaluación (menor a mayor)')),
                ('activo', models.BooleanField(default=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='meows.parametro')),
            ],
            options={
                'verbose_name': 'Rango de Parámetro',
                'verbose_name_plural': 'Rangos de Parámetros',
                'ordering': ['parametro', 'orden', 'valor_min'],
                'indexes': [models.Index(fields=['parametro', 'activo', 'orden'], name='meows_rango_paramet_193d98_idx')],
            },
        ),
    ]
