# Generated by Django 5.2.10 on 2026-01-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Tipo de sangre y RH', max_length=5, null=True),
        ),
    ]
