# Generated by Django 5.2.10 on 2026-04-22 23:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('A_00_Organigrama', '0001_initial'),
        ('BasesGenerales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadTercerizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Actividad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'terc_actividad_tercerizado',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaTercerizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('representante_legal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Representante Legal')),
                ('tipo_servicio', models.CharField(help_text='Ej: Aseo, Vigilancia, Alimentación, Mantenimiento', max_length=200, verbose_name='Tipo de Servicio')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('direccion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Empresa Tercerizada',
                'verbose_name_plural': 'Empresas Tercerizadas',
                'db_table': 'terc_empresa_tercerizada',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ContratoTercerizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='N° Contrato')),
                ('objeto_contrato', models.TextField(verbose_name='Objeto del Contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('valor_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor ($)')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('LIQUIDADO', 'Liquidado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('documento_contrato', models.FileField(blank=True, null=True, upload_to='tercerizadas/contratos/', verbose_name='PDF del Contrato')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='tercerizadas.empresatercerizada', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contrato Tercerizado',
                'verbose_name_plural': 'Contratos Tercerizados',
                'db_table': 'terc_contrato_tercerizado',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ServidorTercerizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')], verbose_name='Número de Documento')),
                ('en_dinamica', models.BooleanField(default=False, verbose_name='Registrado en Dinámica')),
                ('fecha_verificacion_dinamica', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('primer_nombre', models.CharField(max_length=100, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion_residencia', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección de Residencia')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='tercerizadas/fotos/', verbose_name='Foto')),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='tercerizadas/documentos/', verbose_name='Documento de Identidad (PDF)')),
                ('activo_hospital', models.BooleanField(default=True, verbose_name='Activo en el Hospital')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_retiro', models.DateField(blank=True, null=True, verbose_name='Fecha de Retiro')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidores', to='tercerizadas.contratotercerizado', verbose_name='Contrato')),
                ('departamento_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidores_nacidos_dep', to='BasesGenerales.geo02departamento', verbose_name='Departamento de Nacimiento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servidores', to='tercerizadas.empresatercerizada', verbose_name='Empresa')),
                ('grupo_sanguineo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasesGenerales.listatipogruposanguineo', verbose_name='Grupo Sanguíneo')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidores_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('municipio_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidores_nacidos_mun', to='BasesGenerales.geo03municipio', verbose_name='Municipio de Nacimiento')),
                ('municipio_residencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidores_residencia', to='BasesGenerales.geo03municipio', verbose_name='Municipio de Residencia')),
                ('pais_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidores_nacidos_pais', to='BasesGenerales.geo01pais', verbose_name='País de Nacimiento')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servidores_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('sexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasesGenerales.listatiposexo', verbose_name='Sexo')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BasesGenerales.listatipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Servidor Tercerizado',
                'verbose_name_plural': 'Servidores Tercerizados',
                'db_table': 'terc_servidor_tercerizado',
                'ordering': ['primer_apellido', 'primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionOrganigrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Desde')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Hasta')),
                ('activa', models.BooleanField(default=True, verbose_name='Asignación Activa')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tercerizadas.actividadtercerizado', verbose_name='Actividad que realiza')),
                ('organigrama_nivel1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='A_00_Organigrama.organigrama01', verbose_name='Nivel 1 (Dirección)')),
                ('organigrama_nivel2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='A_00_Organigrama.organigrama02', verbose_name='Nivel 2 (División)')),
                ('organigrama_nivel3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='A_00_Organigrama.organigrama03', verbose_name='Nivel 3 (Servicio)')),
                ('organigrama_nivel4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='A_00_Organigrama.organigrama04', verbose_name='Nivel 4 (Área)')),
                ('organigrama_nivel5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='A_00_Organigrama.organigrama05', verbose_name='Nivel 5 (Subárea)')),
                ('organigrama_nivel6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='A_00_Organigrama.organigrama06', verbose_name='Nivel 6 (Unidad)')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_verificadas', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='tercerizadas.servidortercerizado', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Asignación de Área',
                'verbose_name_plural': 'Asignaciones de Área',
                'db_table': 'terc_asignacion_organigrama',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AfiliacionSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ARL', 'ARL — Administradora de Riesgos Laborales'), ('EPS', 'EPS — Entidad Promotora de Salud'), ('IPS', 'IPS — Institución Prestadora de Servicios'), ('AFP', 'AFP — Fondo de Pensiones')], max_length=10, verbose_name='Tipo')),
                ('nombre_entidad', models.CharField(max_length=200, verbose_name='Entidad')),
                ('numero_afiliacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de Afiliación')),
                ('fecha_afiliacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Afiliación')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='tercerizadas/afiliaciones/', verbose_name='Soporte (PDF)')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afiliaciones', to='tercerizadas.servidortercerizado', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Afiliación de Seguridad Social',
                'verbose_name_plural': 'Afiliaciones de Seguridad Social',
                'db_table': 'terc_afiliacion_seguridad',
                'ordering': ['tipo', 'nombre_entidad'],
            },
        ),
    ]
