# Generated by Django 5.2.10 on 2026-05-13 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercerizadas', '0002_administradortercerizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresatercerizada',
            name='cedula_persona_cargo',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')], verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='empresatercerizada',
            name='email_persona_cargo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de la persona a cargo'),
        ),
        migrations.AddField(
            model_name='empresatercerizada',
            name='firma_responsable',
            field=models.TextField(blank=True, help_text='Base64 de la firma del responsable', null=True, verbose_name='Firma del responsable'),
        ),
        migrations.AddField(
            model_name='empresatercerizada',
            name='persona_cargo_hospital',
            field=models.CharField(blank=True, help_text='Nombre del funcionario HUDN responsable de esta empresa', max_length=200, null=True, verbose_name='Persona a cargo (Hospital)'),
        ),
    ]
