# Generated by Django 5.0 on 2026-01-17 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas_externas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CirugiaPropuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Cirugía')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cirugía Propuesta',
                'verbose_name_plural': 'Cirugías Propuestas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAnestesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('sala', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sala/Quirófano')),
                ('diagnostico_pre', models.TextField(verbose_name='Diagnóstico Preoperatorio')),
                ('cirugia_propuesta_texto', models.TextField(blank=True, null=True, verbose_name='Cirugía Propuesta (Texto Libre)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anestesiologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Anestesiólogo')),
                ('cirugia_propuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_anestesia.cirugiapropuesta', verbose_name='Cirugía Propuesta')),
                ('paciente', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='consultas_externas.gentercer', verbose_name='Paciente (GENTERCER)')),
            ],
            options={
                'verbose_name': 'Registro de Anestesia',
                'verbose_name_plural': 'Registros de Anestesia',
            },
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='registro_anestesia.registroanestesia')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekg', models.BooleanField(default=False, verbose_name='EKG')),
                ('pni', models.BooleanField(default=False, verbose_name='PNI')),
                ('pulx', models.BooleanField(default=False, verbose_name='Pulx')),
                ('capno', models.BooleanField(default=False, verbose_name='Capno')),
                ('temp', models.BooleanField(default=False, verbose_name='Temp')),
                ('est_n_perif', models.BooleanField(default=False, verbose_name='Est. N. Periférico')),
                ('otro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro Monitor')),
                ('linea_arterial', models.BooleanField(default=False, verbose_name='PAI (Línea Arterial)')),
                ('cvc', models.BooleanField(default=False, verbose_name='PVC (CVC)')),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreo', to='registro_anestesia.registroanestesia')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=50)),
                ('hora', models.TimeField()),
                ('via', models.CharField(blank=True, max_length=50, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='registro_anestesia.registroanestesia')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvc', models.CharField(blank=True, max_length=20, null=True, verbose_name='PVC')),
                ('liquidos_administrados', models.TextField(blank=True, null=True)),
                ('sangre_derivados', models.TextField(blank=True, null=True)),
                ('diuresis', models.CharField(blank=True, max_length=50, null=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidos', to='registro_anestesia.registroanestesia')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionPreAnestesica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(blank=True, max_length=100, null=True)),
                ('patologia_principal', models.CharField(blank=True, max_length=200, null=True)),
                ('antecedentes_patologicos', models.TextField(blank=True, null=True)),
                ('antecedentes_quirurgicos', models.TextField(blank=True, null=True)),
                ('antecedentes_farmacologicos', models.TextField(blank=True, null=True)),
                ('antecedentes_alergicos', models.TextField(blank=True, null=True)),
                ('antecedentes_toxicos', models.TextField(blank=True, null=True)),
                ('hb', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hbna')),
                ('hto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hcto')),
                ('plaquetas', models.CharField(blank=True, max_length=20, null=True)),
                ('tp', models.CharField(blank=True, max_length=20, null=True)),
                ('tpt', models.CharField(blank=True, max_length=20, null=True)),
                ('rayos_x_comentario', models.TextField(blank=True, null=True, verbose_name='Rx Comentarios')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fc', models.CharField(blank=True, max_length=10, null=True, verbose_name='FC')),
                ('fr', models.CharField(blank=True, max_length=10, null=True, verbose_name='FR')),
                ('pa', models.CharField(blank=True, max_length=20, null=True, verbose_name='PA')),
                ('sao2', models.CharField(blank=True, max_length=10, null=True, verbose_name='SaO2')),
                ('mallampati', models.CharField(blank=True, max_length=10, null=True)),
                ('apertura_bucal', models.CharField(blank=True, max_length=20, null=True)),
                ('dentadura', models.CharField(blank=True, max_length=50, null=True)),
                ('cuello', models.CharField(blank=True, max_length=100, null=True)),
                ('asa', models.CharField(blank=True, max_length=10, null=True, verbose_name='ASA')),
                ('plan_anestesia', models.TextField(blank=True, null=True)),
                ('apto_cirugia', models.BooleanField(default=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_preanestesica', to='registro_anestesia.registroanestesia')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_post', models.TextField(verbose_name='Diagnóstico Postoperatorio')),
                ('cirugia_realizada', models.TextField(verbose_name='Cirugía Realizada')),
                ('destino', models.CharField(blank=True, max_length=50, null=True)),
                ('aldrete', models.CharField(blank=True, max_length=10, null=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salida', to='registro_anestesia.registroanestesia')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('pa_sistolica', models.IntegerField(blank=True, null=True)),
                ('pa_diastolica', models.IntegerField(blank=True, null=True)),
                ('fc', models.IntegerField(blank=True, null=True)),
                ('sao2', models.IntegerField(blank=True, null=True)),
                ('etco2', models.IntegerField(blank=True, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='registro_anestesia.registroanestesia')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.BooleanField(default=False)),
                ('regional', models.BooleanField(default=False)),
                ('sedacion', models.BooleanField(default=False)),
                ('local', models.BooleanField(default=False)),
                ('combinada', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tecnica', to='registro_anestesia.registroanestesia')),
            ],
        ),
        migrations.CreateModel(
            name='Ventilacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espontanea', models.BooleanField(default=False)),
                ('asistida', models.BooleanField(default=False)),
                ('controlada', models.BooleanField(default=False)),
                ('vt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Volumen Tidal')),
                ('fr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Frecuencia Resp')),
                ('peep', models.CharField(blank=True, max_length=20, null=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ventilacion', to='registro_anestesia.registroanestesia')),
            ],
        ),
    ]
