# Generated by Django 5.2.10 on 2026-01-19 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas_externas', '0001_initial'),
        ('registro_anestesia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroanestesia',
            name='paciente',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='consultas_externas.genpacien', verbose_name='Paciente (GENPACIEN)'),
        ),
    ]
