# Generated by Django 5.2.10 on 2026-04-13 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ops4garantias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_garantias', models.BooleanField(default=False, verbose_name='Requiere Garantías')),
            ],
            options={
                'verbose_name': 'Garantías Ops',
                'verbose_name_plural': 'Garantías Ops',
            },
        ),
        migrations.CreateModel(
            name='opsComponenteTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroComponente', models.CharField(max_length=100, unique=True, verbose_name='Número Componente')),
                ('Area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Área')),
                ('Subgerencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subgerencia')),
                ('Dependencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dependencia')),
                ('objetoContractual', models.TextField(blank=True, null=True, verbose_name='Objeto Contractual')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Necesidad')),
                ('claseServicio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clase de Servicio')),
                ('VALORTOTALCONTRATO', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Total Contrato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudio_opscomponente_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Componente Técnico Ops',
                'verbose_name_plural': 'Componentes Técnicos Ops',
            },
        ),
        migrations.CreateModel(
            name='ops4viabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subgerencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subgerencia que da Viabilidad')),
                ('NumeroComponente', models.OneToOneField(db_column='NumeroComponente', on_delete=django.db.models.deletion.CASCADE, related_name='estado_viabilidad', to='EstudioDeConveniencia.opscomponentetecnico', to_field='numeroComponente')),
            ],
            options={
                'verbose_name': 'Viabilidad Ops',
                'verbose_name_plural': 'Viabilidades Ops',
            },
        ),
        migrations.CreateModel(
            name='ops4garantiasDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garantia', models.CharField(max_length=255, verbose_name='Garantía a exigir')),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='EstudioDeConveniencia.ops4garantias')),
                ('NumeroComponente', models.ForeignKey(db_column='NumeroComponente', on_delete=django.db.models.deletion.CASCADE, related_name='garantias_detalle', to='EstudioDeConveniencia.opscomponentetecnico', to_field='numeroComponente')),
            ],
            options={
                'verbose_name': 'Detalle Garantía Ops',
                'verbose_name_plural': 'Detalles Garantía Ops',
            },
        ),
        migrations.AddField(
            model_name='ops4garantias',
            name='NumeroComponente',
            field=models.OneToOneField(db_column='NumeroComponente', on_delete=django.db.models.deletion.CASCADE, related_name='garantia', to='EstudioDeConveniencia.opscomponentetecnico', to_field='numeroComponente'),
        ),
        migrations.CreateModel(
            name='ops4Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumerodeCdp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de CDP')),
                ('NumeroComponente', models.OneToOneField(db_column='NumeroComponente', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='EstudioDeConveniencia.opscomponentetecnico', to_field='numeroComponente')),
            ],
            options={
                'verbose_name': 'Disponibilidad Ops',
                'verbose_name_plural': 'Disponibilidades Ops',
            },
        ),
        migrations.CreateModel(
            name='ops4dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Área Solicitante')),
                ('Subgerencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subgerencia')),
                ('Dependencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dependencia')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Solicitud')),
                ('NumeroComponente', models.OneToOneField(db_column='NumeroComponente', on_delete=django.db.models.deletion.CASCADE, related_name='estado_dependencia', to='EstudioDeConveniencia.opscomponentetecnico', to_field='numeroComponente')),
            ],
            options={
                'verbose_name': 'Dependencia Ops',
                'verbose_name_plural': 'Dependencias Ops',
            },
        ),
        migrations.CreateModel(
            name='ops4aceptaGerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptagerencia', models.BooleanField(default=False, verbose_name='Aprueba Gerencia')),
                ('NumeroComponente', models.OneToOneField(db_column='NumeroComponente', on_delete=django.db.models.deletion.CASCADE, related_name='aceptacion_gerencia', to='EstudioDeConveniencia.opscomponentetecnico', to_field='numeroComponente')),
            ],
            options={
                'verbose_name': 'Aceptación Gerencia Ops',
                'verbose_name_plural': 'Aceptaciones Gerencia Ops',
            },
        ),
        migrations.CreateModel(
            name='ops3_2AspectosIdoneidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idoneidad', models.TextField(verbose_name='Idoneidad (Educación y Formación)')),
                ('NumeroComponente', models.ForeignKey(db_column='NumeroComponente', on_delete=django.db.models.deletion.CASCADE, related_name='aspectos_idoneidad', to='EstudioDeConveniencia.opscomponentetecnico', to_field='numeroComponente')),
            ],
            options={
                'verbose_name': 'Aspecto Idoneidad Ops',
                'verbose_name_plural': 'Aspectos Idoneidad Ops',
            },
        ),
        migrations.CreateModel(
            name='ops3_2AspectosExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.TextField(verbose_name='Experiencia requerida')),
                ('NumeroComponente', models.ForeignKey(db_column='NumeroComponente', on_delete=django.db.models.deletion.CASCADE, related_name='aspectos_experiencia', to='EstudioDeConveniencia.opscomponentetecnico', to_field='numeroComponente')),
            ],
            options={
                'verbose_name': 'Aspecto Experiencia Ops',
                'verbose_name_plural': 'Aspectos Experiencia Ops',
            },
        ),
        migrations.CreateModel(
            name='ops3_1AspectosLegales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspectolegal', models.TextField(verbose_name='Aspecto Legal')),
                ('NumeroComponente', models.ForeignKey(db_column='NumeroComponente', on_delete=django.db.models.deletion.CASCADE, related_name='aspectos_legales', to='EstudioDeConveniencia.opscomponentetecnico', to_field='numeroComponente')),
            ],
            options={
                'verbose_name': 'Aspecto Legal Ops',
                'verbose_name_plural': 'Aspectos Legales Ops',
            },
        ),
        migrations.CreateModel(
            name='ops33_ValorTotaldelContratoyformadepago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formadepago', models.TextField(verbose_name='Forma de pago')),
                ('NumeroComponente', models.ForeignKey(db_column='NumeroComponente', on_delete=django.db.models.deletion.CASCADE, related_name='valor_formas_pago', to='EstudioDeConveniencia.opscomponentetecnico', to_field='numeroComponente')),
            ],
            options={
                'verbose_name': 'Valor Y Forma Pago Ops',
                'verbose_name_plural': 'Valor Y Forma Pago Ops',
            },
        ),
        migrations.CreateModel(
            name='opsCondiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAA_UNSPS', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código PAA/UNSPSC y Nombre')),
                ('FECHADEINICIO', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('FECHADETERMINACION', models.DateField(blank=True, null=True, verbose_name='Fecha de Terminación')),
                ('LUGARDEEJECUCION', models.CharField(blank=True, max_length=500, null=True, verbose_name='Lugar de Ejecución')),
                ('NumeroComponente', models.ForeignKey(db_column='NumeroComponente', on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='EstudioDeConveniencia.opscomponentetecnico', to_field='numeroComponente')),
            ],
            options={
                'verbose_name': 'Condiciones Ops',
                'verbose_name_plural': 'Condiciones Ops',
            },
        ),
        migrations.CreateModel(
            name='opsObligacionesEspecificas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Obligacion', models.TextField(verbose_name='Obligación Específica')),
                ('NumeroComponente', models.ForeignKey(db_column='NumeroComponente', on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones_especificas', to='EstudioDeConveniencia.opscomponentetecnico', to_field='numeroComponente')),
            ],
            options={
                'verbose_name': 'Obligación Específica Ops',
                'verbose_name_plural': 'Obligaciones Específicas Ops',
            },
        ),
        migrations.CreateModel(
            name='opsObligacionesGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Obligacion', models.TextField(verbose_name='Obligación General')),
                ('NumeroComponente', models.ForeignKey(db_column='NumeroComponente', on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones_generales', to='EstudioDeConveniencia.opscomponentetecnico', to_field='numeroComponente')),
            ],
            options={
                'verbose_name': 'Obligación General Ops',
                'verbose_name_plural': 'Obligaciones Generales Ops',
            },
        ),
    ]
