# Generated by Django 5.2.13 on 2026-04-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_acciontutela_campos_peticion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='derechopeticion',
            options={'verbose_name': 'Derecho de petición', 'verbose_name_plural': 'Derechos de Petición'},
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='abogado_responsable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Abogado responsable'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='area_remitir_informacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Área remitir información'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='causa_peticion',
            field=models.TextField(blank=True, null=True, verbose_name='Causa'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='cedula_persona_solicitante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cédula solicitante'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='correo_remitente_peticion',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo remitente petición'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='fecha_correo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha correo'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='fecha_remitente_peticion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha remitente petición'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='fecha_reparto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha reparto'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='fecha_respuesta_peticion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha respuesta petición'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='modalidad_peticion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modalidad petición'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='nombre_persona_solicitante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='num_rad_arch_central',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° rad. archivo central'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='num_rad_interno',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° radicado interno'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='num_reparto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° reparto'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='peticionario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Peticionario'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='peticionario_int_ext',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Peticionario int./ext.'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='termino_dar_tramite',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Término dar trámite'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='tiempo_area_remitir_informacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiempo área remitir información'),
        ),
        migrations.AlterField(
            model_name='derechopeticion',
            name='tramite_impartido',
            field=models.TextField(blank=True, null=True, verbose_name='Trámite impartido'),
        ),
    ]
