# Generated by Django 5.2.13 on 2026-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0010_proceso_pasiva_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procesojudicialterminado',
            options={'verbose_name': 'Proceso judicial terminado', 'verbose_name_plural': 'Procesos Judiciales Terminados'},
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='accion_repeticion',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Acción repetición'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='apoderado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apoderado'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='calidad_entidad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Calidad entidad'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='cc_demandante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='C.C. demandante'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='demandado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Demandado'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='demandante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Demandante'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='despacho_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Despacho'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='enfoque_defensa',
            field=models.TextField(blank=True, null=True, verbose_name='Enfoque defensa'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='estado_actual',
            field=models.TextField(blank=True, null=True, verbose_name='Estado actual'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='fallo_sentencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fallo / sentencia'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='hecho_generador',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hecho generador'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='hechos_relevantes',
            field=models.TextField(blank=True, null=True, verbose_name='Hechos relevantes'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='informe_pago',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Informe pago'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='medio_control',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Medio de control'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='num_proceso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° proceso'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='porcentaje_probabilidad_perdida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='% probabilidad pérdida'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='pretensiones',
            field=models.TextField(blank=True, null=True, verbose_name='Pretensiones'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='riesgo_perdida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Riesgo pérdida'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='ultima_actuacion',
            field=models.TextField(blank=True, null=True, verbose_name='Última actuación'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='valor_fallo_sentencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor fallo sentencia'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='valor_pretension_inicial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor pretensión inicial'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='valor_proceso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor proceso'),
        ),
        migrations.AlterField(
            model_name='procesojudicialterminado',
            name='valor_provisionar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor a provisionar'),
        ),
    ]
