# Generated by Django 5.2.11 on 2026-04-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0011_proceso_terminado_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requerimientoentecontrol',
            options={'verbose_name': 'Requerimiento de ente de control', 'verbose_name_plural': 'Requerimientos de Entes de Control'},
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='abogado_responsable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='asunto',
            field=models.TextField(blank=True, null=True, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='entidad_remitente_requerimiento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='fecha_correo_electronico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha correo'),
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro'),
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='fecha_reparto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha reparto'),
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='fecha_respuesta_tramite',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha respuesta trámite'),
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='num_proceso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° proceso'),
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='num_reparto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° reparto'),
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='termino_dar_tramite',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Término dar trámite'),
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='tipo_tramite',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo trámite'),
        ),
        migrations.AlterField(
            model_name='requerimientoentecontrol',
            name='tramite_impartido',
            field=models.TextField(blank=True, null=True, verbose_name='Trámite impartido'),
        ),
    ]
