"""
Django settings for HospitalManagement project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Apps obstétricas (meows, trabajoparto) viven bajo UNIFICADOR-V1 en este monorepo.
_SISTEMA_OBST = BASE_DIR / 'UNIFICADOR-V1' / 'sistema_obstetrico'
if _SISTEMA_OBST.is_dir():
    _obst_path = str(_SISTEMA_OBST)
    if _obst_path not in sys.path:
        sys.path.insert(0, _obst_path)

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-vm8ux)05e9u$fc=qz5^$)ma+q!ehq)&#y2g9e74#e=+&w(lm1i')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,GestorInstitucionalHUDN,.ngrok.io,.ngrok-free.app,.trycloudflare.com').split(',')


# Para ngrok y túneles seguros
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'https://*.trycloudflare.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
    'defenjur_py.legal',

    'A_00_Organigrama',
    'usuarios',
    'BasesGenerales',
    'consultas_externas',
    'registro_anestesia',
    'unificador_v1',
    'consultas',
    'presupuesto',
    'ConsentimientosInformados',
    'CentralDeMezclas',
    'django.contrib.humanize',
    'consentimientos',
    'sslserver',
    'EstudioDeConveniencia',
    'trasplantes_donacion',
    'CertificadosDIAN',
    'horas_extras',
    'frecuenciafetal',
    'certificados_laborales',
    'visor_soportes',
    'tercerizadas',
    # Cuando integre el código completo de UNIFICADOR-V1 en la raíz del repo, descomente:
    # 'meows',
    # 'trabajoparto',
]

MIDDLEWARE = [
    'core.middleware.SecurityProtectionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'usuarios.middleware.UserPermissionsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.DatabaseCheckMiddleware',
]

ROOT_URLCONF = 'HospitalManagement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'defenjur_py' / 'templates',
            BASE_DIR / 'tercerizadas' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.modules_processor',
                'usuarios.context_processors.user_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'HospitalManagement.wsgi.application'

# BASE PARA EL TRABAJO
 

# CONFIGURACION DE ENTORNO

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': os.getenv('DB_DEFAULT_NAME', 'GestorInstitucional'),
        'USER': os.getenv('DB_DEFAULT_USER', 'apantoja'),
        'PASSWORD': os.getenv('DB_DEFAULT_PASSWORD', 'ConsultasPantojaHUDN_2026$'), 
        'HOST': os.getenv('DB_DEFAULT_HOST', '172.20.100.209'),
        'PORT': os.getenv('DB_DEFAULT_PORT', ''),
        'CONN_MAX_AGE': 600,
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'timeout': 30,
        },
    },
    'readonly': {
        'ENGINE': 'mssql',
        'NAME': os.getenv('DB_READONLY_NAME', 'DGEMPRES03'),
        'USER': os.getenv('DB_READONLY_USER', 'dsolarte'),
        'PASSWORD': os.getenv('DB_READONLY_PASSWORD', 'ConsultaHUDN2026*/$'),
        'HOST': os.getenv('DB_READONLY_HOST', '172.20.100.209'),
        'PORT': os.getenv('DB_READONLY_PORT', ''),
        'CONN_MAX_AGE': 0,
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'host_is_server': True,
            'timeout': 10,
            'connection_timeout': 1,
        },
    }
}




#DATABASES = {
#    'default': {
#        'ENGINE': 'mssql',
#        'NAME': 'HospitalManagement',
#        'HOST': 'DESKTOP-H7G9SSV\\SQLEXPRESS',
#        'OPTIONS': {
#            'driver': 'ODBC Driver 18 for SQL Server',
#            'extra_params': 'TrustServerCertificate=yes;Trusted_Connection=yes',
#        },
#    }
#}


# Database Routers
DATABASE_ROUTERS = [
    'HospitalManagement.routers.HospitalRouter',
    # 'trabajoparto.db_router.ClinicoRouter',
]

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'defenjur_py' / 'static',
    BASE_DIR / 'UNIFICADOR-V1' / 'sistema_obstetrico' / 'static',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sesiones en archivo — rápidas, persisten entre reinicios del servidor
SESSION_ENGINE = 'django.contrib.sessions.backends.file'
SESSION_FILE_PATH = os.path.join(BASE_DIR, 'sessions')
os.makedirs(SESSION_FILE_PATH, exist_ok=True)
SESSION_COOKIE_AGE = 28800  # 8 horas
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'gestor-cache',
    }
}

# Authentication configurations
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'
CSRF_FAILURE_VIEW = 'core.views.csrf_failure'

# Increase max fields for permission matrix
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# DIAN Certificates Configuration
# 1. Origen de datos (Plantilla y Excel)
DIAN_EXCEL_PATH = os.path.join(BASE_DIR, 'CertificadoIngresos2025.xlsm')
DIAN_TEMPLATE_PATH = os.path.join(BASE_DIR, 'media', 'certificados_dian', 'Formulario_220_2026.pdf')

# 2. Destino de los PDF generados
DIAN_OUTPUT_DIR = os.path.join(BASE_DIR.parent, 'Dian2025')
if not os.path.exists(DIAN_OUTPUT_DIR):
    try:
        os.makedirs(DIAN_OUTPUT_DIR, exist_ok=True)
    except:
        pass

# Create local directory if it doesn't exist
if not os.path.exists(DIAN_OUTPUT_DIR):
    try:
        os.makedirs(DIAN_OUTPUT_DIR, exist_ok=True)
    except:
        pass

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)


# Defenjur FTP / NAS Configuration
DEFENJUR_FTP_ENABLED = True
DEFENJUR_FTP_HOST = os.getenv('FTP_HOST', '172.20.100.25')
DEFENJUR_FTP_USER = os.getenv('FTP_USER', '')
DEFENJUR_FTP_PASSWORD = os.getenv('FTP_PASSWORD', '')
DEFENJUR_FTP_BASE_PATH = '/web/defenjur_files/'

# SECURITY HARDENING SETTINGS
if not DEBUG:
    # Security headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HTTPS Enforcement (Only if SSL is configured)
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
    
    # HSTS
    SECURE_HSTS_SECONDS = 31536000 # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Secure Cookies — solo si hay HTTPS real (proxy/ngrok/cloudflare)
    _https = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
    SESSION_COOKIE_SECURE = _https
    CSRF_COOKIE_SECURE = _https
    
    # Referrer Policy
    SECURE_REFERRER_POLICY = 'same-origin'

# Content Security Policy (Optional but recommended)
# We can use django-csp if installed, otherwise we can set headers manually in middleware.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'horas_extras': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',  # Cambiar a DEBUG para ver cada query SQL
            'propagate': False,
        },
    },
}

