"""
Django settings for HospitalManagement project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vm8ux)05e9u$fc=qz5^$)ma+q!ehq)&#y2g9e74#e=+&w(lm1i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.ngrok.io',
    '.ngrok-free.app',
    '.trycloudflare.com',
    '*',  # Para pruebas - permite cualquier host
]

# Para ngrok y túneles seguros
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'https://*.trycloudflare.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
    'defenjur_app',

    'A_00_Organigrama',
    'usuarios',
    # Apps migradas desde AdmonAlexaTotal
    'BasesGenerales',
    'consultas_externas',
    'registro_anestesia',
    'meows',  # Sistema de Alerta Temprana Obstétrico
    'trabajoparto',
    'consultas',
    'presupuesto',
    'ConsentimientosInformados',
    'CentralDeMezclas',
    'django.contrib.humanize',
    'consentimientos',
    'sslserver',
    'EstudioDeConveniencia',
    'trasplantes_donacion',
    'CertificadosDIAN',
    'horas_extras',
    'frecuenciafetal',
    'obstetriciaunificador',
    'certificados_laborales',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.DatabaseCheckMiddleware',
]

ROOT_URLCONF = 'HospitalManagement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.modules_processor',
                'usuarios.context_processors.user_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'HospitalManagement.wsgi.application'

# BASE PARA EL TRABAJO
 

# CONFIGURACION DE ENTORNO

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'GestorInstitucional',
        'USER': 'apantoja',
        'PASSWORD': 'ConsultasPantojaHUDN_2026$', 
        'HOST': '172.20.100.209',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'host_is_server': True,
            'timeout': 60, # Mayor timeout para migraciones iniciales
        },
    },
    'readonly': {
        'ENGINE': 'mssql',
        'NAME': 'DGEMPRES01',
        'USER': 'DSOLARTE',
        'PASSWORD': 'ConsultaHUDN2026*/$', 
        'HOST': '172.20.100.209',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'host_is_server': True,
            'timeout': 10,
        },
    }
}



#DATABASES = {
#    'default': {
#        'ENGINE': 'mssql',
#        'NAME': 'HospitalManagement',
#        'HOST': 'DESKTOP-H7G9SSV\\SQLEXPRESS',
#        'OPTIONS': {
#            'driver': 'ODBC Driver 18 for SQL Server',
#            'extra_params': 'TrustServerCertificate=yes;Trusted_Connection=yes',
#        },
#    }
#}


# Database Routers
DATABASE_ROUTERS = ['HospitalManagement.routers.HospitalRouter', 'trabajoparto.db_router.ClinicoRouter']

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication configurations
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Increase max fields for permission matrix
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# DIAN Certificates Configuration
# 1. Origen de datos (Plantilla y Excel en la ubicación "Original")
DIAN_SOURCE_ROOT = r'C:\Users\SISTEMAS\Documents\HospitalManagement\media\certificados_dian'
DIAN_EXCEL_PATH = os.path.join(DIAN_SOURCE_ROOT, 'CertificadoIngresos2025.xlsm')
DIAN_TEMPLATE_PATH = os.path.join(DIAN_SOURCE_ROOT, 'Formulario_220_2026.pdf')

# 2. Destino de los PDF generados (Carpeta que pediste)
DIAN_OUTPUT_DIR = r'C:\Users\SISTEMAS\Documents\Dian2025'
if not os.path.exists(DIAN_OUTPUT_DIR):
    try:
        os.makedirs(DIAN_OUTPUT_DIR, exist_ok=True)
    except:
        pass

# Create local directory if it doesn't exist
if not os.path.exists(DIAN_OUTPUT_DIR):
    try:
        os.makedirs(DIAN_OUTPUT_DIR, exist_ok=True)
    except:
        pass

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
