# Generated by Django 5.2.11 on 2026-04-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_pago_imputacion_fecha_registro_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosentenciajudicial',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
