# Generated by Django 5.2.13 on 2026-04-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_pago_estado_255'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciontutela',
            name='causa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='fecha_correo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='peticionario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acciontutela',
            name='solicitante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
