# Generated by Django 5.2.13 on 2026-04-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0006_pagosentencia_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peritaje',
            options={'verbose_name': 'Peritaje', 'verbose_name_plural': 'Peritajes'},
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='abogado_responsable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Abogado responsable'),
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='asunto',
            field=models.TextField(blank=True, null=True, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='demandado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Demandado'),
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='demandante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Demandante'),
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='entidad_remitente_requerimiento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entidad requirente'),
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='fecha_asignar_perito',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha asignar perito'),
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='fecha_correo_electronico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha correo'),
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro'),
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='fecha_reparto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha reparto'),
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='num_proceso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° proceso'),
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='num_reparto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° reparto'),
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='pago_honorarios',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Pago honorarios'),
        ),
        migrations.AlterField(
            model_name='peritaje',
            name='perito_asignado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Perito asignado'),
        ),
    ]
