# Generated by Django 5.2.13 on 2026-04-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0008_sancionatorio_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procesojudicialactiva',
            options={'verbose_name': 'Proceso judicial activo', 'verbose_name_plural': 'Procesos Judiciales Activos'},
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='apoderado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apoderado'),
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='demandado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Demandado'),
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='demandante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Demandante'),
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='despacho_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Despacho'),
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='estado_actual',
            field=models.TextField(blank=True, null=True, verbose_name='Estado actual'),
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='estimacion_cuantia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estimación cuantía'),
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro'),
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='medio_control',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Medio de control'),
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='num_proceso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° proceso'),
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='pretension',
            field=models.TextField(blank=True, null=True, verbose_name='Pretensión'),
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='sentencia_primera_instancia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sentencia primera instancia'),
        ),
        migrations.AlterField(
            model_name='procesojudicialactiva',
            name='ultima_actuacion',
            field=models.TextField(blank=True, null=True, verbose_name='Última actuación'),
        ),
    ]
