# Generated by Django 5.2.10 on 2026-02-18 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Formato')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('contenido_html', models.TextField(verbose_name='Contenido HTML/Markdown del Formato')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Consentimiento',
                'verbose_name_plural': 'Plantillas de Consentimiento',
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_oid', models.IntegerField(verbose_name='OID del Paciente')),
                ('profesional_oid', models.IntegerField(verbose_name='OID del Profesional')),
                ('firma_paciente', models.TextField(blank=True, null=True, verbose_name='Firma del Paciente (Base64)')),
                ('firma_profesional', models.TextField(blank=True, null=True, verbose_name='Firma del Profesional (Base64)')),
                ('huella_paciente', models.BinaryField(blank=True, max_length='max', null=True, verbose_name='Huella del Paciente')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Enviado por Email')),
                ('email_destino', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Destino')),
                ('fecha_firma', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Firma')),
                ('pdf_resultado', models.FileField(blank=True, null=True, upload_to='consentimientos/pdfs/', verbose_name='PDF Firmado')),
                ('datos_extra', models.TextField(blank=True, default='{}', verbose_name='Datos capturados en el formulario')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConsentimientosInformados.consentimientotemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Registro de Consentimiento',
                'verbose_name_plural': 'Registros de Consentimiento',
            },
        ),
    ]
