# Generated by Django 5.0 on 2026-03-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsentimientosInformados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimientoregistro',
            name='foto_paciente',
            field=models.TextField(blank=True, null=True, verbose_name='Fotografía del Paciente (Base64)'),
        ),
    ]
