# Generated by Django 5.0 on 2026-03-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsentimientosInformados', '0002_consentimientoregistro_foto_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentimientoregistro',
            name='huella_paciente',
            field=models.BinaryField(blank=True, null=True, verbose_name='Huella del Paciente'),
        ),
    ]
