# Generated by Django 5.2.10 on 2026-04-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsentimientosInformados', '0003_alter_consentimientoregistro_huella_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentimientoregistro',
            name='huella_paciente',
            field=models.TextField(blank=True, null=True, verbose_name='Huella del Paciente (Base64)'),
        ),
    ]
