# Generated by Django 5.2.10 on 2026-04-13 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoConsentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField(help_text='Contenido del documento en HTML o texto plano')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('codigo_formato', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_elaboracion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_actualizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirmaBiometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_id', models.IntegerField(blank=True, help_text='ID de Admisión en el sistema hospitalario', null=True)),
                ('paciente_oid', models.IntegerField(blank=True, null=True)),
                ('folio', models.IntegerField(blank=True, help_text='Número de Folio / Historia Clínica', null=True)),
                ('historia_clinica', models.CharField(blank=True, max_length=50, null=True)),
                ('firma_data', models.TextField(help_text='Base64 de la firma del Paciente')),
                ('firma_medico_data', models.TextField(blank=True, help_text='Base64 de la firma del Médico o Responsable', null=True)),
                ('firma_testigo_data', models.TextField(blank=True, help_text='Base64 de la firma del Testigo (en caso de rechazo)', null=True)),
                ('datos_formulario', models.TextField(default='{}', help_text='Valores de los placeholders diligenciados en JSON')),
                ('metadata_seguridad', models.TextField(default='{}', help_text='Timestamp, IP, User Agent, etc.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consentimientos.documentoconsentimiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FirmaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_data', models.TextField(help_text='Base64 de la firma oficial registrada')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_oficial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(help_text='Base64 encoded credential ID', max_length=250, unique=True)),
                ('public_key', models.TextField(help_text='Base64 encoded public key')),
                ('sign_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
