# Generated by Django 5.0 on 2026-03-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmabiometrica',
            name='datos_formulario',
            field=models.TextField(default='{}', help_text='Valores de los placeholders diligenciados en JSON'),
        ),
        migrations.AlterField(
            model_name='firmabiometrica',
            name='firma_data',
            field=models.TextField(help_text='Base64 de la imagen de la firma o JSON de WebAuthn'),
        ),
    ]
