# Generated by Django 5.0 on 2026-03-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentimientos', '0002_firmabiometrica_datos_formulario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmabiometrica',
            name='firma_medico_data',
            field=models.TextField(blank=True, help_text='Base64 de la firma del Médico o Responsable', null=True),
        ),
        migrations.AlterField(
            model_name='firmabiometrica',
            name='firma_data',
            field=models.TextField(help_text='Base64 de la firma del Paciente'),
        ),
    ]
