# Generated by Django 5.0 on 2026-03-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentimientos', '0003_firmabiometrica_firma_medico_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoconsentimiento',
            name='codigo_formato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentoconsentimiento',
            name='fecha_actualizacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentoconsentimiento',
            name='fecha_elaboracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
