# Generated by Django 5.0 on 2026-03-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentimientos', '0004_documentoconsentimiento_codigo_formato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmabiometrica',
            name='firma_testigo_data',
            field=models.TextField(blank=True, help_text='Base64 de la firma del Testigo (en caso de rechazo)', null=True),
        ),
    ]
