# Generated by Django 5.0 on 2026-03-28 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentimientos', '0005_firmabiometrica_firma_testigo_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmabiometrica',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='firmabiometrica',
            name='folio',
            field=models.IntegerField(blank=True, help_text='Número de Folio / Historia Clínica', null=True),
        ),
        migrations.AddField(
            model_name='firmabiometrica',
            name='historia_clinica',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='firmabiometrica',
            name='ingreso_id',
            field=models.IntegerField(blank=True, help_text='ID de Admisión en el sistema hospitalario', null=True),
        ),
        migrations.AddField(
            model_name='firmabiometrica',
            name='paciente_oid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FirmaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_data', models.TextField(help_text='Base64 de la firma oficial registrada')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_oficial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
