# Generated by Django 5.2.10 on 2026-04-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteNeurocritico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('fecha_identificacion', models.DateTimeField(blank=True, null=True)),
                ('busqueda_activa', models.CharField(blank=True, max_length=50, null=True)),
                ('busqueda_pasiva', models.CharField(blank=True, max_length=50, null=True)),
                ('servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('paciente_intubado', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=200, null=True)),
                ('etnia', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('eapb', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('glasgow_ingreso', models.IntegerField(blank=True, null=True)),
                ('codigo_cie10', models.CharField(blank=True, max_length=20, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('paciente_alertado', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_hora_alerta_crt', models.DateTimeField(blank=True, null=True)),
                ('causa_no_alerta', models.TextField(blank=True, null=True)),
                ('voluntades_anticipadas', models.CharField(blank=True, max_length=100, null=True)),
                ('dx_muerte_encefalica', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_diagnostico_me_hora', models.DateTimeField(blank=True, null=True)),
                ('paciente_legalizado', models.CharField(blank=True, max_length=10, null=True)),
                ('causa_no_legalizacion', models.TextField(blank=True, null=True)),
                ('fecha_legalizacion', models.DateTimeField(blank=True, null=True)),
                ('donante_efectivo', models.CharField(blank=True, max_length=10, null=True)),
                ('causa_no_donante_efectivo', models.TextField(blank=True, null=True)),
                ('estado_vital_egreso', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_egreso', models.DateTimeField(blank=True, null=True)),
                ('organos_recatados', models.TextField(blank=True, null=True)),
                ('medico_alerta', models.CharField(blank=True, max_length=150, null=True)),
                ('medico_no_alerta', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paciente Neurocrítico',
                'verbose_name_plural': 'Pacientes Neurocríticos',
            },
        ),
    ]
