# Generated by Django 5.2.10 on 2026-04-13 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ADMIN', 'Administrador'), ('EDITOR', 'Editor'), ('LECTOR', 'Lector'), ('IMPRESOR', 'Impresor')], default='LECTOR', max_length=20)),
                ('color_primario', models.CharField(default='#2563eb', max_length=7)),
                ('color_secundario', models.CharField(default='#1e40af', max_length=7)),
                ('color_fondo', models.CharField(default='#f8fafc', max_length=7)),
                ('estilo_fondo', models.CharField(default='solid', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermisoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('permitido', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_app', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'app_label')},
            },
        ),
        migrations.CreateModel(
            name='PermisoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('permitido', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_modelo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'app_label', 'model_name')},
            },
        ),
    ]
