# Generated by Django 5.2.10 on 2026-04-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='legal_nick',
            field=models.CharField(blank=True, help_text='Nombre de usuario legacy para DEFENJUR', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='legal_rol',
            field=models.CharField(default='INVITADO', help_text='Rol dentro del módulo DEFENJUR', max_length=120),
        ),
    ]
