# Generated by Django 5.2.10 on 2026-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_cedula_perfilusuario_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='email_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='email_personal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
