# Generated by Django 5.2.10 on 2026-04-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilusuario_email_institucional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rh',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
