# Generated by Django 5.2.10 on 2026-04-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfilusuario_grupo_sanguineo_perfilusuario_rh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='reset_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
