# Generated by Django 5.2.10 on 2026-04-13 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCertificadoDIAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_gravable', models.IntegerField(default=2025)),
                ('cedula', models.CharField(db_index=True, max_length=20)),
                ('primer_apellido', models.CharField(blank=True, max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100)),
                ('primer_nombre', models.CharField(blank=True, max_length=100)),
                ('otros_nombres', models.CharField(blank=True, max_length=100)),
                ('caja_36', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('caja_42', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('caja_46', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('caja_47', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('caja_49', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('caja_52', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('caja_53', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('caja_54', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('caja_56', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('caja_57', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('caja_59', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('caja_60', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Datos de Certificado DIAN',
                'verbose_name_plural': 'Datos de Certificados DIAN',
                'unique_together': {('anio_gravable', 'cedula')},
            },
        ),
        migrations.CreateModel(
            name='RegistroDescargaCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_consultada', models.CharField(max_length=20)),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('ip_descarga', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Descarga',
                'verbose_name_plural': 'Registros de Descargas',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCertificadoWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_consultada', models.CharField(max_length=20)),
                ('nombre_empleado', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
