# Generated by Django 5.2.10 on 2026-05-12 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificadosDIAN', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCertificadoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_consultada', models.CharField(max_length=20)),
                ('nombre_empleado', models.CharField(blank=True, max_length=255, null=True)),
                ('email_envio', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Certificado (Email)',
                'verbose_name_plural': 'Solicitudes de Certificados (Email)',
            },
        ),
        migrations.DeleteModel(
            name='SolicitudCertificadoWhatsapp',
        ),
    ]
