# Generated by Django 5.2.10 on 2026-05-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificadosDIAN', '0002_solicitudcertificadoemail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrodescargacertificado',
            options={'ordering': ['-fecha_descarga'], 'verbose_name': 'Registro de Descarga', 'verbose_name_plural': 'Registros de Descargas'},
        ),
        migrations.AddField(
            model_name='registrodescargacertificado',
            name='anio_gravable',
            field=models.IntegerField(default=2025, verbose_name='Año gravable'),
        ),
        migrations.AddField(
            model_name='registrodescargacertificado',
            name='nombre_empleado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del empleado'),
        ),
        migrations.AddField(
            model_name='registrodescargacertificado',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='Navegador / Dispositivo'),
        ),
    ]
