# Generated by Django 5.2.10 on 2026-04-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificadosDIAN', '0003_datoscertificadodian'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcertificadowhatsapp',
            name='nombre_empleado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
