# Generated by Django 5.2.10 on 2026-05-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificadosDIAN', '0003_alter_registrodescargacertificado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodescargacertificado',
            name='enviado_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Enviado por WhatsApp'),
        ),
        migrations.AddField(
            model_name='registrodescargacertificado',
            name='fecha_whatsapp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha envío WhatsApp'),
        ),
        migrations.AddField(
            model_name='registrodescargacertificado',
            name='telefono_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono WhatsApp'),
        ),
    ]
