"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a+&1&v#(qais_sgq7f9aao846xqqt5d=2u7cqfuul$gzfss@dx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'legal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'FENJUR_BD_ORG',
        'HOST': r'localhost\SQLEXPRESS',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params': 'Trusted_Connection=yes;TrustServerCertificate=yes;',
        },
    },
    # Consultas de solo lectura (Nexus / DGEMPRES). Uso: Model.objects.using('readonly')
    'readonly': {
        'ENGINE': 'mssql',
        'NAME': os.environ.get('READONLY_DB_NAME', 'DGEMPRES_NEXUS'),
        'USER': os.environ.get('READONLY_DB_USER', 'apantoja'),
        'PASSWORD': os.environ.get('READONLY_DB_PASSWORD', ''),
        'HOST': os.environ.get('READONLY_DB_HOST', '172.20.100.209'),
        'PORT': os.environ.get('READONLY_DB_PORT', ''),
        'OPTIONS': {
            'driver': os.environ.get('READONLY_ODBC_DRIVER', 'ODBC Driver 17 for SQL Server'),
            'extra_params': 'TrustServerCertificate=yes',
        },
        'CONN_MAX_AGE': 0,
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Sesión: alineado con buenas prácticas y mensaje de "sesión expirada" del manual de usuario
SESSION_COOKIE_AGE = 60 * 60 * 2  # 2 horas de inactividad (cookie)
SESSION_SAVE_EVERY_REQUEST = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'legal.Usuario'

# ─── FTP / NAS (opcional; espejo de adjuntos como defenjur-back ftpService.js) ───
DEFENJUR_FTP_ENABLED = os.environ.get('DEFENJUR_FTP_ENABLED', 'False').lower() in ('1', 'true', 'yes')
DEFENJUR_FTP_HOST = os.environ.get('DEFENJUR_FTP_HOST', '')
DEFENJUR_FTP_USER = os.environ.get('DEFENJUR_FTP_USER', '')
DEFENJUR_FTP_PASSWORD = os.environ.get('DEFENJUR_FTP_PASSWORD', '')
DEFENJUR_FTP_BASE_PATH = os.environ.get('DEFENJUR_FTP_BASE_PATH', '/web/defenjur_files').rstrip('/')

# Correo mostrado en la plantilla de mantenimiento (réplica del front PHP).
DEFENJUR_SUPPORT_EMAIL = os.environ.get('DEFENJUR_SUPPORT_EMAIL', 'soporte@defenjur.example')
