# Generated by Django 5.2.10 on 2026-04-09 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas_externas', '0002_alter_adnauprde_options_alter_adnausede_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentos',
            name='oid',
        ),
        migrations.AddField(
            model_name='hcnconmed',
            name='hcnmedpac',
            field=models.ForeignKey(blank=True, db_column='HCNMEDPAC', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hcnconmed_details', to='consultas_externas.hcnmedpac'),
        ),
        migrations.AddField(
            model_name='hcndiapac',
            name='hcnfolio',
            field=models.ForeignKey(blank=True, db_column='HCNFOLIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultas_externas.hcnfolio'),
        ),
        migrations.AddField(
            model_name='hcnfolio',
            name='hcnfolio',
            field=models.ForeignKey(blank=True, db_column='HCNFOLIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='consultas_externas.hcnfolio'),
        ),
        migrations.AddField(
            model_name='hcnfolordsrv',
            name='hcnfolio',
            field=models.ForeignKey(blank=True, db_column='HCNFOLIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultas_externas.hcnfolio'),
        ),
        migrations.AddField(
            model_name='hcninterc',
            name='hcnfolio',
            field=models.ForeignKey(blank=True, db_column='HCNFOLIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultas_externas.hcnfolio'),
        ),
        migrations.AddField(
            model_name='hcnmedpac',
            name='hcnfolio',
            field=models.ForeignKey(blank=True, db_column='HCNFOLIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultas_externas.hcnfolio'),
        ),
        migrations.AddField(
            model_name='hcnsolexa',
            name='hcnfolio',
            field=models.ForeignKey(blank=True, db_column='HCNFOLIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultas_externas.hcnfolio'),
        ),
        migrations.AddField(
            model_name='hcnsolpnqx',
            name='hcnfolio',
            field=models.ForeignKey(blank=True, db_column='HCNFOLIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultas_externas.hcnfolio'),
        ),
        migrations.AddField(
            model_name='innmsumpa',
            name='hcnmedpac',
            field=models.ForeignKey(blank=True, db_column='HCNMEDPAC', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultas_externas.hcnmedpac'),
        ),
        migrations.AlterField(
            model_name='adningreso',
            name='gendetcon',
            field=models.ForeignKey(blank=True, db_column='GENDETCON', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultas_externas.gendetcon'),
        ),
        migrations.AlterField(
            model_name='adningreso',
            name='genpacien',
            field=models.ForeignKey(blank=True, db_column='GENPACIEN', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultas_externas.genpacien'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='iprcodigo',
            field=models.CharField(db_column='IPRCODIGO', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slnfactur',
            name='adningreso',
            field=models.ForeignKey(blank=True, db_column='ADNINGRESO', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='consultas_externas.adningreso'),
        ),
        migrations.AlterField(
            model_name='slnfactur',
            name='gendetcon',
            field=models.ForeignKey(blank=True, db_column='GENDETCON', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='consultas_externas.gendetcon'),
        ),
    ]
