# Generated by Django 5.2.10 on 2026-04-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas_externas', '0003_remove_medicamentos_oid_hcnconmed_hcnmedpac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adningreso',
            name='ainfirmadig',
            field=models.BinaryField(blank=True, db_column='AINFIRMADIG', null=True),
        ),
        migrations.AlterField(
            model_name='ccncontrato',
            name='ctoctoresu',
            field=models.BinaryField(blank=True, db_column='CTOCTORESU', null=True),
        ),
        migrations.AlterField(
            model_name='ccnplaact',
            name='pacplanti',
            field=models.BinaryField(blank=True, db_column='PACPLANTI', null=True),
        ),
        migrations.AlterField(
            model_name='ccnplacont',
            name='pctplanti',
            field=models.BinaryField(blank=True, db_column='PCTPLANTI', null=True),
        ),
        migrations.AlterField(
            model_name='ccnplares',
            name='prsplanti',
            field=models.BinaryField(blank=True, db_column='PRSPLANTI', null=True),
        ),
        migrations.AlterField(
            model_name='comaccedir',
            name='accicono',
            field=models.BinaryField(blank=True, db_column='ACCICONO', null=True),
        ),
        migrations.AlterField(
            model_name='comtercero',
            name='terimagen',
            field=models.BinaryField(blank=True, db_column='TERIMAGEN', null=True),
        ),
        migrations.AlterField(
            model_name='crnparsis',
            name='banner1y2',
            field=models.BinaryField(blank=True, db_column='BANNER1Y2', null=True),
        ),
        migrations.AlterField(
            model_name='crnparsis',
            name='banner3',
            field=models.BinaryField(blank=True, db_column='BANNER3', null=True),
        ),
        migrations.AlterField(
            model_name='crnparsis',
            name='banner4',
            field=models.BinaryField(blank=True, db_column='BANNER4', null=True),
        ),
        migrations.AlterField(
            model_name='crnparsis',
            name='banner5',
            field=models.BinaryField(blank=True, db_column='BANNER5', null=True),
        ),
        migrations.AlterField(
            model_name='crnparsis',
            name='banner6',
            field=models.BinaryField(blank=True, db_column='BANNER6', null=True),
        ),
        migrations.AlterField(
            model_name='genarcadju',
            name='adarchivo',
            field=models.BinaryField(blank=True, db_column='ADARCHIVO', null=True),
        ),
        migrations.AlterField(
            model_name='gendiagno',
            name='diaplanotif',
            field=models.BinaryField(blank=True, db_column='DIAPLANOTIF', null=True),
        ),
        migrations.AlterField(
            model_name='genempres',
            name='empimagen',
            field=models.BinaryField(blank=True, db_column='EMPIMAGEN', null=True),
        ),
        migrations.AlterField(
            model_name='genmedico',
            name='gmefirma',
            field=models.BinaryField(blank=True, db_column='GMEFIRMA', null=True),
        ),
        migrations.AlterField(
            model_name='genmedico',
            name='gmefotoima',
            field=models.BinaryField(blank=True, db_column='GMEFOTOIMA', null=True),
        ),
        migrations.AlterField(
            model_name='genpacien',
            name='pacarchue',
            field=models.BinaryField(blank=True, db_column='PACARCHUE', null=True),
        ),
        migrations.AlterField(
            model_name='genpacien',
            name='pacfotoima',
            field=models.BinaryField(blank=True, db_column='PACFOTOIMA', null=True),
        ),
        migrations.AlterField(
            model_name='genpacien',
            name='usuhuella',
            field=models.BinaryField(blank=True, db_column='USUHUELLA', null=True),
        ),
        migrations.AlterField(
            model_name='genperrep',
            name='gepreport',
            field=models.BinaryField(blank=True, db_column='GEPREPORT', null=True),
        ),
        migrations.AlterField(
            model_name='genperrep',
            name='gepreportxml',
            field=models.BinaryField(blank=True, db_column='GEPREPORTXML', null=True),
        ),
        migrations.AlterField(
            model_name='genusuario',
            name='usuarchue',
            field=models.BinaryField(blank=True, db_column='USUARCHUE', null=True),
        ),
        migrations.AlterField(
            model_name='genusuario',
            name='usuhuedig',
            field=models.BinaryField(blank=True, db_column='USUHUEDIG', null=True),
        ),
        migrations.AlterField(
            model_name='genwidenla',
            name='empimagen',
            field=models.BinaryField(blank=True, db_column='EMPIMAGEN', null=True),
        ),
        migrations.AlterField(
            model_name='gereporte',
            name='gepreport',
            field=models.BinaryField(blank=True, db_column='GEPREPORT', null=True),
        ),
        migrations.AlterField(
            model_name='gereporte',
            name='geresquema',
            field=models.BinaryField(blank=True, db_column='GERESQUEMA', null=True),
        ),
        migrations.AlterField(
            model_name='gereporte',
            name='gerreportxml',
            field=models.BinaryField(blank=True, db_column='GERREPORTXML', null=True),
        ),
        migrations.AlterField(
            model_name='ggngrafind',
            name='gglytgraf',
            field=models.BinaryField(blank=True, db_column='GGLYTGRAF', null=True),
        ),
        migrations.AlterField(
            model_name='ggntabctrl',
            name='ggtlytpar',
            field=models.BinaryField(blank=True, db_column='GGTLYTPAR', null=True),
        ),
        migrations.AlterField(
            model_name='ggntabctrl',
            name='ggtlytpiv',
            field=models.BinaryField(blank=True, db_column='GGTLYTPIV', null=True),
        ),
        migrations.AlterField(
            model_name='ggntabctrl',
            name='ggtlytrep',
            field=models.BinaryField(blank=True, db_column='GGTLYTREP', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n01',
            field=models.BinaryField(blank=True, db_column='HCCM13N01', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n02',
            field=models.BinaryField(blank=True, db_column='HCCM13N02', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n03',
            field=models.BinaryField(blank=True, db_column='HCCM13N03', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n04',
            field=models.BinaryField(blank=True, db_column='HCCM13N04', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n05',
            field=models.BinaryField(blank=True, db_column='HCCM13N05', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n06',
            field=models.BinaryField(blank=True, db_column='HCCM13N06', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n07',
            field=models.BinaryField(blank=True, db_column='HCCM13N07', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n08',
            field=models.BinaryField(blank=True, db_column='HCCM13N08', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n09',
            field=models.BinaryField(blank=True, db_column='HCCM13N09', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n10',
            field=models.BinaryField(blank=True, db_column='HCCM13N10', null=True),
        ),
        migrations.AlterField(
            model_name='hcmdesope',
            name='hccm12n26',
            field=models.BinaryField(blank=True, db_column='HCCM12N26', null=True),
        ),
        migrations.AlterField(
            model_name='hcmevoreu',
            name='hccm12n47',
            field=models.BinaryField(blank=True, db_column='HCCM12N47', null=True),
        ),
        migrations.AlterField(
            model_name='hcmevoreu',
            name='hccm12n61',
            field=models.BinaryField(blank=True, db_column='HCCM12N61', null=True),
        ),
        migrations.AlterField(
            model_name='hcmevoreu',
            name='hccm12n62',
            field=models.BinaryField(blank=True, db_column='HCCM12N62', null=True),
        ),
        migrations.AlterField(
            model_name='hcmfis001',
            name='hccm12n33',
            field=models.BinaryField(blank=True, db_column='HCCM12N33', null=True),
        ),
        migrations.AlterField(
            model_name='hcminfpat',
            name='hccm12n113',
            field=models.BinaryField(blank=True, db_column='HCCM12N113', null=True),
        ),
        migrations.AlterField(
            model_name='hcminfpat',
            name='hccm12n12',
            field=models.BinaryField(blank=True, db_column='HCCM12N12', null=True),
        ),
        migrations.AlterField(
            model_name='hcminfpat',
            name='hccm12n125',
            field=models.BinaryField(blank=True, db_column='HCCM12N125', null=True),
        ),
        migrations.AlterField(
            model_name='hcminfpat',
            name='hccm12n126',
            field=models.BinaryField(blank=True, db_column='HCCM12N126', null=True),
        ),
        migrations.AlterField(
            model_name='hcminfpat',
            name='hccm12n13',
            field=models.BinaryField(blank=True, db_column='HCCM12N13', null=True),
        ),
        migrations.AlterField(
            model_name='hcmnutr01',
            name='hccm12n02',
            field=models.BinaryField(blank=True, db_column='HCCM12N02', null=True),
        ),
        migrations.AlterField(
            model_name='hcmradiot',
            name='hccm12n11',
            field=models.BinaryField(blank=True, db_column='HCCM12N11', null=True),
        ),
        migrations.AlterField(
            model_name='hcmradiot',
            name='hccm12n12',
            field=models.BinaryField(blank=True, db_column='HCCM12N12', null=True),
        ),
        migrations.AlterField(
            model_name='hcmradiot',
            name='hccm12n348',
            field=models.BinaryField(blank=True, db_column='HCCM12N348', null=True),
        ),
        migrations.AlterField(
            model_name='hcmradiot',
            name='hccm13n298',
            field=models.BinaryField(blank=True, db_column='HCCM13N298', null=True),
        ),
        migrations.AlterField(
            model_name='hcmtami02',
            name='hccm12n30',
            field=models.BinaryField(blank=True, db_column='HCCM12N30', null=True),
        ),
        migrations.AlterField(
            model_name='hcmtami02',
            name='hccm12n31',
            field=models.BinaryField(blank=True, db_column='HCCM12N31', null=True),
        ),
        migrations.AlterField(
            model_name='hcmtami02',
            name='hccm12n32',
            field=models.BinaryField(blank=True, db_column='HCCM12N32', null=True),
        ),
        migrations.AlterField(
            model_name='hcmtami02',
            name='hccm12n33',
            field=models.BinaryField(blank=True, db_column='HCCM12N33', null=True),
        ),
        migrations.AlterField(
            model_name='hcmterf01',
            name='hccm12n33',
            field=models.BinaryField(blank=True, db_column='HCCM12N33', null=True),
        ),
        migrations.AlterField(
            model_name='hcmterf01',
            name='hccm12n39',
            field=models.BinaryField(blank=True, db_column='HCCM12N39', null=True),
        ),
        migrations.AlterField(
            model_name='hcmwdesop',
            name='hccm12n26',
            field=models.BinaryField(blank=True, db_column='HCCM12N26', null=True),
        ),
        migrations.AlterField(
            model_name='hcmwinfpa',
            name='hccm12n113',
            field=models.BinaryField(blank=True, db_column='HCCM12N113', null=True),
        ),
        migrations.AlterField(
            model_name='hcmwinfpa',
            name='hccm12n12',
            field=models.BinaryField(blank=True, db_column='HCCM12N12', null=True),
        ),
        migrations.AlterField(
            model_name='hcmwinfpa',
            name='hccm12n13',
            field=models.BinaryField(blank=True, db_column='HCCM12N13', null=True),
        ),
        migrations.AlterField(
            model_name='hcmwnutr0',
            name='hccm12n02',
            field=models.BinaryField(blank=True, db_column='HCCM12N02', null=True),
        ),
        migrations.AlterField(
            model_name='hcnautintv',
            name='hcadocfin',
            field=models.BinaryField(blank=True, db_column='HCADOCFIN', null=True),
        ),
        migrations.AlterField(
            model_name='hcnautintv',
            name='hcanotifica',
            field=models.BinaryField(blank=True, db_column='HCANOTIFICA', null=True),
        ),
        migrations.AlterField(
            model_name='hcnautintv',
            name='hcpacfir',
            field=models.BinaryField(blank=True, db_column='HCPACFIR', null=True),
        ),
        migrations.AlterField(
            model_name='hcnautintv',
            name='hcrepfir',
            field=models.BinaryField(blank=True, db_column='HCREPFIR', null=True),
        ),
        migrations.AlterField(
            model_name='hcnconcotri',
            name='hciimage',
            field=models.BinaryField(blank=True, db_column='HCIIMAGE', null=True),
        ),
        migrations.AlterField(
            model_name='hcndiapac',
            name='dianotifica',
            field=models.BinaryField(blank=True, db_column='DIANOTIFICA', null=True),
        ),
        migrations.AlterField(
            model_name='hcndishis',
            name='geprepmod',
            field=models.BinaryField(blank=True, db_column='GEPREPMOD', null=True),
        ),
        migrations.AlterField(
            model_name='hcndishis',
            name='geprepmodxml',
            field=models.BinaryField(blank=True, db_column='GEPREPMODXML', null=True),
        ),
        migrations.AlterField(
            model_name='hcndishis',
            name='hcdlytdis',
            field=models.BinaryField(blank=True, db_column='HCDLYTDIS', null=True),
        ),
        migrations.AlterField(
            model_name='hcnfolhisto',
            name='hcreporthc',
            field=models.BinaryField(blank=True, db_column='HCREPORTHC', null=True),
        ),
        migrations.AlterField(
            model_name='hcnfomimp',
            name='hcnrepmipres',
            field=models.BinaryField(blank=True, db_column='HCNREPMIPRES', null=True),
        ),
        migrations.AlterField(
            model_name='hcnmedpac',
            name='hcsfienmecd',
            field=models.BinaryField(blank=True, db_column='HCSFIENMECD', null=True),
        ),
        migrations.AlterField(
            model_name='hcnparame',
            name='hcnandaplavalini',
            field=models.BinaryField(blank=True, db_column='HCNANDAPLAVALINI', null=True),
        ),
        migrations.AlterField(
            model_name='hcnparame',
            name='hcpexcnut',
            field=models.BinaryField(blank=True, db_column='HCPEXCNUT', null=True),
        ),
        migrations.AlterField(
            model_name='hcnplancui',
            name='hcvalini',
            field=models.BinaryField(blank=True, db_column='HCVALINI', null=True),
        ),
        migrations.AlterField(
            model_name='hcnplconsinf',
            name='hcplnotific',
            field=models.BinaryField(blank=True, db_column='HCPLNOTIFIC', null=True),
        ),
        migrations.AlterField(
            model_name='hcnresimg',
            name='hciimage',
            field=models.BinaryField(blank=True, db_column='HCIIMAGE', null=True),
        ),
        migrations.AlterField(
            model_name='hcnresimg',
            name='hcimgdic',
            field=models.BinaryField(blank=True, db_column='HCIMGDIC', null=True),
        ),
        migrations.AlterField(
            model_name='ifninfofinr',
            name='ifrreporte',
            field=models.BinaryField(blank=True, db_column='IFRREPORTE', null=True),
        ),
        migrations.AlterField(
            model_name='inncsumpa',
            name='innpacfir',
            field=models.BinaryField(blank=True, db_column='INNPACFIR', null=True),
        ),
        migrations.AlterField(
            model_name='nomconcer',
            name='ccreporte',
            field=models.BinaryField(blank=True, db_column='CCREPORTE', null=True),
        ),
        migrations.AlterField(
            model_name='nomplares',
            name='parplanti',
            field=models.BinaryField(blank=True, db_column='PARPLANTI', null=True),
        ),
        migrations.AlterField(
            model_name='plantillas',
            name='binarydata',
            field=models.BinaryField(blank=True, db_column='BinaryData', null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='gepreport',
            field=models.BinaryField(blank=True, db_column='GEPREPORT', null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='gepreportxml',
            field=models.BinaryField(blank=True, db_column='GEPREPORTXML', null=True),
        ),
        migrations.AlterField(
            model_name='slnautser',
            name='sanauadj',
            field=models.BinaryField(blank=True, db_column='SANAUADJ', null=True),
        ),
        migrations.AlterField(
            model_name='slnfactur',
            name='sfaserrip',
            field=models.BinaryField(blank=True, db_column='SFASERRIP', null=True),
        ),
        migrations.AlterField(
            model_name='slnordsal',
            name='srafirmadig',
            field=models.BinaryField(blank=True, db_column='SRAFIRMADIG', null=True),
        ),
        migrations.AlterField(
            model_name='xtempo1',
            name='gepreport',
            field=models.BinaryField(blank=True, db_column='GEPREPORT', null=True),
        ),
    ]
