# Generated by Django 5.2.10 on 2026-04-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas_externas', '0004_alter_adningreso_ainfirmadig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adningreso',
            name='ainfirmadig',
            field=models.BinaryField(blank=True, db_column='AINFIRMADIG', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='ccncontrato',
            name='ctoctoresu',
            field=models.BinaryField(blank=True, db_column='CTOCTORESU', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='ccnplaact',
            name='pacplanti',
            field=models.BinaryField(blank=True, db_column='PACPLANTI', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='ccnplacont',
            name='pctplanti',
            field=models.BinaryField(blank=True, db_column='PCTPLANTI', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='ccnplares',
            name='prsplanti',
            field=models.BinaryField(blank=True, db_column='PRSPLANTI', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='comaccedir',
            name='accicono',
            field=models.BinaryField(blank=True, db_column='ACCICONO', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='comtercero',
            name='terimagen',
            field=models.BinaryField(blank=True, db_column='TERIMAGEN', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='crnparsis',
            name='banner1y2',
            field=models.BinaryField(blank=True, db_column='BANNER1Y2', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='crnparsis',
            name='banner3',
            field=models.BinaryField(blank=True, db_column='BANNER3', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='crnparsis',
            name='banner4',
            field=models.BinaryField(blank=True, db_column='BANNER4', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='crnparsis',
            name='banner5',
            field=models.BinaryField(blank=True, db_column='BANNER5', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='crnparsis',
            name='banner6',
            field=models.BinaryField(blank=True, db_column='BANNER6', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='genarcadju',
            name='adarchivo',
            field=models.BinaryField(blank=True, db_column='ADARCHIVO', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='gendiagno',
            name='diaplanotif',
            field=models.BinaryField(blank=True, db_column='DIAPLANOTIF', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='genempres',
            name='empimagen',
            field=models.BinaryField(blank=True, db_column='EMPIMAGEN', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='genmedico',
            name='gmefirma',
            field=models.BinaryField(blank=True, db_column='GMEFIRMA', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='genmedico',
            name='gmefotoima',
            field=models.BinaryField(blank=True, db_column='GMEFOTOIMA', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='genpacien',
            name='pacarchue',
            field=models.BinaryField(blank=True, db_column='PACARCHUE', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='genpacien',
            name='pacfotoima',
            field=models.BinaryField(blank=True, db_column='PACFOTOIMA', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='genpacien',
            name='usuhuella',
            field=models.BinaryField(blank=True, db_column='USUHUELLA', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='genperrep',
            name='gepreport',
            field=models.BinaryField(blank=True, db_column='GEPREPORT', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='genperrep',
            name='gepreportxml',
            field=models.BinaryField(blank=True, db_column='GEPREPORTXML', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='genusuario',
            name='usuarchue',
            field=models.BinaryField(blank=True, db_column='USUARCHUE', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='genusuario',
            name='usuhuedig',
            field=models.BinaryField(blank=True, db_column='USUHUEDIG', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='genwidenla',
            name='empimagen',
            field=models.BinaryField(blank=True, db_column='EMPIMAGEN', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='gereporte',
            name='gepreport',
            field=models.BinaryField(blank=True, db_column='GEPREPORT', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='gereporte',
            name='geresquema',
            field=models.BinaryField(blank=True, db_column='GERESQUEMA', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='gereporte',
            name='gerreportxml',
            field=models.BinaryField(blank=True, db_column='GERREPORTXML', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='ggngrafind',
            name='gglytgraf',
            field=models.BinaryField(blank=True, db_column='GGLYTGRAF', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='ggntabctrl',
            name='ggtlytpar',
            field=models.BinaryField(blank=True, db_column='GGTLYTPAR', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='ggntabctrl',
            name='ggtlytpiv',
            field=models.BinaryField(blank=True, db_column='GGTLYTPIV', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='ggntabctrl',
            name='ggtlytrep',
            field=models.BinaryField(blank=True, db_column='GGTLYTREP', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n01',
            field=models.BinaryField(blank=True, db_column='HCCM13N01', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n02',
            field=models.BinaryField(blank=True, db_column='HCCM13N02', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n03',
            field=models.BinaryField(blank=True, db_column='HCCM13N03', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n04',
            field=models.BinaryField(blank=True, db_column='HCCM13N04', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n05',
            field=models.BinaryField(blank=True, db_column='HCCM13N05', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n06',
            field=models.BinaryField(blank=True, db_column='HCCM13N06', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n07',
            field=models.BinaryField(blank=True, db_column='HCCM13N07', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n08',
            field=models.BinaryField(blank=True, db_column='HCCM13N08', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n09',
            field=models.BinaryField(blank=True, db_column='HCCM13N09', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmanexos',
            name='hccm13n10',
            field=models.BinaryField(blank=True, db_column='HCCM13N10', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmdesope',
            name='hccm12n26',
            field=models.BinaryField(blank=True, db_column='HCCM12N26', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmevoreu',
            name='hccm12n47',
            field=models.BinaryField(blank=True, db_column='HCCM12N47', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmevoreu',
            name='hccm12n61',
            field=models.BinaryField(blank=True, db_column='HCCM12N61', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmevoreu',
            name='hccm12n62',
            field=models.BinaryField(blank=True, db_column='HCCM12N62', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmfis001',
            name='hccm12n33',
            field=models.BinaryField(blank=True, db_column='HCCM12N33', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcminfpat',
            name='hccm12n113',
            field=models.BinaryField(blank=True, db_column='HCCM12N113', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcminfpat',
            name='hccm12n12',
            field=models.BinaryField(blank=True, db_column='HCCM12N12', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcminfpat',
            name='hccm12n125',
            field=models.BinaryField(blank=True, db_column='HCCM12N125', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcminfpat',
            name='hccm12n126',
            field=models.BinaryField(blank=True, db_column='HCCM12N126', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcminfpat',
            name='hccm12n13',
            field=models.BinaryField(blank=True, db_column='HCCM12N13', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmnutr01',
            name='hccm12n02',
            field=models.BinaryField(blank=True, db_column='HCCM12N02', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmradiot',
            name='hccm12n11',
            field=models.BinaryField(blank=True, db_column='HCCM12N11', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmradiot',
            name='hccm12n12',
            field=models.BinaryField(blank=True, db_column='HCCM12N12', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmradiot',
            name='hccm12n348',
            field=models.BinaryField(blank=True, db_column='HCCM12N348', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmradiot',
            name='hccm13n298',
            field=models.BinaryField(blank=True, db_column='HCCM13N298', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmtami02',
            name='hccm12n30',
            field=models.BinaryField(blank=True, db_column='HCCM12N30', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmtami02',
            name='hccm12n31',
            field=models.BinaryField(blank=True, db_column='HCCM12N31', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmtami02',
            name='hccm12n32',
            field=models.BinaryField(blank=True, db_column='HCCM12N32', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmtami02',
            name='hccm12n33',
            field=models.BinaryField(blank=True, db_column='HCCM12N33', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmterf01',
            name='hccm12n33',
            field=models.BinaryField(blank=True, db_column='HCCM12N33', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmterf01',
            name='hccm12n39',
            field=models.BinaryField(blank=True, db_column='HCCM12N39', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmwdesop',
            name='hccm12n26',
            field=models.BinaryField(blank=True, db_column='HCCM12N26', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmwinfpa',
            name='hccm12n113',
            field=models.BinaryField(blank=True, db_column='HCCM12N113', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmwinfpa',
            name='hccm12n12',
            field=models.BinaryField(blank=True, db_column='HCCM12N12', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmwinfpa',
            name='hccm12n13',
            field=models.BinaryField(blank=True, db_column='HCCM12N13', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcmwnutr0',
            name='hccm12n02',
            field=models.BinaryField(blank=True, db_column='HCCM12N02', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnautintv',
            name='hcadocfin',
            field=models.BinaryField(blank=True, db_column='HCADOCFIN', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnautintv',
            name='hcanotifica',
            field=models.BinaryField(blank=True, db_column='HCANOTIFICA', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnautintv',
            name='hcpacfir',
            field=models.BinaryField(blank=True, db_column='HCPACFIR', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnautintv',
            name='hcrepfir',
            field=models.BinaryField(blank=True, db_column='HCREPFIR', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnconcotri',
            name='hciimage',
            field=models.BinaryField(blank=True, db_column='HCIIMAGE', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcndiapac',
            name='dianotifica',
            field=models.BinaryField(blank=True, db_column='DIANOTIFICA', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcndishis',
            name='geprepmod',
            field=models.BinaryField(blank=True, db_column='GEPREPMOD', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcndishis',
            name='geprepmodxml',
            field=models.BinaryField(blank=True, db_column='GEPREPMODXML', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcndishis',
            name='hcdlytdis',
            field=models.BinaryField(blank=True, db_column='HCDLYTDIS', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnfolhisto',
            name='hcreporthc',
            field=models.BinaryField(blank=True, db_column='HCREPORTHC', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnfomimp',
            name='hcnrepmipres',
            field=models.BinaryField(blank=True, db_column='HCNREPMIPRES', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnmedpac',
            name='hcsfienmecd',
            field=models.BinaryField(blank=True, db_column='HCSFIENMECD', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnparame',
            name='hcnandaplavalini',
            field=models.BinaryField(blank=True, db_column='HCNANDAPLAVALINI', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnparame',
            name='hcpexcnut',
            field=models.BinaryField(blank=True, db_column='HCPEXCNUT', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnplancui',
            name='hcvalini',
            field=models.BinaryField(blank=True, db_column='HCVALINI', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnplconsinf',
            name='hcplnotific',
            field=models.BinaryField(blank=True, db_column='HCPLNOTIFIC', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnresimg',
            name='hciimage',
            field=models.BinaryField(blank=True, db_column='HCIIMAGE', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='hcnresimg',
            name='hcimgdic',
            field=models.BinaryField(blank=True, db_column='HCIMGDIC', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='ifninfofinr',
            name='ifrreporte',
            field=models.BinaryField(blank=True, db_column='IFRREPORTE', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='inncsumpa',
            name='innpacfir',
            field=models.BinaryField(blank=True, db_column='INNPACFIR', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='nomconcer',
            name='ccreporte',
            field=models.BinaryField(blank=True, db_column='CCREPORTE', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='nomplares',
            name='parplanti',
            field=models.BinaryField(blank=True, db_column='PARPLANTI', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='plantillas',
            name='binarydata',
            field=models.BinaryField(blank=True, db_column='BinaryData', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='gepreport',
            field=models.BinaryField(blank=True, db_column='GEPREPORT', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='gepreportxml',
            field=models.BinaryField(blank=True, db_column='GEPREPORTXML', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='slnautser',
            name='sanauadj',
            field=models.BinaryField(blank=True, db_column='SANAUADJ', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='slnfactur',
            name='sfaserrip',
            field=models.BinaryField(blank=True, db_column='SFASERRIP', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='slnordsal',
            name='srafirmadig',
            field=models.BinaryField(blank=True, db_column='SRAFIRMADIG', max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='xtempo1',
            name='gepreport',
            field=models.BinaryField(blank=True, db_column='GEPREPORT', max_length='max', null=True),
        ),
    ]
