# Generated by Django 5.2.10 on 2026-04-13 20:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_tabHonorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Use solo mayúsculas y dígitos (sin espacios).', regex='^[A-Z0-9]+$')], verbose_name='Código Honorario')),
                ('valorHora', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor por Hora')),
                ('valorMes', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor por Mes')),
            ],
            options={
                'verbose_name': 'Tabla de Honorarios',
                'verbose_name_plural': 'Tablas de Honorarios',
                'db_table': 'tablas_001_Organigrama_Honorarios',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Organigrama01',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3, message='Debe tener exactamente 3 caracteres.'), django.core.validators.RegexValidator(message='Use solo mayúsculas y dígitos (sin espacios).', regex='^[A-Z0-9]+$')], verbose_name='Código Nivel 1')),
                ('descripcion', models.CharField(max_length=600, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Organigrama Nivel 1',
                'verbose_name_plural': 'Organigramas Nivel 1',
                'db_table': 'tablas_001_Organigrama_Nivel1',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Organigrama02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2, message='Debe tener exactamente 2 caracteres.'), django.core.validators.RegexValidator(message='Use solo mayúsculas y dígitos (sin espacios).', regex='^[A-Z0-9]+$')], verbose_name='Código Nivel 2')),
                ('descripcion', models.CharField(max_length=600, verbose_name='Descripción')),
                ('Organigrama01', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel2', to='A_00_Organigrama.organigrama01', verbose_name='Nivel 1')),
            ],
            options={
                'verbose_name': 'Organigrama Nivel 2',
                'verbose_name_plural': 'Organigramas Nivel 2',
                'db_table': 'tablas_001_Organigrama_Nivel2',
                'ordering': ('Organigrama01_id', 'codigo'),
                'unique_together': {('Organigrama01', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Organigrama03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2, message='Debe tener exactamente 2 caracteres.'), django.core.validators.RegexValidator(message='Use solo mayúsculas y dígitos (sin espacios).', regex='^[A-Z0-9]+$')], verbose_name='Código Nivel 3')),
                ('descripcion', models.CharField(max_length=600, verbose_name='Descripción')),
                ('Organigrama01', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel3p1', to='A_00_Organigrama.organigrama01', verbose_name='Nivel 1')),
                ('Organigrama02', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel3', to='A_00_Organigrama.organigrama02', verbose_name='Nivel 2')),
            ],
            options={
                'verbose_name': 'Organigrama Nivel 3',
                'verbose_name_plural': 'Organigramas Nivel 3',
                'db_table': 'tablas_001_Organigrama_Nivel3',
                'ordering': ('Organigrama01_id', 'Organigrama02_id', 'codigo'),
                'unique_together': {('Organigrama01', 'Organigrama02', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Organigrama04',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3, message='Debe tener exactamente 3 caracteres.'), django.core.validators.RegexValidator(message='Use solo mayúsculas y dígitos (sin espacios).', regex='^[A-Z0-9]+$')], verbose_name='Código Nivel 4')),
                ('descripcion', models.CharField(max_length=600, verbose_name='Descripción')),
                ('Organigrama01', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel4p1', to='A_00_Organigrama.organigrama01', verbose_name='Nivel 1')),
                ('Organigrama02', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel4p2', to='A_00_Organigrama.organigrama02', verbose_name='Nivel 2')),
                ('Organigrama03', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel4', to='A_00_Organigrama.organigrama03', verbose_name='Nivel 3')),
            ],
            options={
                'verbose_name': 'Organigrama Nivel 4',
                'verbose_name_plural': 'Organigramas Nivel 4',
                'db_table': 'tablas_001_Organigrama_Nivel4',
                'ordering': ('Organigrama01_id', 'Organigrama02_id', 'Organigrama03_id', 'codigo'),
                'unique_together': {('Organigrama01', 'Organigrama02', 'Organigrama03', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Organigrama05',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2, message='Debe tener exactamente 2 caracteres.'), django.core.validators.RegexValidator(message='Use solo mayúsculas y dígitos (sin espacios).', regex='^[A-Z0-9]+$')], verbose_name='Código Nivel 5')),
                ('descripcion', models.CharField(max_length=600, verbose_name='Descripción')),
                ('Organigrama01', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel5p1', to='A_00_Organigrama.organigrama01', verbose_name='Nivel 1')),
                ('Organigrama02', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel5p2', to='A_00_Organigrama.organigrama02', verbose_name='Nivel 2')),
                ('Organigrama03', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel5p3', to='A_00_Organigrama.organigrama03', verbose_name='Nivel 3')),
                ('Organigrama04', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel5', to='A_00_Organigrama.organigrama04', verbose_name='Nivel 4')),
            ],
            options={
                'verbose_name': 'Organigrama Nivel 5',
                'verbose_name_plural': 'Organigramas Nivel 5',
                'db_table': 'tablas_001_Organigrama_Nivel5',
                'ordering': ('Organigrama01_id', 'Organigrama02_id', 'Organigrama03_id', 'Organigrama04_id', 'codigo'),
                'unique_together': {('Organigrama01', 'Organigrama02', 'Organigrama03', 'Organigrama04', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Organigrama06',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3, message='Debe tener exactamente 3 caracteres.'), django.core.validators.RegexValidator(message='Use solo mayúsculas y dígitos (sin espacios).', regex='^[A-Z0-9]+$')], verbose_name='Código Nivel 6')),
                ('descripcion', models.CharField(max_length=600, verbose_name='Descripción')),
                ('Organigrama01', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel6p1', to='A_00_Organigrama.organigrama01', verbose_name='Nivel 1')),
                ('Organigrama02', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel6p2', to='A_00_Organigrama.organigrama02', verbose_name='Nivel 2')),
                ('Organigrama03', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel6p3', to='A_00_Organigrama.organigrama03', verbose_name='Nivel 3')),
                ('Organigrama04', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel6p4', to='A_00_Organigrama.organigrama04', verbose_name='Nivel 4')),
                ('Organigrama05', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel6p5', to='A_00_Organigrama.organigrama05', verbose_name='Nivel 5')),
            ],
            options={
                'verbose_name': 'Organigrama Nivel 6',
                'verbose_name_plural': 'Organigramas Nivel 6',
                'db_table': 'tablas_001_Organigrama_Nivel6',
                'ordering': ('Organigrama01_id', 'Organigrama02_id', 'Organigrama03_id', 'Organigrama04_id', 'Organigrama05_id', 'codigo'),
                'unique_together': {('Organigrama01', 'Organigrama02', 'Organigrama03', 'Organigrama04', 'Organigrama05', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Supervisores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.PositiveIntegerField(editable=False, verbose_name='Ítem')),
                ('Organigrama01', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama01', verbose_name='Nivel 1')),
                ('Organigrama02', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama02', verbose_name='Nivel 2')),
                ('Organigrama03', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama03', verbose_name='Nivel 3')),
                ('Organigrama04', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama04', verbose_name='Nivel 4')),
                ('Organigrama05', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama05', verbose_name='Nivel 5')),
                ('Organigrama06', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama06', verbose_name='Nivel 6')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisores',
                'db_table': 'tablas_001_Organigrama_Supervisores',
                'ordering': ('Item',),
            },
        ),
    ]
