# Generated by Django 4.2.30 on 2026-05-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crueremisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remision',
            name='medico_hudn',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Médico HUDN que confirma'),
        ),
    ]
