# Generated by Django 5.2.10 on 2026-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstetricia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionparto',
            name='paciente',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='atencionparto',
            table='unificador_v1_atencionparto',
        ),
    ]
