# Generated by Django 5.2.10 on 2026-05-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinadorArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_nombre', models.CharField(max_length=150, unique=True)),
                ('nombre_coordinador', models.CharField(max_length=150)),
                ('email_coordinador', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'apc_coordinadores_area',
                'ordering': ['area_nombre'],
            },
        ),
        migrations.CreateModel(
            name='DestinatarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso_clave', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'apc_destinatarios_rol',
                'ordering': ['permiso_clave', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EncabezadoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='ASIGNACIÓN DE PERMISOS Y CLAVES', max_length=200)),
                ('codigo', models.CharField(default='FRSGI-002', max_length=50)),
                ('version', models.CharField(default='06', max_length=10)),
                ('fecha_elaboracion', models.CharField(default='05 DE JUNIO DE 2014', max_length=100)),
                ('fecha_actualizacion', models.CharField(default='22 DE SEPTIEMBRE DE 2023', max_length=100)),
                ('hoja', models.CharField(default='1 DE 1', max_length=20)),
            ],
            options={
                'db_table': 'apc_encabezado_config',
            },
        ),
        migrations.CreateModel(
            name='FirmantesFijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('coord_talento_humano', 'Coordinador Talento Humano'), ('coord_gestion_info', 'Coordinador Gestión de Información')], max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'apc_firmantes_fijos',
            },
        ),
        migrations.CreateModel(
            name='ListaBlancaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usunombre', models.CharField(max_length=100, unique=True)),
                ('usuemail', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('avatar', models.CharField(default='US', max_length=4)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'apc_lista_blanca_admin',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PermisoAccesoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=80, unique=True)),
                ('etiqueta', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.SmallIntegerField(default=1)),
                ('disponible_tercerizado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'apc_permisos_acceso_config',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SeccionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'apc_secciones_config',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diligenciamiento', models.DateField()),
                ('num_identificacion', models.CharField(max_length=20)),
                ('lugar_expedicion', models.CharField(max_length=100)),
                ('nombres_apellidos', models.CharField(max_length=200)),
                ('direccion_residencia', models.CharField(max_length=200)),
                ('tel_celular', models.CharField(max_length=20)),
                ('correo_personal', models.CharField(max_length=150)),
                ('tel_fijo', models.CharField(blank=True, default='', max_length=20)),
                ('tipo_vinculacion', models.CharField(choices=[('planta_permanente', 'Planta Permanente'), ('planta_temporal', 'Planta Temporal'), ('ops', 'OPS'), ('tercerizado', 'Tercerizado(a)/Contratista')], max_length=20)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('area_servicios', models.CharField(max_length=150)),
                ('cargo_funcionario', models.CharField(max_length=150)),
                ('num_registro_tarjeta', models.CharField(blank=True, default='', max_length=100)),
                ('nombre_empresa_contratista', models.CharField(blank=True, default='', max_length=200)),
                ('direccion_empresa_contratista', models.CharField(blank=True, default='', max_length=200)),
                ('tel_empresa_contratista', models.CharField(blank=True, default='', max_length=20)),
                ('fecha_entrenamiento', models.DateField(blank=True, null=True)),
                ('hora_inicio_entrenamiento', models.TimeField(blank=True, null=True)),
                ('hora_fin_entrenamiento', models.TimeField(blank=True, null=True)),
                ('responsable_entrenamiento', models.CharField(blank=True, default='', max_length=150)),
                ('entrenamiento_dgh', models.BooleanField(default=False)),
                ('entrenamiento_correo', models.BooleanField(default=False)),
                ('entrenamiento_aplicativos', models.BooleanField(default=False)),
                ('entrenamiento_intranet', models.BooleanField(default=False)),
                ('acepto_confidencialidad', models.BooleanField(default=False)),
                ('firma_funcionario', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('EN_TRAMITE', 'En Trámite'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado')], default='EN_TRAMITE', max_length=15)),
                ('creado_por', models.CharField(blank=True, default='', max_length=100)),
                ('correo_notificacion', models.CharField(blank=True, default='', max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'apc_solicitudes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FirmaAPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_firma', models.CharField(choices=[('coordinador_area', 'Coordinador de Área'), ('resp_contratista', 'Responsable Contratista'), ('funcionario', 'Funcionario'), ('coord_talento_humano', 'Coordinador Talento Humano'), ('coord_gestion_info', 'Coordinador Gestión de Información')], max_length=30)),
                ('nombre_firmante', models.CharField(max_length=150)),
                ('email_firmante', models.CharField(blank=True, default='', max_length=150)),
                ('firma_imagen', models.TextField(blank=True, default='')),
                ('token_firma', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('token_expira', models.DateTimeField(blank=True, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('orden', models.SmallIntegerField(default=1)),
                ('auto_firma_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_firmadas_por', to='asignacion_permisos.firmaapc')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='asignacion_permisos.solicitudapc')),
            ],
            options={
                'db_table': 'apc_firmas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmailLogAPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=150)),
                ('asunto', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ERROR', 'Error')], max_length=10)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignacion_permisos.solicitudapc')),
            ],
            options={
                'db_table': 'apc_email_log',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='PermisoSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso_clave', models.CharField(max_length=80)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_solicitados', to='asignacion_permisos.solicitudapc')),
            ],
            options={
                'db_table': 'apc_permisos_solicitados',
                'unique_together': {('solicitud', 'permiso_clave')},
            },
        ),
    ]
