# Generated by Django 5.2.10 on 2026-05-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_permisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encabezadoconfig',
            name='texto_mensaje',
            field=models.TextField(default='Declaro de manera libre, expresa, inequívoca e informada que, conozco el ACUERDO INDIVIDUAL DE CONFIDENCIALIDAD DE LA INFORMACIÓN FRSG1-001 y que mediante la firma de este documento confirmo y acepto mi responsabilidad para los fines pertinentes.'),
        ),
        migrations.CreateModel(
            name='CampoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.SmallIntegerField()),
                ('campo_clave', models.CharField(max_length=100)),
                ('etiqueta', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'apc_campos_config',
                'ordering': ['seccion', 'orden'],
                'unique_together': {('seccion', 'campo_clave')},
            },
        ),
    ]
