# Generated by Django 5.2.10 on 2026-05-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_permisos', '0005_solicitudapc_foto_carnet_tipo_sangre'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinadorareagmail',
            name='usuario_dinamica',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='solicitudapc',
            name='numero_contrato',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
