# Generated by Django 5.2.10 on 2026-05-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_permisos', '0006_add_usuario_dinamica_and_numero_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinadorareagmail',
            name='firma_imagen',
            field=models.TextField(blank=True, default=''),
        ),
    ]
