# Generated by Django 5.2.10 on 2026-05-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasesGenerales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formatos_Hudn_area',
            fields=[
                ('codigo', models.CharField(help_text='Ejemplo: FRFAR, FRHOS, FRLAB', max_length=5, primary_key=True, serialize=False, verbose_name='Código de Área')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Área')),
                ('cantidad_estimada', models.IntegerField(default=0, verbose_name='Cantidad de Formatos')),
            ],
            options={
                'verbose_name': 'Área de Formatos',
                'verbose_name_plural': 'Áreas de Formatos',
                'db_table': 'Formatos_Hudn_area',
                'ordering': ['codigo'],
            },
        ),
    ]
