# Generated by Django 5.2.10 on 2026-01-22 22:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasesGenerales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formatos_Hudn',
            fields=[
                ('codigo_formato', models.CharField(help_text='Formato: FR + 3 letras del área + guion + 3 dígitos (ej: FRJUR-001)', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El código debe tener el formato FRXXX-NNN (ej: FRJUR-001, FRADM-025)', regex='^FR[A-Z]{3}-\\d{3}$')], verbose_name='Código del Formato')),
                ('nombre_formato', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Solo letras, espacios y signos básicos (- . / ( )).', regex='^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ\\s\\-\\.\\(\\)\\/]+$')], verbose_name='Nombre del Formato')),
                ('version', models.CharField(default='1.0', help_text='Versión del formato (ej: 1.0, 2.1, etc.)', max_length=10, verbose_name='Versión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('elaborado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formatos_elaborados', to=settings.AUTH_USER_MODEL, verbose_name='Elaborado Por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formatos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por')),
            ],
            options={
                'verbose_name': 'Formato HUDN',
                'verbose_name_plural': 'Formatos HUDN',
                'db_table': 'Formatos_Hudn',
                'ordering': ('codigo_formato',),
            },
        ),
    ]
