# Generated by Django 5.2.10 on 2026-05-06 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasesGenerales', '0002_formatos_hudn_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatos_hudn',
            name='area',
            field=models.ForeignKey(default='FRFAR', on_delete=django.db.models.deletion.PROTECT, related_name='formatos', to='BasesGenerales.formatos_hudn_area', verbose_name='Área del Formato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formatos_hudn',
            name='consecutivo',
            field=models.IntegerField(blank=True, editable=False, help_text='Número secuencial dentro del área (001, 002...)', null=True, verbose_name='N° de Formato'),
        ),
        migrations.AlterField(
            model_name='formatos_hudn',
            name='codigo_formato',
            field=models.CharField(help_text='Generado automáticamente: AREA-NNN (Ej: FRJUR-001)', max_length=15, primary_key=True, serialize=False, verbose_name='Código del Formato'),
        ),
    ]
