# Generated by Django 5.0 on 2026-01-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasesGenerales', '0002_formatos_hudn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisores',
            name='Organigrama01',
        ),
        migrations.RemoveField(
            model_name='supervisores',
            name='Organigrama02',
        ),
        migrations.RemoveField(
            model_name='supervisores',
            name='Organigrama03',
        ),
        migrations.RemoveField(
            model_name='supervisores',
            name='Organigrama04',
        ),
        migrations.RemoveField(
            model_name='supervisores',
            name='Organigrama05',
        ),
        migrations.RemoveField(
            model_name='supervisores',
            name='Organigrama06',
        ),
        migrations.RemoveField(
            model_name='supervisores',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='opsSupervicion',
        ),
        migrations.DeleteModel(
            name='Supervisores',
        ),
    ]
