# Generated by Django 5.2.10 on 2026-05-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasesGenerales', '0003_formatos_hudn_area_formatos_hudn_consecutivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatos_hudn',
            name='slug_app',
            field=models.SlugField(blank=True, help_text='Si se define, este formato abrirá una aplicación funcional en lugar de solo vista estática.', null=True, verbose_name='Slug de Aplicación'),
        ),
    ]
