# Generated by Django 5.0 on 2026-01-25 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasesGenerales', '0003_remove_supervisores_organigrama01_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.PositiveIntegerField(editable=False, verbose_name='Ítem')),
                ('Organigrama01', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='BasesGenerales.organigrama01', verbose_name='Nivel 1')),
                ('Organigrama02', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='BasesGenerales.organigrama02', verbose_name='Nivel 2')),
                ('Organigrama03', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='BasesGenerales.organigrama03', verbose_name='Nivel 3')),
                ('Organigrama04', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='BasesGenerales.organigrama04', verbose_name='Nivel 4')),
                ('Organigrama05', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='BasesGenerales.organigrama05', verbose_name='Nivel 5')),
                ('Organigrama06', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='BasesGenerales.organigrama06', verbose_name='Nivel 6')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisores',
                'db_table': 'supervisores',
                'ordering': ('Item',),
            },
        ),
    ]
