# Generated by Django 5.2.10 on 2026-04-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_00_Organigrama', '0001_initial'),
        ('BasesGenerales', '0004_supervisores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opscomponentetecnico',
            name='claseServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='A_00_Organigrama.doc_tabhonorarios', verbose_name='Clase de Servicio'),
        ),
        migrations.AlterField(
            model_name='ingresohospital',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama01', verbose_name='Área'),
        ),
        migrations.RemoveField(
            model_name='organigrama02',
            name='Organigrama01',
        ),
        migrations.AlterField(
            model_name='paa',
            name='Dependencia_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paa_dep1', to='A_00_Organigrama.organigrama01', verbose_name='Dependencia 1'),
        ),
        migrations.RemoveField(
            model_name='organigrama04',
            name='Organigrama01',
        ),
        migrations.RemoveField(
            model_name='organigrama06',
            name='Organigrama01',
        ),
        migrations.RemoveField(
            model_name='organigrama05',
            name='Organigrama01',
        ),
        migrations.RemoveField(
            model_name='supervisores',
            name='Organigrama01',
        ),
        migrations.AlterField(
            model_name='opscomponentetecnico',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama01', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='ops4dependencia',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama01', verbose_name='Área'),
        ),
        migrations.RemoveField(
            model_name='organigrama03',
            name='Organigrama01',
        ),
        migrations.AlterUniqueTogether(
            name='organigrama02',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='opscomponentetecnico',
            name='Subgerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama02', verbose_name='Subgerencia'),
        ),
        migrations.AlterField(
            model_name='ops4dependencia',
            name='Subgerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama02', verbose_name='Subgerencia'),
        ),
        migrations.RemoveField(
            model_name='organigrama03',
            name='Organigrama02',
        ),
        migrations.AlterField(
            model_name='ingresohospital',
            name='Subgerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama02', verbose_name='Subgerencia'),
        ),
        migrations.AlterField(
            model_name='ops4viabilidad',
            name='Subgerencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='A_00_Organigrama.organigrama02', verbose_name='Seleccione Subgerencia (Administrativa o Salud)'),
        ),
        migrations.AlterField(
            model_name='paa',
            name='Dependencia_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paa_dep2', to='A_00_Organigrama.organigrama02', verbose_name='Dependencia 2'),
        ),
        migrations.AlterField(
            model_name='ops4disponibilidad',
            name='NumerodeCdp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='A_00_Organigrama.organigrama02', verbose_name='Seleccione Subgerencia (Administrativa o Salud)'),
        ),
        migrations.RemoveField(
            model_name='organigrama06',
            name='Organigrama02',
        ),
        migrations.RemoveField(
            model_name='organigrama05',
            name='Organigrama02',
        ),
        migrations.RemoveField(
            model_name='supervisores',
            name='Organigrama02',
        ),
        migrations.RemoveField(
            model_name='organigrama04',
            name='Organigrama02',
        ),
        migrations.AlterUniqueTogether(
            name='organigrama03',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='ops4dependencia',
            name='Dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama03', verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='opscomponentetecnico',
            name='Dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama03', verbose_name='Dependencia'),
        ),
        migrations.RemoveField(
            model_name='supervisores',
            name='Organigrama03',
        ),
        migrations.AlterField(
            model_name='ingresohospital',
            name='Dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='A_00_Organigrama.organigrama03', verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='paa',
            name='Dependencia_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paa_dep3', to='A_00_Organigrama.organigrama03', verbose_name='Dependencia 3'),
        ),
        migrations.RemoveField(
            model_name='organigrama06',
            name='Organigrama03',
        ),
        migrations.RemoveField(
            model_name='organigrama05',
            name='Organigrama03',
        ),
        migrations.RemoveField(
            model_name='organigrama04',
            name='Organigrama03',
        ),
        migrations.AlterUniqueTogether(
            name='organigrama04',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='paa',
            name='Dependencia_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paa_dep4', to='A_00_Organigrama.organigrama04', verbose_name='Dependencia 4'),
        ),
        migrations.RemoveField(
            model_name='organigrama05',
            name='Organigrama04',
        ),
        migrations.RemoveField(
            model_name='supervisores',
            name='Organigrama04',
        ),
        migrations.RemoveField(
            model_name='organigrama06',
            name='Organigrama04',
        ),
        migrations.AlterUniqueTogether(
            name='organigrama05',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='paa',
            name='Dependencia_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paa_dep5', to='A_00_Organigrama.organigrama05', verbose_name='Dependencia 5'),
        ),
        migrations.RemoveField(
            model_name='supervisores',
            name='Organigrama05',
        ),
        migrations.RemoveField(
            model_name='organigrama06',
            name='Organigrama05',
        ),
        migrations.AlterUniqueTogether(
            name='organigrama06',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='supervisores',
            name='Organigrama06',
        ),
        migrations.AlterField(
            model_name='paa',
            name='Dependencia_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paa_dep6', to='A_00_Organigrama.organigrama06', verbose_name='Dependencia 6'),
        ),
        migrations.RemoveField(
            model_name='supervisores',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='doc_tabHonorarios',
        ),
        migrations.DeleteModel(
            name='Organigrama01',
        ),
        migrations.DeleteModel(
            name='Organigrama02',
        ),
        migrations.DeleteModel(
            name='Organigrama03',
        ),
        migrations.DeleteModel(
            name='Organigrama04',
        ),
        migrations.DeleteModel(
            name='Organigrama05',
        ),
        migrations.DeleteModel(
            name='Organigrama06',
        ),
        migrations.DeleteModel(
            name='Supervisores',
        ),
    ]
