# Generated by Django 5.2.10 on 2026-02-18 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MezclaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_oid', models.IntegerField(verbose_name='OID Paciente')),
                ('medico_oid', models.IntegerField(verbose_name='OID Médico Solicitante')),
                ('tipo_mezcla', models.CharField(choices=[('NPT', 'Nutrición Parenteral Total'), ('ATB', 'Antibióticos Reconstituidos'), ('ONC', 'Medicamentos Oncológicos'), ('AJU', 'Ajuste de Dosis Específicas')], max_length=3, verbose_name='Tipo de Mezcla')),
                ('descripcion_medicamento', models.TextField(verbose_name='Medicamento y Dosis Solicitada')),
                ('prioridad', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('STAT', 'Inmediata (STAT)')], default='NORMAL', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Verificación'), ('VERIFICADA', 'Validada por Farmacéutico'), ('PREPARANDO', 'En Proceso de Mezcla'), ('CONTROLADA', 'Control de Calidad Aprobado'), ('DISTRIBUIDA', 'Entregada a Servicio'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('observaciones_clinicas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orden de Mezcla',
                'verbose_name_plural': 'Órdenes de Mezcla',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='MezclaPreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_interno', models.CharField(max_length=50, unique=True, verbose_name='Lote de Preparación')),
                ('farmaceutico_oid', models.IntegerField(verbose_name='OID Farmacéutico Responsable')),
                ('cabina_id', models.CharField(max_length=50, verbose_name='Identificación de Cabina/Flujo Laminar')),
                ('insumos_utilizados', models.TextField(default='{}', verbose_name='Detalle de Insumos y Cantidades')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tecnico_preparador', models.CharField(max_length=100, verbose_name='Nombre del Técnico Preparador')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparacion', to='CentralDeMezclas.mezclaorden')),
            ],
            options={
                'verbose_name': 'Preparación de Mezcla',
                'verbose_name_plural': 'Preparaciones de Mezcla',
            },
        ),
        migrations.CreateModel(
            name='MezclaDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_destino', models.CharField(max_length=100, verbose_name='Servicio de Destino (UCI, ONCO, etc.)')),
                ('responsable_recibe', models.CharField(max_length=150, verbose_name='Nombre de quien recibe en Servicio')),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('entregado_por_oid', models.IntegerField(verbose_name='OID Personal que entrega')),
                ('preparacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribucion', to='CentralDeMezclas.mezclapreparacion')),
            ],
            options={
                'verbose_name': 'Distribución de Mezcla',
                'verbose_name_plural': 'Distribuciones de Mezcla',
            },
        ),
        migrations.CreateModel(
            name='MezclaControlCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_ok', models.BooleanField(default=False, verbose_name='Inspección Visual Correcta')),
                ('etiquetado_ok', models.BooleanField(default=False, verbose_name='Etiquetado y Trazabilidad Correcta')),
                ('hermeticidad_ok', models.BooleanField(default=False, verbose_name='Cierre Hermético Verificado')),
                ('valoracion_final', models.TextField(blank=True, null=True, verbose_name='Observaciones de Calidad')),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_control', models.DateTimeField(auto_now_add=True)),
                ('controlador_oid', models.IntegerField(verbose_name='OID del Validador de Calidad')),
                ('preparacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='CentralDeMezclas.mezclapreparacion')),
            ],
            options={
                'verbose_name': 'Control de Calidad',
                'verbose_name_plural': 'Controles de Calidad',
            },
        ),
    ]
