# Generated by Django 5.2.10 on 2026-02-18 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReempaqueMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cum', models.CharField(max_length=50, unique=True, verbose_name='CUM')),
                ('nombre_generico', models.CharField(max_length=255, verbose_name='Nombre Genérico')),
                ('concentracion', models.CharField(max_length=100, verbose_name='Concentración')),
                ('forma_farmaceutica', models.CharField(max_length=100, verbose_name='Forma Farmacéutica')),
                ('presentacion_comercial', models.CharField(max_length=100, verbose_name='Presentación Comercial')),
                ('registro_invima', models.CharField(max_length=100, verbose_name='Registro INVIMA')),
                ('vencimiento_registro', models.DateField(blank=True, null=True, verbose_name='Vencimiento Registro INVIMA')),
                ('fabricante', models.CharField(max_length=255, verbose_name='Laboratorio Fabricante')),
                ('condiciones_almacenamiento', models.TextField(blank=True, null=True, verbose_name='Condiciones de Almacenamiento')),
            ],
            options={
                'verbose_name': 'Medicamento para Reempaque',
                'verbose_name_plural': 'Medicamentos para Reempaque',
                'ordering': ['nombre_generico'],
            },
        ),
        migrations.CreateModel(
            name='ReempaqueOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_interno', models.CharField(max_length=50, unique=True, verbose_name='Lote Interno (REE...)')),
                ('lote_fabricante', models.CharField(max_length=50, verbose_name='Lote del Fabricante')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento Original')),
                ('fecha_vencimiento_reempaque', models.DateField(verbose_name='Vencimiento Post-Reempaque')),
                ('cantidad_a_reempacar', models.IntegerField(verbose_name='Cantidad Inicial')),
                ('cantidad_final_aprobada', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Final Aprobada')),
                ('fecha_produccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsable_reempaque_oid', models.IntegerField(verbose_name='OID Responsable de Reempaque')),
                ('farmaceutico_validador_oid', models.IntegerField(verbose_name='OID Farmacéutico que Valida')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('CONTROL_CALIDAD', 'En Control de Calidad'), ('LIBERADO', 'Liberado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='CentralDeMezclas.reempaquemedicamento')),
            ],
            options={
                'verbose_name': 'Orden de Reempaque',
                'verbose_name_plural': 'Órdenes de Reempaque',
                'ordering': ['-fecha_produccion'],
            },
        ),
        migrations.CreateModel(
            name='ReempaqueMuestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano_lote', models.IntegerField()),
                ('nivel_inspeccion', models.CharField(default='II', max_length=10, verbose_name='Nivel de Inspección')),
                ('letra_codigo', models.CharField(max_length=5, verbose_name='Letra Código')),
                ('tamano_muestra', models.IntegerField(verbose_name='Tamaño de la Muestra')),
                ('ac', models.IntegerField(verbose_name='Número de Aceptación (Ac)')),
                ('re', models.IntegerField(verbose_name='Número de Rechazo (Re)')),
                ('fecha_muestreo', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestreos', to='CentralDeMezclas.reempaqueorden')),
            ],
            options={
                'verbose_name': 'Muestreo de Calidad',
                'verbose_name_plural': 'Muestreos de Calidad',
            },
        ),
        migrations.CreateModel(
            name='ReempaqueControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspecto_fisico_ok', models.BooleanField(default=False, verbose_name='Aspecto Físico Correcto')),
                ('hermeticidad_ok', models.BooleanField(default=False, verbose_name='Hermeticidad Verificada')),
                ('etiquetado_completo_ok', models.BooleanField(default=False, verbose_name='Etiquetado con Info Completa')),
                ('limpieza_area_ok', models.BooleanField(default=False, verbose_name='Limpieza de Área Verificada')),
                ('unidades_defectuosas', models.IntegerField(default=0, verbose_name='Unidades Defectuosas Halladas')),
                ('observaciones_calidad', models.TextField(blank=True, null=True)),
                ('liberado', models.BooleanField(default=False, verbose_name='Producto Liberado')),
                ('fecha_liberacion', models.DateTimeField(blank=True, null=True)),
                ('responsable_liberacion_oid', models.IntegerField(blank=True, null=True, verbose_name='OID Químico Farmacéutico')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_calidad', to='CentralDeMezclas.reempaqueorden')),
            ],
            options={
                'verbose_name': 'Control de Calidad Reempaque',
                'verbose_name_plural': 'Controles de Calidad Reempaque',
            },
        ),
    ]
