# Generated by Django 5.2.10 on 2026-02-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0002_reempaquemedicamento_reempaqueorden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reempaquemedicamento',
            options={'ordering': ['nombre'], 'verbose_name': 'Medicamento para Reempaque', 'verbose_name_plural': 'Medicamentos para Reempaque'},
        ),
        migrations.RemoveField(
            model_name='reempaquemedicamento',
            name='cum',
        ),
        migrations.RemoveField(
            model_name='reempaquemedicamento',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='reempaquemedicamento',
            name='nombre_generico',
        ),
        migrations.RemoveField(
            model_name='reempaquemedicamento',
            name='presentacion_comercial',
        ),
        migrations.RemoveField(
            model_name='reempaquemedicamento',
            name='registro_invima',
        ),
        migrations.RemoveField(
            model_name='reempaquemedicamento',
            name='vencimiento_registro',
        ),
        migrations.AddField(
            model_name='reempaquemedicamento',
            name='fotosensibilidad',
            field=models.CharField(default='NO', max_length=50, verbose_name='Fotosensibilidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reempaquemedicamento',
            name='nombre',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Medicamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reempaquemedicamento',
            name='senalizacion',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Señalizaciòn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reempaquemedicamento',
            name='via',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Via'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reempaquemedicamento',
            name='concentracion',
            field=models.CharField(max_length=100, verbose_name='CONCENTRACION'),
        ),
        migrations.AlterField(
            model_name='reempaquemedicamento',
            name='condiciones_almacenamiento',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Temperatura Y Humedad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reempaquemedicamento',
            name='forma_farmaceutica',
            field=models.CharField(max_length=100, verbose_name='FORMA FARMACEUTICA'),
        ),
    ]
