# Generated by Django 5.2.10 on 2026-02-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0003_alter_reempaquemedicamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reempaqueorden',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Laboratorio'),
        ),
        migrations.AddField(
            model_name='reempaqueorden',
            name='registro_invima',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro INVIMA'),
        ),
        migrations.AddField(
            model_name='reempaqueorden',
            name='semaforizacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Semaforización'),
        ),
    ]
