# Generated by Django 5.2.10 on 2026-02-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0004_reempaqueorden_laboratorio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Color de Alerta')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código de Alerta')),
            ],
            options={
                'verbose_name': 'Alerta de Reempaque',
                'verbose_name_plural': 'Alertas de Reempaque',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ConvencionFormaFarmaceutica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_farmaceutica', models.CharField(max_length=100, verbose_name='Forma Farmacéutica')),
                ('via', models.CharField(max_length=100, verbose_name='Vía de Administración')),
            ],
            options={
                'verbose_name': 'Convención Forma Farmacéutica',
                'verbose_name_plural': 'Convenciones Formas Farmacéuticas',
                'ordering': ['forma_farmaceutica'],
            },
        ),
    ]
