# Generated by Django 5.2.10 on 2026-02-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0005_alerta_convencionformafarmaceutica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reempaquemedicamento',
            name='forma_farmaceutica',
        ),
        migrations.RemoveField(
            model_name='reempaquemedicamento',
            name='via',
        ),
        migrations.AddField(
            model_name='reempaquemedicamento',
            name='convencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CentralDeMezclas.convencionformafarmaceutica', verbose_name='Forma y Vía'),
        ),
    ]
