# Generated by Django 5.2.10 on 2026-02-19 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0006_remove_reempaquemedicamento_forma_farmaceutica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reempaquemedicamento',
            name='senalizacion',
        ),
        migrations.AddField(
            model_name='reempaquemedicamento',
            name='alerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CentralDeMezclas.alerta', verbose_name='Alerta / Semaforización'),
        ),
    ]
