# Generated by Django 5.2.10 on 2026-02-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0007_remove_reempaquemedicamento_senalizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoEsteril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='COD.')),
                ('medicamento_1', models.CharField(max_length=255, verbose_name='MEDICAMENTO 1')),
                ('medicamento_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='MEDICAMENTO 2')),
                ('concentracion_1', models.CharField(max_length=100, verbose_name='CONCENTRACION MED 1')),
                ('concentracion_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='CONCENTRACION MED 2')),
                ('dosis_estandar', models.CharField(max_length=255, verbose_name='DOSIS ESTANDAR')),
                ('dosis_frecuencia', models.CharField(max_length=255, verbose_name='DOSIS Y FRECUENCIA')),
                ('dosis_med_1', models.CharField(max_length=100, verbose_name='DOSIS MED 1')),
                ('dosis_med_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOSIS MED 2')),
                ('vol_reconstitucion_1', models.CharField(max_length=100, verbose_name='VOL. RECONSTITUCION MED 1')),
                ('vol_reconstitucion_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='VOL. RECONSTITUCION MED 2')),
                ('cantidad_necesaria', models.CharField(max_length=100, verbose_name='CANTIDAD NECESARIA')),
                ('diluyente', models.CharField(blank=True, max_length=255, null=True, verbose_name='DILUYENTE')),
                ('cod_diluyente', models.CharField(blank=True, max_length=50, null=True, verbose_name='COD. DIL.')),
                ('via', models.CharField(max_length=50, verbose_name='VIA')),
                ('vehiculo_final', models.CharField(max_length=255, verbose_name='VEHICULO FINAL')),
                ('jeringa', models.CharField(max_length=255, verbose_name='JERINGA')),
                ('agua_hipodermica', models.CharField(max_length=255, verbose_name='AGUA HIPODERMICA')),
                ('almacenamiento', models.CharField(max_length=255, verbose_name='ALMACENAMIENTO')),
                ('manejo_especial', models.CharField(blank=True, max_length=255, null=True, verbose_name='OBSERVACIONES / MANEJO')),
                ('fecha_preparacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='FECHA PREPARACIÓN')),
                ('cod_med_1', models.CharField(max_length=50, verbose_name='COD. MED 1')),
                ('cod_med_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='COD. MED 2')),
            ],
            options={
                'verbose_name': 'Medicamento Estéril (Base)',
                'verbose_name_plural': 'Medicamentos Estériles (Base)',
                'ordering': ['medicamento_1'],
            },
        ),
    ]
