# Generated by Django 5.2.10 on 2026-02-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0008_medicamentoesteril'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentoesteril',
            name='elaborado_por',
            field=models.CharField(default='Q.F. ELBERT MUÑOZ', max_length=150, verbose_name='ELABORADO POR'),
        ),
        migrations.AddField(
            model_name='medicamentoesteril',
            name='verificado_por',
            field=models.CharField(default='PILAR GALLARDO', max_length=150, verbose_name='VERIFICADO POR'),
        ),
    ]
