# Generated by Django 5.2.10 on 2026-02-20 17:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0009_medicamentoesteril_elaborado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidosisPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('orden_produccion', models.CharField(max_length=50, unique=True, verbose_name='ORDEN DE PRODUCCIÓN')),
                ('jefe_produccion', models.CharField(default='ELBERT MUÑOZ', max_length=150)),
                ('qf_preparador', models.CharField(default='ELBERT MUÑOZ', max_length=150)),
                ('alistamiento', models.CharField(default='ROSA DAVILA', max_length=150)),
                ('jefe_calidad', models.CharField(default='PILAR GALLARDO', max_length=150)),
                ('registrado_por', models.CharField(default='PAOLA DORADO', max_length=150)),
                ('digitador', models.CharField(default='ROSA DAVILA', max_length=150)),
                ('director_tecnico', models.CharField(default='TOMAS VALENCIA', max_length=150)),
                ('preelaboracion', models.CharField(default='JAIRO CORTES', max_length=150)),
            ],
            options={
                'verbose_name': 'Periodo de Producción Unidosis',
                'verbose_name_plural': 'Periodos de Producción Unidosis',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='UnidosisOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_interno', models.CharField(max_length=50, verbose_name='LOTE INTERNO')),
                ('paciente_nombre', models.CharField(max_length=255, verbose_name='NOMBRE DEL PACIENTE')),
                ('paciente_identificacion', models.CharField(max_length=50, verbose_name='IDENTIFICACION')),
                ('cama', models.CharField(max_length=20, verbose_name='CAMA')),
                ('servicio', models.CharField(max_length=100, verbose_name='SERVICIO')),
                ('dosis_estandar_pme', models.CharField(max_length=255, verbose_name='MEDICAMENTO+DOSIS ESTANDAR PME')),
                ('dosis_frecuencia', models.CharField(max_length=255, verbose_name='DOSIS Y FRECUENCIA')),
                ('sln_diluyente', models.CharField(max_length=255, verbose_name='SLN DILUYENTE')),
                ('volumen_dilucion', models.CharField(max_length=100, verbose_name='VOLUMEN DILUCION')),
                ('vehiculo_volumen_final', models.CharField(max_length=255, verbose_name='VEHICULO Y VOLUMEN FINAL')),
                ('via', models.CharField(max_length=50, verbose_name='VIA')),
                ('frecuencia', models.CharField(max_length=100, verbose_name='FRECUENCIA')),
                ('cantidad_necesaria', models.CharField(max_length=50, verbose_name='CANTIDAD NECESARIA')),
                ('volumen_dosis', models.CharField(max_length=50, verbose_name='VOLUMEN DOSIS')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='FECHA DE EXPIRACIÓN')),
                ('temp_almacenamiento', models.CharField(default='2-8 °C', max_length=50, verbose_name='T°')),
                ('luz_almacenamiento', models.CharField(default='PROTEGER LUZ', max_length=50, verbose_name='LUZ')),
                ('medicamento_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CentralDeMezclas.medicamentoesteril', verbose_name='MEDICAMENTO')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='CentralDeMezclas.unidosisperiodo')),
            ],
            options={
                'verbose_name': 'Orden Unidosis Adultos',
                'verbose_name_plural': 'Órdenes Unidosis Adultos',
            },
        ),
    ]
