# Generated by Django 5.2.10 on 2026-02-20 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0010_unidosisperiodo_unidosisorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='CÉDULA')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='NOMBRE COMPLETO')),
                ('cargo', models.CharField(blank=True, max_length=150, null=True, verbose_name='CARGO')),
                ('activo', models.BooleanField(default=True, verbose_name='ACTIVO')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.AlterField(
            model_name='unidosisperiodo',
            name='alistamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_alistamiento', to='CentralDeMezclas.funcionario', verbose_name='ALISTAMIENTO'),
        ),
        migrations.AlterField(
            model_name='unidosisperiodo',
            name='digitador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_digitador', to='CentralDeMezclas.funcionario', verbose_name='DIGITADOR'),
        ),
        migrations.AlterField(
            model_name='unidosisperiodo',
            name='director_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_director', to='CentralDeMezclas.funcionario', verbose_name='DIRECTOR TÉCNICO'),
        ),
        migrations.AlterField(
            model_name='unidosisperiodo',
            name='jefe_calidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_jefe_calidad', to='CentralDeMezclas.funcionario', verbose_name='JEFE DE C. CALIDAD'),
        ),
        migrations.AlterField(
            model_name='unidosisperiodo',
            name='jefe_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_jefe_prod', to='CentralDeMezclas.funcionario', verbose_name='JEFE DE PRODUCCIÓN'),
        ),
        migrations.AlterField(
            model_name='unidosisperiodo',
            name='preelaboracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_preelab', to='CentralDeMezclas.funcionario', verbose_name='PREELABORACIÓN'),
        ),
        migrations.AlterField(
            model_name='unidosisperiodo',
            name='qf_preparador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_qf_prep', to='CentralDeMezclas.funcionario', verbose_name='QF PREPARADOR'),
        ),
        migrations.AlterField(
            model_name='unidosisperiodo',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_registrado', to='CentralDeMezclas.funcionario', verbose_name='REGISTRADO POR'),
        ),
    ]
