# Generated by Django 5.2.10 on 2026-02-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0011_funcionario_alter_unidosisperiodo_alistamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentoesteril',
            name='alto_riesgo',
            field=models.BooleanField(default=False, verbose_name='ALTO RIESGO'),
        ),
        migrations.AddField(
            model_name='medicamentoesteril',
            name='lasa',
            field=models.BooleanField(default=False, verbose_name='LASA'),
        ),
    ]
