# Generated by Django 5.2.11 on 2026-03-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0012_medicamentoesteril_alto_riesgo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoOncologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(blank=True, null=True, verbose_name='COD.')),
                ('producto', models.CharField(max_length=255, verbose_name='PRODUCTO')),
                ('medicamento', models.CharField(max_length=255, verbose_name='MEDICAMENTO')),
                ('concentracion', models.CharField(max_length=100, verbose_name='CONCENTRACIÓN (mg, UI)')),
                ('forma_farmaceutica', models.CharField(max_length=100, verbose_name='FORMA FARMACÉUTICA')),
                ('volumen_reconstitucion', models.CharField(blank=True, max_length=100, null=True, verbose_name='VOLUMEN DE RECONSTITUCIÓN')),
                ('solucion_reconstitucion', models.CharField(blank=True, max_length=255, null=True, verbose_name='SOLUCIÓN DE RECONSTITUCIÓN')),
                ('cod_dil', models.CharField(blank=True, max_length=50, null=True, verbose_name='COD. DIL.')),
                ('administracion', models.CharField(max_length=50, verbose_name='ADMINISTRACIÓN')),
                ('vol_final', models.CharField(blank=True, max_length=100, null=True, verbose_name='VOL. FINAL (mL)')),
                ('vehiculo', models.CharField(blank=True, max_length=255, null=True, verbose_name='VEHÍCULO')),
                ('jeringa', models.CharField(blank=True, max_length=255, null=True, verbose_name='JERINGA')),
                ('aguja', models.CharField(blank=True, max_length=255, null=True, verbose_name='AGUJA')),
                ('almacenamiento', models.CharField(blank=True, max_length=255, null=True, verbose_name='ALMACENAMIENTO')),
                ('proteccion_luz', models.CharField(blank=True, max_length=255, null=True, verbose_name='PROTECCIÓN LUZ / OBSERVACIONES')),
                ('fecha_expiracion', models.CharField(blank=True, max_length=100, null=True, verbose_name='FECHA DE EXPIRACIÓN')),
            ],
            options={
                'verbose_name': 'Medicamento Oncológico (Base)',
                'verbose_name_plural': 'Medicamentos Oncológicos Alta Complejidad (Base)',
                'ordering': ['medicamento'],
            },
        ),
    ]
