# Generated by Django 5.2.11 on 2026-03-05 16:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0013_medicamentooncologico'),
    ]

    operations = [
        migrations.CreateModel(
            name='OncologicoAlistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('numero_orden', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Orden')),
                ('area', models.CharField(default='ONCOLOGICOS', max_length=100, verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Alistamiento Oncológico',
                'verbose_name_plural': 'Alistamientos Oncológicos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OncologicoMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('orden_produccion', models.CharField(max_length=50, unique=True, verbose_name='Orden de Producción')),
                ('quien_prepara', models.CharField(blank=True, max_length=150, null=True, verbose_name='Quien Prepara')),
                ('preelaboracion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Preelaboración')),
                ('alistamiento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Alistamiento')),
                ('quien_cobra', models.CharField(blank=True, max_length=150, null=True, verbose_name='Quien Cobra')),
                ('jefe_produccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Jefe de Producción')),
                ('jefe_control_calidad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Jefe de Control de Calidad')),
            ],
            options={
                'verbose_name': 'Matriz Oncológica (Encabezado)',
                'verbose_name_plural': 'Matrices Oncológicas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OncologicoOrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Nº Orden de Producción')),
            ],
            options={
                'verbose_name': 'Orden de Producción Oncológica',
                'verbose_name_plural': 'Órdenes de Producción Oncológicas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OncologicoAlistamientoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255, verbose_name='Material de Partida')),
                ('lote_fabricante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote Fabricante')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('cantidad_solicitada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad Solicitada')),
                ('cantidad_ingresada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad Ingresada')),
                ('aprovechamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aprovechamiento')),
                ('producto_terminado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Producto Terminado')),
                ('alistamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CentralDeMezclas.oncologicoalistamiento')),
            ],
            options={
                'verbose_name': 'Ítem Alistamiento Oncológico',
                'verbose_name_plural': 'Ítems Alistamiento Oncológico',
            },
        ),
        migrations.CreateModel(
            name='OncologicoMatrizItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_interno', models.CharField(max_length=50, verbose_name='Lote Interno')),
                ('paciente_nombre', models.CharField(max_length=255, verbose_name='Nombre del Paciente')),
                ('identificacion', models.CharField(max_length=50, verbose_name='Identificación')),
                ('cama', models.CharField(max_length=20, verbose_name='Cama')),
                ('servicio', models.CharField(max_length=100, verbose_name='Servicio')),
                ('cod', models.CharField(blank=True, max_length=50, null=True, verbose_name='COD')),
                ('medicamento', models.CharField(max_length=255, verbose_name='Medicamento')),
                ('concentracion', models.CharField(max_length=100, verbose_name='Concentración (mg, UI)')),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma Farmacéutica')),
                ('dosis', models.CharField(max_length=100, verbose_name='Dosis (mg, UI)')),
                ('frecuencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Frecuencia (Cantidad)')),
                ('volumen_final', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volumen Final')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote Fabricante')),
                ('fecha_vencimiento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Vencimiento')),
                ('solucion_diluyente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Solución Diluyente')),
                ('viales_ampollas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Viales/Ampollas')),
                ('vol_dilucion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volumen Dilución')),
                ('vol_dosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volumen de Dosis')),
                ('vol_final_unidosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volumen Final Unidosis')),
                ('via_admon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vía de Administración')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CentralDeMezclas.oncologicomatriz')),
                ('medicamento_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CentralDeMezclas.medicamentooncologico', verbose_name='Medicamento (Catálogo)')),
            ],
            options={
                'verbose_name': 'Ítem Matriz Oncológica',
                'verbose_name_plural': 'Ítems Matriz Oncológica',
            },
        ),
        migrations.CreateModel(
            name='OncologicoOrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=255, verbose_name='Nombre del Paciente')),
                ('identificacion', models.CharField(max_length=50, verbose_name='Identificación')),
                ('cama', models.CharField(max_length=20, verbose_name='Cama')),
                ('medicamento', models.CharField(max_length=255, verbose_name='Medicamento')),
                ('via_administracion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vía de Administración')),
                ('viales_ampollas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Viales/Ampollas')),
                ('vehiculo_reconstitucion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vehículo Reconstitución')),
                ('volumen_reconstitucion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volumen Reconstitución (mL)')),
                ('dosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosis (mg, UI)')),
                ('vol_dosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volumen de Dosis (mL)')),
                ('vehiculo_unidosis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vehículo Unidosis')),
                ('vol_final', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volumen Final (mL)')),
                ('concentracion_final', models.CharField(blank=True, max_length=100, null=True, verbose_name='Concentración Final (mg/mL, UI/mL)')),
                ('lote_interno', models.CharField(max_length=50, verbose_name='Lote Interno')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('recibido', models.BooleanField(default=False, verbose_name='Recibido')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CentralDeMezclas.oncologicoordenproduccion')),
            ],
            options={
                'verbose_name': 'Ítem Orden Producción Oncológica',
                'verbose_name_plural': 'Ítems Orden Producción Oncológica',
            },
        ),
    ]
