# Generated by Django 5.0 on 2026-03-06 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0014_oncologicoalistamiento_oncologicomatriz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezclacontrolcalidad',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controles_aprobados', to='CentralDeMezclas.funcionario', verbose_name='Aprobado por (Jefe Calidad)'),
        ),
        migrations.AddField(
            model_name='mezclacontrolcalidad',
            name='cf_etiqueta_ok',
            field=models.BooleanField(default=True, verbose_name='CF: Etiqueta correcta (Paciente/Lote/Vence)'),
        ),
        migrations.AddField(
            model_name='mezclacontrolcalidad',
            name='cf_hermeticidad',
            field=models.BooleanField(default=True, verbose_name='CF: Hermeticidad y sellado ok'),
        ),
        migrations.AddField(
            model_name='mezclacontrolcalidad',
            name='cf_limpieza',
            field=models.BooleanField(default=True, verbose_name='CF: Envase limpio sin roturas'),
        ),
        migrations.AddField(
            model_name='mezclacontrolcalidad',
            name='ci_concordancia_op',
            field=models.BooleanField(default=True, verbose_name='CI: Concordancia con OP'),
        ),
        migrations.AddField(
            model_name='mezclacontrolcalidad',
            name='ci_fugas',
            field=models.BooleanField(default=True, verbose_name='CI: Sin fugas'),
        ),
        migrations.AddField(
            model_name='mezclacontrolcalidad',
            name='ci_particulas_extranas',
            field=models.BooleanField(default=True, verbose_name='CI: Ausencia de partículas extrañas'),
        ),
        migrations.AddField(
            model_name='mezclacontrolcalidad',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controles_verificados', to='CentralDeMezclas.funcionario', verbose_name='Verificado por'),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='criterio_cantidad',
            field=models.BooleanField(default=True, verbose_name='8. Cantidad total unidades'),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='criterio_concentracion',
            field=models.BooleanField(default=True, verbose_name='6. Concentración, forma, dosis'),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='criterio_dci',
            field=models.BooleanField(default=True, verbose_name='5. Nombre genérico DCI'),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='criterio_indicaciones',
            field=models.BooleanField(default=True, verbose_name='9. Indicaciones, firma, registro'),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='criterio_legibilidad',
            field=models.BooleanField(default=True, verbose_name='10. Letra legible, sin tachones'),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='criterio_lugar_fecha',
            field=models.BooleanField(default=True, verbose_name='2. Lugar, fecha, período'),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='criterio_paciente',
            field=models.BooleanField(default=True, verbose_name='3. Nombre paciente, ID, historia'),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='criterio_periodo',
            field=models.BooleanField(default=True, verbose_name='11. Período duración tratamiento'),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='criterio_prestador',
            field=models.BooleanField(default=True, verbose_name='1. Nombre prestador/profesional'),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='criterio_tipo_usuario',
            field=models.BooleanField(default=True, verbose_name='4. Tipo de usuario'),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='criterio_via_frecuencia',
            field=models.BooleanField(default=True, verbose_name='7. Vía y frecuencia'),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='criterio_vigencia',
            field=models.BooleanField(default=True, verbose_name='12. Vigencia prescripción'),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mezclaorden',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_validadas', to='CentralDeMezclas.funcionario', verbose_name='Validado por (QF)'),
        ),
        migrations.AddField(
            model_name='mezclapreparacion',
            name='alistamiento_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones_alistamiento', to='CentralDeMezclas.funcionario', verbose_name='Alistamiento por'),
        ),
        migrations.AddField(
            model_name='mezclapreparacion',
            name='director_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones_director', to='CentralDeMezclas.funcionario', verbose_name='Director Técnico'),
        ),
        migrations.AddField(
            model_name='mezclapreparacion',
            name='jefe_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones_jefe', to='CentralDeMezclas.funcionario', verbose_name='Jefe de Producción'),
        ),
        migrations.AddField(
            model_name='mezclapreparacion',
            name='qf_preparador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones_qf', to='CentralDeMezclas.funcionario', verbose_name='QF Preparador'),
        ),
        migrations.AddField(
            model_name='mezclapreparacion',
            name='solucion_diluyente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Solución Diluyente'),
        ),
        migrations.AddField(
            model_name='mezclapreparacion',
            name='vehiculo_volumen_final',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vehículo y Vol. Final'),
        ),
        migrations.AddField(
            model_name='mezclapreparacion',
            name='viales_ampollas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Viales/Ampollas'),
        ),
        migrations.AddField(
            model_name='mezclapreparacion',
            name='volumen_dilucion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Volumen Dilución (mL)'),
        ),
        migrations.AddField(
            model_name='mezclapreparacion',
            name='volumen_dosis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Volumen Dosis (mL)'),
        ),
        migrations.AddField(
            model_name='oncologicomatriz',
            name='digitador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oncologico_digitador', to='CentralDeMezclas.funcionario', verbose_name='Digitador'),
        ),
        migrations.AlterField(
            model_name='mezclacontrolcalidad',
            name='controlador_oid',
            field=models.IntegerField(blank=True, null=True, verbose_name='OID del Validador de Calidad'),
        ),
        migrations.AlterField(
            model_name='oncologicomatriz',
            name='alistamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oncologico_alistamiento', to='CentralDeMezclas.funcionario', verbose_name='Alistamiento'),
        ),
        migrations.AlterField(
            model_name='oncologicomatriz',
            name='jefe_control_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oncologico_jefe_calidad', to='CentralDeMezclas.funcionario', verbose_name='Jefe de C. Calidad'),
        ),
        migrations.AlterField(
            model_name='oncologicomatriz',
            name='jefe_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oncologico_jefe_prod', to='CentralDeMezclas.funcionario', verbose_name='Jefe de Producción'),
        ),
        migrations.AlterField(
            model_name='oncologicomatriz',
            name='preelaboracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oncologico_preelab', to='CentralDeMezclas.funcionario', verbose_name='Preelaboración'),
        ),
        migrations.AlterField(
            model_name='oncologicomatriz',
            name='quien_cobra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oncologico_cobra', to='CentralDeMezclas.funcionario', verbose_name='Quien Cobra'),
        ),
        migrations.AlterField(
            model_name='oncologicomatriz',
            name='quien_prepara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oncologico_prepara', to='CentralDeMezclas.funcionario', verbose_name='Quien Prepara'),
        ),
    ]
