# Generated by Django 5.0 on 2026-03-06 01:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0015_mezclacontrolcalidad_aprobado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oncologicomatriz',
            options={},
        ),
        migrations.CreateModel(
            name='MagistralesOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('lote_interno', models.CharField(max_length=50, unique=True, verbose_name='Lote Interno (MAG-...)')),
                ('formula_nombre', models.CharField(max_length=255, verbose_name='Nombre de la Fórmula')),
                ('cantidad_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('preparador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='magistrales_preparador', to='CentralDeMezclas.funcionario')),
                ('validador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='magistrales_validador', to='CentralDeMezclas.funcionario')),
            ],
            options={
                'verbose_name': 'Orden Magistral',
                'verbose_name_plural': 'Órdenes Magistrales',
            },
        ),
        migrations.CreateModel(
            name='NeonatosOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('lote_interno', models.CharField(max_length=50, unique=True, verbose_name='Lote Interno (NEO-...)')),
                ('paciente_nombre', models.CharField(max_length=255)),
                ('historia_clinica', models.CharField(max_length=50)),
                ('medicamento', models.CharField(max_length=255)),
                ('dosis_solicitada', models.CharField(max_length=100)),
                ('volumen_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aprobado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neonatos_aprobado', to='CentralDeMezclas.funcionario')),
                ('elaborado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neonatos_elaborado', to='CentralDeMezclas.funcionario')),
                ('revisado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neonatos_revisado', to='CentralDeMezclas.funcionario')),
            ],
            options={
                'verbose_name': 'Orden Neonatos',
                'verbose_name_plural': 'Órdenes Neonatos',
            },
        ),
        migrations.CreateModel(
            name='NutricionParenteral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('lote_interno', models.CharField(max_length=50, unique=True, verbose_name='Lote Interno (NPT-...)')),
                ('paciente', models.CharField(max_length=255)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volumen_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dextrosa_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aminoacidos_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lipidos_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quien_prepara', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='npt_prepara', to='CentralDeMezclas.funcionario')),
                ('quien_valida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='npt_valida', to='CentralDeMezclas.funcionario')),
            ],
            options={
                'verbose_name': 'Matriz Oncológica (Encabezado)',
                'verbose_name_plural': 'Matrices Oncológicas',
                'ordering': ['-fecha'],
            },
        ),
    ]
