# Generated by Django 5.0 on 2026-03-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0016_alter_oncologicomatriz_options_magistralesorden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentoesteril',
            name='es_control_especial',
            field=models.BooleanField(default=False, verbose_name='ACE (Control Especial)'),
        ),
        migrations.AddField(
            model_name='medicamentooncologico',
            name='es_control_especial',
            field=models.BooleanField(default=False, verbose_name='ACE (Control Especial)'),
        ),
    ]
