# Generated by Django 5.0 on 2026-03-06 03:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0017_medicamentoesteril_es_control_especial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutricionparenteral',
            name='quien_prepara',
        ),
        migrations.RemoveField(
            model_name='nutricionparenteral',
            name='quien_valida',
        ),
        migrations.AddField(
            model_name='nutricionparenteral',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npt_aprobado', to='CentralDeMezclas.funcionario'),
        ),
        migrations.AddField(
            model_name='nutricionparenteral',
            name='elaborado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npt_elaborado', to='CentralDeMezclas.funcionario'),
        ),
        migrations.AddField(
            model_name='nutricionparenteral',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npt_revisado', to='CentralDeMezclas.funcionario'),
        ),
        migrations.AddField(
            model_name='reempaqueorden',
            name='tipo',
            field=models.CharField(choices=[('REEMPAQUE', 'Reempaque (Sólidos)'), ('REENVASE', 'Reenvase (Líquidos/Semisólidos)')], default='REEMPAQUE', max_length=20, verbose_name='Tipo de Proceso'),
        ),
        migrations.AlterField(
            model_name='neonatosorden',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neonatos_aprobado', to='CentralDeMezclas.funcionario'),
        ),
        migrations.AlterField(
            model_name='neonatosorden',
            name='elaborado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neonatos_elaborado', to='CentralDeMezclas.funcionario'),
        ),
        migrations.AlterField(
            model_name='neonatosorden',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neonatos_revisado', to='CentralDeMezclas.funcionario'),
        ),
        migrations.CreateModel(
            name='UnidosisProduccionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('lote_interno', models.CharField(max_length=50, unique=True, verbose_name='Lote Interno (UNI-...)')),
                ('medicamento', models.CharField(max_length=255, verbose_name='Medicamento / Mezcla')),
                ('cantidad_unidades', models.IntegerField(verbose_name='Cantidad Unidades')),
                ('volumen_individual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volumen (mL/und)')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidosis_aprobado', to='CentralDeMezclas.funcionario')),
                ('elaborado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidosis_elaborado', to='CentralDeMezclas.funcionario')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidosis_revisado', to='CentralDeMezclas.funcionario')),
            ],
            options={
                'verbose_name': 'Orden de Producción Unidosis',
                'verbose_name_plural': 'Órdenes de Producción Unidosis',
            },
        ),
        migrations.DeleteModel(
            name='MagistralesOrden',
        ),
    ]
