# Generated by Django 5.2.11 on 2026-03-20 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0018_remove_nutricionparenteral_quien_prepara_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeonatosMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(blank=True, null=True, verbose_name='COD.')),
                ('producto', models.CharField(max_length=255, verbose_name='PRODUCTO')),
                ('medicamento', models.CharField(max_length=255, verbose_name='MEDICAMENTO')),
                ('concentracion', models.CharField(max_length=100, verbose_name='CONCENTRACIÓN')),
                ('forma_farmaceutica', models.CharField(max_length=100, verbose_name='FORMA FARMACÉUTICA')),
                ('volumen_reconstitucion', models.CharField(blank=True, max_length=100, null=True, verbose_name='VOLUMEN DE RECONSTITUCIÓN')),
                ('solucion_reconstitucion', models.CharField(blank=True, max_length=255, null=True, verbose_name='SOLUCIÓN DE RECONSTITUCIÓN')),
                ('cod_dil', models.CharField(blank=True, max_length=50, null=True, verbose_name='COD. DIL.')),
                ('administracion', models.CharField(blank=True, max_length=50, null=True, verbose_name='ADMINISTRACIÓN')),
                ('vol_final', models.CharField(blank=True, max_length=100, null=True, verbose_name='VOL. FINAL (mL)')),
                ('vehiculo', models.CharField(blank=True, max_length=255, null=True, verbose_name='VEHÍCULO')),
                ('jeringa', models.CharField(blank=True, max_length=255, null=True, verbose_name='JERINGA')),
                ('aguja', models.CharField(blank=True, max_length=255, null=True, verbose_name='AGUJA')),
                ('almacenamiento', models.CharField(blank=True, max_length=255, null=True, verbose_name='ALMACENAMIENTO')),
                ('proteccion_luz', models.CharField(blank=True, max_length=255, null=True, verbose_name='PROTECCIÓN LUZ / OBSERVACIONES')),
                ('fecha_expiracion', models.CharField(blank=True, max_length=100, null=True, verbose_name='FECHA DE EXPIRACIÓN')),
            ],
            options={
                'verbose_name': 'Medicamento Neonato (Base)',
                'verbose_name_plural': 'Medicamentos Neonatos (Base)',
                'ordering': ['medicamento'],
            },
        ),
        migrations.CreateModel(
            name='NeonatosOrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Nº Orden de Producción')),
            ],
            options={
                'verbose_name': 'Orden de Producción Neonatos',
                'verbose_name_plural': 'Órdenes de Producción Neonatos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NeonatosAlistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Alistamiento')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CentralDeMezclas.funcionario', verbose_name='Responsable Alistamiento')),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alistamientos', to='CentralDeMezclas.neonatosordenproduccion', verbose_name='Orden de Producción')),
            ],
            options={
                'verbose_name': 'Alistamiento Neonatos',
                'verbose_name_plural': 'Alistamientos Neonatos',
            },
        ),
        migrations.CreateModel(
            name='NeonatosAlistamientoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_med', models.CharField(max_length=50, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción (Medicamento/Acondicionamiento)')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento')),
                ('cantidad_entregada', models.IntegerField(verbose_name='Cantidad Entregada')),
                ('cantidad_devuelta', models.IntegerField(default=0, verbose_name='Cantidad Devuelta')),
                ('cantidad_averiada', models.IntegerField(default=0, verbose_name='Cantidad Averiada')),
                ('cantidad_consumida', models.IntegerField(default=0, verbose_name='Cantidad Consumida')),
                ('alistamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CentralDeMezclas.neonatosalistamiento')),
            ],
            options={
                'verbose_name': 'Ítem Alistamiento Neonatos',
                'verbose_name_plural': 'Ítems Alistamiento Neonatos',
            },
        ),
        migrations.CreateModel(
            name='NeonatosMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('orden_produccion', models.CharField(max_length=50, unique=True, verbose_name='Orden de Producción')),
                ('alistamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neonato_alistamiento', to='CentralDeMezclas.funcionario', verbose_name='Alistamiento')),
                ('digitador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neonato_digitador', to='CentralDeMezclas.funcionario', verbose_name='Digitador')),
                ('jefe_control_calidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neonato_jefe_calidad', to='CentralDeMezclas.funcionario', verbose_name='Jefe de C. Calidad')),
                ('jefe_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neonato_jefe_prod', to='CentralDeMezclas.funcionario', verbose_name='Jefe de Producción')),
                ('preelaboracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neonato_preelab', to='CentralDeMezclas.funcionario', verbose_name='Preelaboración')),
                ('quien_cobra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neonato_cobra', to='CentralDeMezclas.funcionario', verbose_name='Quien Cobra')),
                ('quien_prepara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neonato_prepara', to='CentralDeMezclas.funcionario', verbose_name='Quien Prepara')),
            ],
            options={
                'verbose_name': 'Matriz Neonatos (Encabezado)',
                'verbose_name_plural': 'Matrices Neonatos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NeonatosMatrizItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_interno', models.CharField(max_length=50, verbose_name='Lote Interno')),
                ('paciente_nombre', models.CharField(max_length=255, verbose_name='Nombre del Paciente')),
                ('identificacion', models.CharField(max_length=50, verbose_name='Identificación')),
                ('cama', models.CharField(max_length=20, verbose_name='Cama')),
                ('servicio', models.CharField(max_length=100, verbose_name='Servicio')),
                ('cod', models.CharField(blank=True, max_length=50, null=True, verbose_name='COD')),
                ('medicamento', models.CharField(max_length=255, verbose_name='Medicamento')),
                ('concentracion', models.CharField(max_length=100, verbose_name='Concentración')),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma Farmacéutica')),
                ('dosis', models.CharField(max_length=100, verbose_name='Dosis')),
                ('frecuencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Frecuencia')),
                ('volumen_final', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volumen Final')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote Fabricante')),
                ('fecha_vencimiento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Vencimiento')),
                ('solucion_diluyente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Solución Diluyente')),
                ('viales_ampollas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Viales/Ampollas')),
                ('vol_dilucion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volumen Dilución')),
                ('vol_dosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volumen de Dosis')),
                ('vol_final_unidosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volumen Final Unidosis')),
                ('via_admon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vía de Administración')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CentralDeMezclas.neonatosmatriz')),
                ('medicamento_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CentralDeMezclas.neonatosmedicamento', verbose_name='Medicamento (Catálogo)')),
            ],
            options={
                'verbose_name': 'Ítem Matriz Neonatos',
                'verbose_name_plural': 'Ítems Matriz Neonatos',
            },
        ),
        migrations.CreateModel(
            name='NeonatosOrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_interno', models.CharField(max_length=50, verbose_name='Lote Interno')),
                ('medicamento', models.CharField(max_length=255, verbose_name='Medicamento')),
                ('lote_fabricante', models.CharField(max_length=50, verbose_name='Lote Fabricante')),
                ('cantidad_unidades', models.IntegerField(verbose_name='Cantidad Unidades')),
                ('volumen_etiquetar', models.CharField(max_length=100, verbose_name='Volumen a Etiquetar')),
                ('preparador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neonato_orden_prep', to='CentralDeMezclas.funcionario')),
                ('verificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neonato_orden_verif', to='CentralDeMezclas.funcionario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CentralDeMezclas.neonatosordenproduccion')),
            ],
            options={
                'verbose_name': 'Ítem Orden de Producción Neonatos',
                'verbose_name_plural': 'Ítems Orden de Producción Neonatos',
            },
        ),
        migrations.DeleteModel(
            name='NeonatosOrden',
        ),
    ]
