# Generated by Django 5.2.11 on 2026-03-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0019_neonatosmedicamento_neonatosordenproduccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reempaquecontrol',
            name='responsable_liberacion_oid',
        ),
        migrations.RemoveField(
            model_name='reempaqueorden',
            name='farmaceutico_validador_oid',
        ),
        migrations.RemoveField(
            model_name='reempaqueorden',
            name='responsable_reempaque_oid',
        ),
        migrations.AddField(
            model_name='reempaquecontrol',
            name='responsable_liberacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reempaques_liberacion', to='CentralDeMezclas.funcionario', verbose_name='Responsable Liberación (QF)'),
        ),
        migrations.AddField(
            model_name='reempaqueorden',
            name='farmaceutico_validador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reempaques_validador', to='CentralDeMezclas.funcionario', verbose_name='Farmacéutico Validador'),
        ),
        migrations.AddField(
            model_name='reempaqueorden',
            name='responsable_reempaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reempaques_responsable', to='CentralDeMezclas.funcionario', verbose_name='Responsable de Reempaque'),
        ),
    ]
