# Generated by Django 5.0 on 2026-03-23 23:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0020_remove_reempaquecontrol_responsable_liberacion_oid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NptOrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Nº Orden de Producción')),
            ],
            options={
                'verbose_name': 'Orden de Producción NPT',
                'verbose_name_plural': 'Órdenes de Producción NPT',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='oncologicomatriz',
            options={'ordering': ['-fecha'], 'verbose_name': 'Matriz Oncológica (Encabezado)', 'verbose_name_plural': 'Matrices Oncológicas'},
        ),
        migrations.CreateModel(
            name='NptAlistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Alistamiento')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CentralDeMezclas.funcionario', verbose_name='Responsable Alistamiento')),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alistamientos', to='CentralDeMezclas.nptordenproduccion', verbose_name='Orden de Producción')),
            ],
            options={
                'verbose_name': 'Alistamiento NPT',
                'verbose_name_plural': 'Alistamientos NPT',
            },
        ),
        migrations.CreateModel(
            name='NptAlistamientoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255, verbose_name='Material de Partida')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento')),
                ('cantidad_solicitada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad Solicitada')),
                ('cantidad_ingresada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad Ingresada')),
                ('aprovechamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aprovechamiento')),
                ('producto_terminado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Producto Terminado')),
                ('alistamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CentralDeMezclas.nptalistamiento')),
            ],
            options={
                'verbose_name': 'Ítem Alistamiento NPT',
                'verbose_name_plural': 'Ítems Alistamiento NPT',
            },
        ),
        migrations.CreateModel(
            name='NptMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('orden_produccion', models.CharField(max_length=50, unique=True, verbose_name='Orden de Producción')),
                ('alistamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npt_alistamiento', to='CentralDeMezclas.funcionario')),
                ('digitador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npt_digitador', to='CentralDeMezclas.funcionario')),
                ('director_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npt_director', to='CentralDeMezclas.funcionario')),
                ('jefe_control_calidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npt_jefe_cal', to='CentralDeMezclas.funcionario')),
                ('jefe_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npt_jefe_prod', to='CentralDeMezclas.funcionario')),
                ('preelaboracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npt_preelab', to='CentralDeMezclas.funcionario')),
                ('qf_preparador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npt_prepara', to='CentralDeMezclas.funcionario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npt_registra', to='CentralDeMezclas.funcionario')),
            ],
            options={
                'verbose_name': 'Matriz NPT (Encabezado)',
                'verbose_name_plural': 'Matrices NPT',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NptMatrizItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_interno', models.CharField(max_length=50, verbose_name='Lote Interno')),
                ('cod', models.CharField(blank=True, max_length=50, null=True, verbose_name='COD.')),
                ('medicamento', models.CharField(max_length=255, verbose_name='Medicamento')),
                ('paciente_nombre', models.CharField(max_length=255, verbose_name='Nombre de Paciente')),
                ('identificacion', models.CharField(max_length=50, verbose_name='Identificación')),
                ('servicio', models.CharField(max_length=100, verbose_name='Servicio')),
                ('cama', models.CharField(max_length=20, verbose_name='Cama')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso')),
                ('volumen_dextrosa', models.CharField(blank=True, max_length=50, null=True, verbose_name='VOLUMEN DEXTROSA')),
                ('concentracion_dextrosa', models.CharField(blank=True, max_length=50, null=True, verbose_name='CONCENTRACION DEXTROSA')),
                ('aa_neonatos_10', models.CharField(blank=True, max_length=50, null=True, verbose_name='A.A. Neonatos 10%')),
                ('aa_adultos_10', models.CharField(blank=True, max_length=50, null=True, verbose_name='A.A. Adultos 10%')),
                ('aa_adultos_15', models.CharField(blank=True, max_length=50, null=True, verbose_name='A.A. Adultos 15%')),
                ('glutamina', models.CharField(blank=True, max_length=50, null=True, verbose_name='Glutamina')),
                ('omegaven', models.CharField(blank=True, max_length=50, null=True, verbose_name='Omegaven')),
                ('acidos_grasos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Acidos Grasos')),
                ('sodio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sodio (Na)')),
                ('potasio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Potasio (K)')),
                ('glicerol_fosfato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Glicerol Fosfato')),
                ('calcio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calcio (Ca)')),
                ('magnesio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Magnesio (Mg)')),
                ('multivitamina_cernevit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Multivitamina (Cernevit)')),
                ('multi_hidro_neo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Multivitamina Hidrosoluble Neo')),
                ('multi_lipo_neo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Multivitamina Liposoluble Neo')),
                ('vitamina_c', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vitamina C')),
                ('elementos_traza_neo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Elementos traza Neonatos (Peditrace)')),
                ('elementos_traza_adultos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Elementos traza Adultos')),
                ('profesional_tratante', models.CharField(blank=True, max_length=255, null=True, verbose_name='PROFESIONAL TRATANTE')),
                ('ajuste_flujo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ajuste de Flujo')),
                ('volumen_total', models.CharField(blank=True, max_length=50, null=True, verbose_name='Volumen Total')),
                ('volumen_total_purga', models.CharField(blank=True, max_length=50, null=True, verbose_name='Volumen Total + Purga')),
                ('bolsa_eva_formulada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bolsa EVA formulada')),
                ('bolsa_final', models.CharField(blank=True, max_length=50, null=True, verbose_name='BOLSA FINAL')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CentralDeMezclas.nptmatriz')),
            ],
            options={
                'verbose_name': 'Ítem Matriz NPT',
                'verbose_name_plural': 'Ítems Matriz NPT',
            },
        ),
        migrations.CreateModel(
            name='NptOrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_interno', models.CharField(max_length=50, verbose_name='Lote Interno')),
                ('paciente_nombre', models.CharField(max_length=255, verbose_name='Nombre del Paciente')),
                ('medicamento', models.CharField(max_length=255, verbose_name='Medicamento')),
                ('volumen_final', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volumen Final')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CentralDeMezclas.nptordenproduccion')),
            ],
            options={
                'verbose_name': 'Ítem Orden NPT',
                'verbose_name_plural': 'Ítems Orden NPT',
            },
        ),
        migrations.DeleteModel(
            name='NutricionParenteral',
        ),
    ]
