# Generated by Django 5.2.10 on 2026-04-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralDeMezclas', '0021_nptordenproduccion_alter_oncologicomatriz_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='convencionformafarmaceutica',
            options={},
        ),
        migrations.AlterField(
            model_name='alerta',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='convencionformafarmaceutica',
            name='via',
            field=models.CharField(max_length=100, verbose_name='Vía de administración'),
        ),
    ]
